"""Endpoints under `/api/1/combo`.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any

from iikocloudapi._resource import Resource
from iikocloudapi.models.common import OrderItem
from iikocloudapi.models.general import (
    CalculateComboPriceRequest,
    CalculateComboPriceResponse,
    GetCombosInfoRequest,
    GetCombosInfoResponse,
)


class ComboResource(Resource):
    """Endpoints under `/api/1/combo`."""

    __slots__ = ()

    async def __call__(
        self,
        *,
        organization_id: str,
        extra_data: bool | None = None,
        timeout: float | None = None,
    ) -> GetCombosInfoResponse:
        """Get combos info.

        `POST /api/1/combo`

        Get all organization's combos.

        Restriction group: `Data: menu`.

        Args:
            organization_id: Organization id.
            extra_data: Extra data.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `GetCombosInfoResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Menu/paths/~1api~11~1combo/post)
        """
        return await self._client._call(
            "/api/1/combo",
            GetCombosInfoRequest,
            {"organization_id": organization_id, "extra_data": extra_data},
            GetCombosInfoResponse,
            timeout=timeout,
        )

    async def calculate(
        self,
        *,
        items: Sequence[OrderItem | Mapping[str, Any]],
        organization_id: str,
        timeout: float | None = None,
    ) -> CalculateComboPriceResponse:
        """Calculate combo price.

        `POST /api/1/combo/calculate`

        Make combo price calculation.

        Restriction group: `Loyalty: order calculate`.

        Args:
            items: Items with modifiers included in combo.
            organization_id: Organization id.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `CalculateComboPriceResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Menu/paths/~1api~11~1combo~1calculate/post)
        """
        return await self._client._call(
            "/api/1/combo/calculate",
            CalculateComboPriceRequest,
            {"items": items, "organization_id": organization_id},
            CalculateComboPriceResponse,
            timeout=timeout,
        )


__all__ = [
    "ComboResource",
]
