"""Endpoints under `/api/1/delivery_restrictions`.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

import datetime
from collections.abc import Mapping, Sequence
from decimal import Decimal
from typing import Any

from iikocloudapi._resource import Resource
from iikocloudapi.models.delivery import (
    GetAllowedRestrictionsRequest,
    GetAllowedRestrictionsResponse,
    GetDeliveryRestrictionsRequest,
    GetDeliveryRestrictionsResponse,
    OrderLocation,
    RestrictionsAddress,
    RestrictionsOrderItem,
)


class DeliveryRestrictionsResource(Resource):
    """Endpoints under `/api/1/delivery_restrictions`."""

    __slots__ = ()

    async def __call__(
        self,
        *,
        organization_ids: Sequence[str],
        timeout: float | None = None,
    ) -> GetDeliveryRestrictionsResponse:
        """Retrieve list of delivery restrictions.

        `POST /api/1/delivery_restrictions`

        Allowed from version `6.4.16`.

        Restriction group: `Data: dictionaries`.

        Args:
            organization_ids: Organizations IDs which delivery restrictions have to be returned. Can be obtained by `/api/1/organizations` operation.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `GetDeliveryRestrictionsResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Delivery-restrictions/paths/~1api~11~1delivery_restrictions/post)
        """
        return await self._client._call(
            "/api/1/delivery_restrictions",
            GetDeliveryRestrictionsRequest,
            {"organization_ids": organization_ids},
            GetDeliveryRestrictionsResponse,
            timeout=timeout,
        )

    async def allowed(
        self,
        *,
        is_courier_delivery: bool,
        organization_id: str | None = None,
        organization_ids: Sequence[str] | None = None,
        delivery_address: RestrictionsAddress | Mapping[str, Any] | None = None,
        order_location: OrderLocation | Mapping[str, Any] | None = None,
        order_items: Sequence[RestrictionsOrderItem | Mapping[str, Any]] | None = None,
        delivery_date: datetime.datetime | str | None = None,
        delivery_sum: Decimal | float | None = None,
        discount_sum: Decimal | float | None = None,
        timeout: float | None = None,
    ) -> GetAllowedRestrictionsResponse:
        """Get suitable terminal groups for delivery restrictions.

        `POST /api/1/delivery_restrictions/allowed`

        Allowed from version `6.4.16`.

        Restriction group: `Orders: preparing`.

        Args:
            is_courier_delivery: Type of delivery service.
            organization_id: **Deprecated.** Organization ID. Deprecated, use "organizationIds".
            organization_ids: Organization IDs. Can be obtained by `/api/1/organizations` operation.
            delivery_address: Delivery address.
            order_location: Order location.
            order_items: Order list.
            delivery_date: Delivery date (Local for delivery terminal).
            delivery_sum: Sum.
            discount_sum: Discounts sum.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `GetAllowedRestrictionsResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Delivery-restrictions/paths/~1api~11~1delivery_restrictions~1allowed/post)
        """
        return await self._client._call(
            "/api/1/delivery_restrictions/allowed",
            GetAllowedRestrictionsRequest,
            {
                "is_courier_delivery": is_courier_delivery,
                "organization_id": organization_id,
                "organization_ids": organization_ids,
                "delivery_address": delivery_address,
                "order_location": order_location,
                "order_items": order_items,
                "delivery_date": delivery_date,
                "delivery_sum": delivery_sum,
                "discount_sum": discount_sum,
            },
            GetAllowedRestrictionsResponse,
            timeout=timeout,
        )


__all__ = [
    "DeliveryRestrictionsResource",
]
