"""Endpoints under `/api`.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any

from iikocloudapi._resource import Resource
from iikocloudapi.models.employees import (
    AttendanceCreateRequest,
    AttendanceCreateResponse,
    AttendanceDeleteRequest,
    AttendanceDeleteResponse,
    AttendanceListRequest,
    AttendanceListResponse,
    AttendanceTypeListRequest,
    AttendanceTypeListResponse,
    AttendanceUpdateRequest,
    AttendanceUpdateResponse,
    EmployeeCreateRequest,
    EmployeeFilter,
    EmployeeFireRequest,
    EmployeeFireResponse,
    EmployeeGetRequest,
    EmployeeListRequest,
    EmployeePositionFilterItem,
    EmployeePositionResponse,
    EmployeeResponse,
    EmployeeRestoreRequest,
    EmployeeRestoreResponse,
    EmployeeUpdateRequest,
    GetPositionRequest,
    ListPositionsRequest,
    ListPositionsResponse,
    SwaggerEmployeeListResponse,
)
from iikocloudapi.models.general import (
    ActiveCourierLocationsByTerminalGroupRequest,
    ActiveCourierLocationsResponse,
    ChangePersonalSessionResponse,
    ClosePersonalSessionRequest,
    CourierLocationsByTimeOffsetRequest,
    CourierLocationsByTimeOffsetResponse,
    CouriersAndCheckRoleRequest,
    CouriersRequest,
    EmployeeInfoRequest,
    EmployeeInfoResponse,
    EmployeesResponse,
    EmployeesWithRoleSignResponse,
    GetPersonalSessionInfoRequest,
    GetPersonalSessionInfoResponse,
    GetTerminalGroupsOfEmployeeRequest,
    GetTerminalGroupsOfEmployeeResponse,
    OpenPersonalSessionRequest,
)


class EmployeesShiftsResource(Resource):
    """Endpoints under `/api/1/employees/shifts/by_courier`."""

    __slots__ = ()

    async def by_courier(
        self,
        *,
        employee_id: str,
        timeout: float | None = None,
    ) -> GetTerminalGroupsOfEmployeeResponse:
        """Get terminal groups where employee session is opened.

        `POST /api/1/employees/shifts/by_courier`

        Restriction group: `Employees: shifts`.

        Args:
            employee_id: See the API reference.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `GetTerminalGroupsOfEmployeeResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees/paths/~1api~11~1employees~1shifts~1by_courier/post)
        """
        return await self._client._call(
            "/api/1/employees/shifts/by_courier",
            GetTerminalGroupsOfEmployeeRequest,
            {"employee_id": employee_id},
            GetTerminalGroupsOfEmployeeResponse,
            timeout=timeout,
        )


class EmployeesShiftResource(Resource):
    """Endpoints under `/api/1/employees/shift`."""

    __slots__ = ()

    async def clockin(
        self,
        *,
        organization_id: str,
        terminal_group_id: str,
        employee_id: str,
        role_id: str | None = None,
        timeout: float | None = None,
    ) -> ChangePersonalSessionResponse:
        """Open personal session.

        `POST /api/1/employees/shift/clockin`

        Restriction group: `Employees: shifts`.

        Note:
            This method is a command: it only starts the operation. Pass the response to
            `IikoCloud.wait()` to wait for the result.

        Args:
            organization_id: Organization ID. Can be obtained by `/api/1/organizations` operation.
            terminal_group_id: Delivery group ID. Can be obtained by `/api/1/terminal_groups` operation.
            employee_id: Employee ID.
            role_id: Employee role ID. Must be null if the restaurant doesn't use roles, otherwise not-null role must be specified.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `ChangePersonalSessionResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees/paths/~1api~11~1employees~1shift~1clockin/post)
        """
        return await self._client._call(
            "/api/1/employees/shift/clockin",
            OpenPersonalSessionRequest,
            {
                "organization_id": organization_id,
                "terminal_group_id": terminal_group_id,
                "employee_id": employee_id,
                "role_id": role_id,
            },
            ChangePersonalSessionResponse,
            timeout=timeout,
        )

    async def clockout(
        self,
        *,
        organization_id: str,
        terminal_group_id: str,
        employee_id: str,
        timeout: float | None = None,
    ) -> ChangePersonalSessionResponse:
        """Close personal session.

        `POST /api/1/employees/shift/clockout`

        Restriction group: `Employees: shifts`.

        Note:
            This method is a command: it only starts the operation. Pass the response to
            `IikoCloud.wait()` to wait for the result.

        Args:
            organization_id: Organization ID. Can be obtained by `/api/1/organizations` operation.
            terminal_group_id: Delivery group ID. Can be obtained by `/api/1/terminal_groups` operation.
            employee_id: Employee ID.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `ChangePersonalSessionResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees/paths/~1api~11~1employees~1shift~1clockout/post)
        """
        return await self._client._call(
            "/api/1/employees/shift/clockout",
            ClosePersonalSessionRequest,
            {"organization_id": organization_id, "terminal_group_id": terminal_group_id, "employee_id": employee_id},
            ChangePersonalSessionResponse,
            timeout=timeout,
        )

    async def is_open(
        self,
        *,
        organization_id: str,
        terminal_group_id: str,
        employee_id: str,
        timeout: float | None = None,
    ) -> GetPersonalSessionInfoResponse:
        """Check if personal session is open.

        `POST /api/1/employees/shift/is_open`

        Restriction group: `Employees: shifts`.

        Args:
            organization_id: Organization ID. Can be obtained by `/api/1/organizations` operation.
            terminal_group_id: Delivery group ID. Can be obtained by `/api/1/terminal_groups` operation.
            employee_id: Employee ID.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `GetPersonalSessionInfoResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees/paths/~1api~11~1employees~1shift~1is_open/post)
        """
        return await self._client._call(
            "/api/1/employees/shift/is_open",
            GetPersonalSessionInfoRequest,
            {"organization_id": organization_id, "terminal_group_id": terminal_group_id, "employee_id": employee_id},
            GetPersonalSessionInfoResponse,
            timeout=timeout,
        )


class EmployeesPositionsResource(Resource):
    """Endpoints under `/api/employees/v1/positions`."""

    __slots__ = ()

    async def get(
        self,
        *,
        id: str | None = None,
        revision_from: int | None = None,
        timeout: float | None = None,
    ) -> EmployeePositionResponse:
        """Get employee position by identifier.

        `POST /api/employees/v1/positions/get`

        Returns full information about an employee position by identifier

        Args:
            id: Employee position identifier (GUID)
            revision_from: Revision from which to return changed records (optional)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `EmployeePositionResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees.Positions/paths/~1api~1employees~1v1~1positions~1get/post)
        """
        return await self._client._call(
            "/api/employees/v1/positions/get",
            GetPositionRequest,
            {"id": id, "revision_from": revision_from},
            EmployeePositionResponse,
            timeout=timeout,
        )

    async def list(
        self,
        *,
        filters: Sequence[EmployeePositionFilterItem | Mapping[str, Any]] | None = None,
        limit: int | None = None,
        offset: int | None = None,
        revision_from: int | None = None,
        timeout: float | None = None,
    ) -> ListPositionsResponse:
        """List employee positions.

        `POST /api/employees/v1/positions/list`

        Returns a paginated list of employee positions with filter support

        Args:
            filters: List of filters (fields: isDeleted, scheduleTypes)
            limit: Maximum number of records in the response (default: 50, max: 1000)
            offset: Number of records to skip from the beginning (0-based)
            revision_from: Revision from which to return changed records (optional)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `ListPositionsResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees.Positions/paths/~1api~1employees~1v1~1positions~1list/post)
        """
        return await self._client._call(
            "/api/employees/v1/positions/list",
            ListPositionsRequest,
            {"filters": filters, "limit": limit, "offset": offset, "revision_from": revision_from},
            ListPositionsResponse,
            timeout=timeout,
        )


class EmployeesEmployeeResource(Resource):
    """Endpoints under `/api/employees/v1/employee`."""

    __slots__ = ()

    async def create(
        self,
        *,
        code: str,
        main_organization_id: str,
        card_number: str | None = None,
        email: str | None = None,
        first_name: str | None = None,
        hire_date: str | None = None,
        last_name: str | None = None,
        main_role_id: str | None = None,
        middle_name: str | None = None,
        name: str | None = None,
        note: str | None = None,
        organization_ids: Sequence[str] | None = None,
        phone: str | None = None,
        responsible_for_organization_ids: Sequence[str] | None = None,
        timeout: float | None = None,
    ) -> EmployeeResponse:
        """Create employee.

        `POST /api/employees/v1/employee/create`

        Creates an employee

        Args:
            code: Code
            main_organization_id: Identifier (organizationId) of the employee's main organization
            card_number: Card number
            email: E-mail
            first_name: First name
            hire_date: Employee hire date. Can be `null`
            last_name: Last name
            main_role_id: Position identifier
            middle_name: Middle name
            name: Employee name in the system
            note: Notes
            organization_ids: Identifiers (organizationId) of the employee's organizations
            phone: Phone
            responsible_for_organization_ids: Identifiers (organizationId) of the organizations the employee is responsible for
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `EmployeeResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees.Employees/paths/~1api~1employees~1v1~1employee~1create/post)
        """
        return await self._client._call(
            "/api/employees/v1/employee/create",
            EmployeeCreateRequest,
            {
                "code": code,
                "main_organization_id": main_organization_id,
                "card_number": card_number,
                "email": email,
                "first_name": first_name,
                "hire_date": hire_date,
                "last_name": last_name,
                "main_role_id": main_role_id,
                "middle_name": middle_name,
                "name": name,
                "note": note,
                "organization_ids": organization_ids,
                "phone": phone,
                "responsible_for_organization_ids": responsible_for_organization_ids,
            },
            EmployeeResponse,
            timeout=timeout,
        )

    async def fire(
        self,
        *,
        ids: Sequence[str],
        timeout: float | None = None,
    ) -> EmployeeFireResponse:
        """Fire employees.

        `POST /api/employees/v1/employee/fire`

        Fires up to 100 employees (soft delete)

        Args:
            ids: List of employee identifiers to fire
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `EmployeeFireResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees.Employees/paths/~1api~1employees~1v1~1employee~1fire/post)
        """
        return await self._client._call(
            "/api/employees/v1/employee/fire",
            EmployeeFireRequest,
            {"ids": ids},
            EmployeeFireResponse,
            timeout=timeout,
        )

    async def get(
        self,
        *,
        id: str,
        timeout: float | None = None,
    ) -> EmployeeResponse:
        """Get employee.

        `POST /api/employees/v1/employee/get`

        Returns a full employee profile by id

        Args:
            id: Employee identifier
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `EmployeeResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees.Employees/paths/~1api~1employees~1v1~1employee~1get/post)
        """
        return await self._client._call(
            "/api/employees/v1/employee/get",
            EmployeeGetRequest,
            {"id": id},
            EmployeeResponse,
            timeout=timeout,
        )

    async def list(
        self,
        *,
        filters: Sequence[EmployeeFilter | Mapping[str, Any]],
        fields_: Sequence[str] | None = None,
        limit: int | None = None,
        offset: int | None = None,
        timeout: float | None = None,
    ) -> SwaggerEmployeeListResponse:
        """List of employees.

        `POST /api/employees/v1/employee/list`

        Returns a paginated list of employees

        Args:
            filters: Filter fields.
            fields_: Requested response fields: `id`, `code`, `firstName`, `lastName`, `middleName`, `name`, `phone`, `email`, `cardNumber`, `mainRoleId`, `roleIds`, `isSystem`, `isFired`, `hireDate`, `fireDate`, `note`, `mainOrganizationId`, `organizationIds`, `responsibleForOrganizationIds`. If empty - returns 4 fields only: `id`, `name`, `code`, `isFired`.
            limit: Maximum number of records in the response.
            offset: Number of records to skip from the beginning.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `SwaggerEmployeeListResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees.Employees/paths/~1api~1employees~1v1~1employee~1list/post)
        """
        return await self._client._call(
            "/api/employees/v1/employee/list",
            EmployeeListRequest,
            {"filters": filters, "fields_": fields_, "limit": limit, "offset": offset},
            SwaggerEmployeeListResponse,
            timeout=timeout,
        )

    async def restore(
        self,
        *,
        id: str,
        timeout: float | None = None,
    ) -> EmployeeRestoreResponse:
        """Restore employee.

        `POST /api/employees/v1/employee/restore`

        Restores a fired employee (undoes soft delete)

        Args:
            id: Employee identifier
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `EmployeeRestoreResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees.Employees/paths/~1api~1employees~1v1~1employee~1restore/post)
        """
        return await self._client._call(
            "/api/employees/v1/employee/restore",
            EmployeeRestoreRequest,
            {"id": id},
            EmployeeRestoreResponse,
            timeout=timeout,
        )

    async def update(
        self,
        *,
        id: str,
        card_number: str | None = None,
        code: str | None = None,
        email: str | None = None,
        first_name: str | None = None,
        hire_date: str | None = None,
        last_name: str | None = None,
        main_organization_id: str | None = None,
        main_role_id: str | None = None,
        middle_name: str | None = None,
        name: str | None = None,
        note: str | None = None,
        organization_ids: Sequence[str] | None = None,
        phone: str | None = None,
        responsible_for_organization_ids: Sequence[str] | None = None,
        timeout: float | None = None,
    ) -> EmployeeResponse:
        """Update employee.

        `POST /api/employees/v1/employee/update`

        Partially updates an employee

        Args:
            id: Employee identifier
            card_number: Card number
            code: Code
            email: E-mail
            first_name: First name
            hire_date: Employee hire date. Can be `null`
            last_name: Last name
            main_organization_id: Identifier (organizationId) of the employee's main organization
            main_role_id: Position identifier
            middle_name: Middle name
            name: Employee name in the system
            note: Notes
            organization_ids: Identifiers (organizationId) of the employee's organizations
            phone: Phone
            responsible_for_organization_ids: Identifiers (organizationId) of the organizations the employee is responsible for
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `EmployeeResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees.Employees/paths/~1api~1employees~1v1~1employee~1update/post)
        """
        return await self._client._call(
            "/api/employees/v1/employee/update",
            EmployeeUpdateRequest,
            {
                "id": id,
                "card_number": card_number,
                "code": code,
                "email": email,
                "first_name": first_name,
                "hire_date": hire_date,
                "last_name": last_name,
                "main_organization_id": main_organization_id,
                "main_role_id": main_role_id,
                "middle_name": middle_name,
                "name": name,
                "note": note,
                "organization_ids": organization_ids,
                "phone": phone,
                "responsible_for_organization_ids": responsible_for_organization_ids,
            },
            EmployeeResponse,
            timeout=timeout,
        )


class EmployeesCouriersLocationsResource(Resource):
    """Endpoints under `/api/1/employees/couriers/locations/by_time_offset`."""

    __slots__ = ()

    async def by_time_offset(
        self,
        *,
        organization_ids: Sequence[str],
        offset_in_seconds: int | None = None,
        timeout: float | None = None,
    ) -> CourierLocationsByTimeOffsetResponse:
        """Method of obtaining drivers' coordinates history.

        `POST /api/1/employees/couriers/locations/by_time_offset`

        Restriction group: `Drivers: location`.

        Args:
            organization_ids: List of organizations for drivers coordinates of which will be retrieved.
            offset_in_seconds: Interval in seconds from current server time. If driver coordinates were recorded in server storage within interval: ("current server time" - *OffsetInSeconds*, "current server time"], driver and their coordinates will be retrieved.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `CourierLocationsByTimeOffsetResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees/paths/~1api~11~1employees~1couriers~1locations~1by_time_offset/post)
        """
        return await self._client._call(
            "/api/1/employees/couriers/locations/by_time_offset",
            CourierLocationsByTimeOffsetRequest,
            {"organization_ids": organization_ids, "offset_in_seconds": offset_in_seconds},
            CourierLocationsByTimeOffsetResponse,
            timeout=timeout,
        )


class EmployeesCouriersActiveLocationResource(Resource):
    """Endpoints under `/api/1/employees/couriers/active_location`."""

    __slots__ = ()

    async def __call__(
        self,
        *,
        organization_ids: Sequence[str],
        timeout: float | None = None,
    ) -> ActiveCourierLocationsResponse:
        """Returns list of all active (courier session is opened) courier's locations which are delivery drivers
        in specified restaurants.

        `POST /api/1/employees/couriers/active_location`

        Restriction group: `Drivers: location`.

        Args:
            organization_ids: List of organizations.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `ActiveCourierLocationsResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees/paths/~1api~11~1employees~1couriers~1active_location/post)
        """
        return await self._client._call(
            "/api/1/employees/couriers/active_location",
            CouriersRequest,
            {"organization_ids": organization_ids},
            ActiveCourierLocationsResponse,
            timeout=timeout,
        )

    async def by_terminal(
        self,
        *,
        organization_id: str,
        terminal_group_id: str,
        timeout: float | None = None,
    ) -> ActiveCourierLocationsResponse:
        """Returns list of all active (courier session is opened) courier's locations which are delivery drivers in specified
        restaurant and are clocked in on specified delivery terminal.

        `POST /api/1/employees/couriers/active_location/by_terminal`

        Restriction group: `Drivers: location`.

        Args:
            organization_id: Organization ID. Can be obtained by `/api/1/organizations` operation.
            terminal_group_id: iikoFront terminals group ID. Can be obtained by `/api/1/terminal_groups` operation.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `ActiveCourierLocationsResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees/paths/~1api~11~1employees~1couriers~1active_location~1by_terminal/post)
        """
        return await self._client._call(
            "/api/1/employees/couriers/active_location/by_terminal",
            ActiveCourierLocationsByTerminalGroupRequest,
            {"organization_id": organization_id, "terminal_group_id": terminal_group_id},
            ActiveCourierLocationsResponse,
            timeout=timeout,
        )


class EmployeesCouriersResource(Resource):
    """Endpoints under `/api/1/employees/couriers`."""

    __slots__ = ()

    @property
    def active_location(self) -> EmployeesCouriersActiveLocationResource:
        """Endpoints under `/api/1/employees/couriers/active_location`."""
        return EmployeesCouriersActiveLocationResource(self._client)

    @property
    def locations(self) -> EmployeesCouriersLocationsResource:
        """Endpoints under `/api/1/employees/couriers/locations/by_time_offset`."""
        return EmployeesCouriersLocationsResource(self._client)

    async def __call__(
        self,
        *,
        organization_ids: Sequence[str],
        timeout: float | None = None,
    ) -> EmployeesResponse:
        """Returns list of all employees which are delivery drivers in specified restaurants.

        `POST /api/1/employees/couriers`

        Restriction group: `Drivers: dictionaries`.

        Args:
            organization_ids: List of organizations.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `EmployeesResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees/paths/~1api~11~1employees~1couriers/post)
        """
        return await self._client._call(
            "/api/1/employees/couriers",
            CouriersRequest,
            {"organization_ids": organization_ids},
            EmployeesResponse,
            timeout=timeout,
        )

    async def by_role(
        self,
        *,
        organization_ids: Sequence[str],
        roles_to_check: Sequence[str],
        timeout: float | None = None,
    ) -> EmployeesWithRoleSignResponse:
        """Returns list of all employees which are delivery drivers in specified restaurants,
        and checks whether each employee has passed role.

        `POST /api/1/employees/couriers/by_role`

        Restriction group: `Drivers: dictionaries`.

        Args:
            organization_ids: List of organizations. Can be obtained by `/api/1/organizations` operation.
            roles_to_check: Employee's roles for check. The short name of employee's position.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `EmployeesWithRoleSignResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees/paths/~1api~11~1employees~1couriers~1by_role/post)
        """
        return await self._client._call(
            "/api/1/employees/couriers/by_role",
            CouriersAndCheckRoleRequest,
            {"organization_ids": organization_ids, "roles_to_check": roles_to_check},
            EmployeesWithRoleSignResponse,
            timeout=timeout,
        )


class EmployeesAttendanceTypeResource(Resource):
    """Endpoints under `/api/employees/v1/attendance-type/list`."""

    __slots__ = ()

    async def list(
        self,
        *,
        is_deleted: bool | None = None,
        limit: int | None = None,
        offset: int | None = None,
        timeout: float | None = None,
    ) -> AttendanceTypeListResponse:
        """List attendance types.

        `POST /api/employees/v1/attendance-type/list`

        Returns the attendance type catalog

        Args:
            is_deleted: false — active, true — deleted, null — all
            limit: Maximum number of records in the response (1..1000)
            offset: Number of records to skip from the beginning
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `AttendanceTypeListResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees.Attendance/paths/~1api~1employees~1v1~1attendance-type~1list/post)
        """
        return await self._client._call(
            "/api/employees/v1/attendance-type/list",
            AttendanceTypeListRequest,
            {"is_deleted": is_deleted, "limit": limit, "offset": offset},
            AttendanceTypeListResponse,
            timeout=timeout,
        )


class EmployeesAttendanceResource(Resource):
    """Endpoints under `/api/employees/v1/attendance`."""

    __slots__ = ()

    async def create(
        self,
        *,
        employee_id: str,
        end_at: str,
        organization_id: str,
        role_id: str,
        start_at: str,
        attendance_type_id: str | None = None,
        comment: str | None = None,
        is_confirmed_manually: bool | None = None,
        personal_end_at: str | None = None,
        personal_start_at: str | None = None,
        timeout: float | None = None,
    ) -> AttendanceCreateResponse:
        """Create employee attendance.

        `POST /api/employees/v1/attendance/create`

        Creates a closed employee attendance and returns the creation result

        Args:
            employee_id: Employee UUID
            end_at: Date and time of the confirmed attendance end. If the value is `null`, the attendance is considered open. Existing attendances may be open.
            organization_id: Organization UUID
            role_id: Role UUID; may be absent for legacy attendances
            start_at: Date and time of the confirmed attendance start
            attendance_type_id: Attendance type UUID
            comment: Comment
            is_confirmed_manually: Manually confirmed flag; may be absent for legacy data.
            personal_end_at: Date and time of the registered attendance end from POS
            personal_start_at: Date and time of the registered attendance start from POS
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `AttendanceCreateResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees.Attendance/paths/~1api~1employees~1v1~1attendance~1create/post)
        """
        return await self._client._call(
            "/api/employees/v1/attendance/create",
            AttendanceCreateRequest,
            {
                "employee_id": employee_id,
                "end_at": end_at,
                "organization_id": organization_id,
                "role_id": role_id,
                "start_at": start_at,
                "attendance_type_id": attendance_type_id,
                "comment": comment,
                "is_confirmed_manually": is_confirmed_manually,
                "personal_end_at": personal_end_at,
                "personal_start_at": personal_start_at,
            },
            AttendanceCreateResponse,
            timeout=timeout,
        )

    async def delete(
        self,
        *,
        id: str,
        organization_id: str,
        timeout: float | None = None,
    ) -> AttendanceDeleteResponse:
        """Delete employee attendance.

        `POST /api/employees/v1/attendance/delete`

        Irreversibly deletes a single attendance

        Args:
            id: Attendance UUID
            organization_id: Organization UUID
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `AttendanceDeleteResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees.Attendance/paths/~1api~1employees~1v1~1attendance~1delete/post)
        """
        return await self._client._call(
            "/api/employees/v1/attendance/delete",
            AttendanceDeleteRequest,
            {"id": id, "organization_id": organization_id},
            AttendanceDeleteResponse,
            timeout=timeout,
        )

    async def list(
        self,
        *,
        end_at: str,
        organization_id: str,
        start_at: str,
        attendance_type_ids: Sequence[str] | None = None,
        employee_ids: Sequence[str] | None = None,
        is_closed: bool | None = None,
        limit: int | None = None,
        offset: int | None = None,
        should_include_payment_details: bool | None = None,
        timeout: float | None = None,
    ) -> AttendanceListResponse:
        """List employee attendances.

        `POST /api/employees/v1/attendance/list`

        Returns attendances within one organization for a period

        Args:
            end_at: Date and time of the confirmed attendance end. If the value is `null`, the attendance is considered open. Existing attendances may be open.
            organization_id: Organization UUID
            start_at: Date and time of the confirmed attendance start
            attendance_type_ids: Non-empty unique array of attendance type UUIDs to filter by
            employee_ids: Non-empty unique array of employee UUIDs to filter by
            is_closed: Attendance closed flag. If absent in the request body - both closed and open attendances will be returned. If the value is `true` - only closed attendances will be returned (`endAt != null`). If the value is `false` - only open attendances will be returned (`endAt = null`)
            limit: Maximum number of records in the response (1..1000)
            offset: Number of records to skip from the beginning
            should_include_payment_details: Flag to display payment details
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `AttendanceListResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees.Attendance/paths/~1api~1employees~1v1~1attendance~1list/post)
        """
        return await self._client._call(
            "/api/employees/v1/attendance/list",
            AttendanceListRequest,
            {
                "end_at": end_at,
                "organization_id": organization_id,
                "start_at": start_at,
                "attendance_type_ids": attendance_type_ids,
                "employee_ids": employee_ids,
                "is_closed": is_closed,
                "limit": limit,
                "offset": offset,
                "should_include_payment_details": should_include_payment_details,
            },
            AttendanceListResponse,
            timeout=timeout,
        )

    async def update(
        self,
        *,
        attendance_type_id: str,
        employee_id: str,
        end_at: str,
        id: str,
        is_confirmed_manually: bool,
        organization_id: str,
        role_id: str,
        start_at: str,
        comment: str | None = None,
        personal_end_at: str | None = None,
        personal_start_at: str | None = None,
        timeout: float | None = None,
    ) -> AttendanceUpdateResponse:
        """Update employee attendance.

        `POST /api/employees/v1/attendance/update`

        Updates an attendance; when the organization is changed, a new attendance with a new id is created

        Args:
            attendance_type_id: Attendance type UUID
            employee_id: Employee UUID
            end_at: Date and time of the confirmed attendance end. If the value is `null`, the attendance is considered open. Existing attendances may be open.
            id: Attendance UUID
            is_confirmed_manually: Manually confirmed flag; may be absent for legacy data
            organization_id: Organization UUID
            role_id: Role UUID; may be absent for legacy attendances
            start_at: Date and time of the confirmed attendance start
            comment: Comment
            personal_end_at: Date and time of the registered attendance end from POS. An already set value cannot be reset (set to `null`).
            personal_start_at: Date and time of the registered attendance start from POS. An already set value cannot be reset (set to `null`).
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `AttendanceUpdateResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees.Attendance/paths/~1api~1employees~1v1~1attendance~1update/post)
        """
        return await self._client._call(
            "/api/employees/v1/attendance/update",
            AttendanceUpdateRequest,
            {
                "attendance_type_id": attendance_type_id,
                "employee_id": employee_id,
                "end_at": end_at,
                "id": id,
                "is_confirmed_manually": is_confirmed_manually,
                "organization_id": organization_id,
                "role_id": role_id,
                "start_at": start_at,
                "comment": comment,
                "personal_end_at": personal_end_at,
                "personal_start_at": personal_start_at,
            },
            AttendanceUpdateResponse,
            timeout=timeout,
        )


class EmployeesResource(Resource):
    """Endpoints under `/api`."""

    __slots__ = ()

    @property
    def attendance(self) -> EmployeesAttendanceResource:
        """Endpoints under `/api/employees/v1/attendance`."""
        return EmployeesAttendanceResource(self._client)

    @property
    def attendance_type(self) -> EmployeesAttendanceTypeResource:
        """Endpoints under `/api/employees/v1/attendance-type/list`."""
        return EmployeesAttendanceTypeResource(self._client)

    @property
    def couriers(self) -> EmployeesCouriersResource:
        """Endpoints under `/api/1/employees/couriers`."""
        return EmployeesCouriersResource(self._client)

    @property
    def employee(self) -> EmployeesEmployeeResource:
        """Endpoints under `/api/employees/v1/employee`."""
        return EmployeesEmployeeResource(self._client)

    @property
    def positions(self) -> EmployeesPositionsResource:
        """Endpoints under `/api/employees/v1/positions`."""
        return EmployeesPositionsResource(self._client)

    @property
    def shift(self) -> EmployeesShiftResource:
        """Endpoints under `/api/1/employees/shift`."""
        return EmployeesShiftResource(self._client)

    @property
    def shifts(self) -> EmployeesShiftsResource:
        """Endpoints under `/api/1/employees/shifts/by_courier`."""
        return EmployeesShiftsResource(self._client)

    async def info(
        self,
        *,
        organization_id: str,
        id: str,
        timeout: float | None = None,
    ) -> EmployeeInfoResponse:
        """Returns employee info.

        `POST /api/1/employees/info`

        Restriction group: `Employees: dictionaries`.

        Args:
            organization_id: Organization ID. Can be obtained by `/api/1/organizations` operation.
            id: Employee ID.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `EmployeeInfoResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Employees/paths/~1api~11~1employees~1info/post)
        """
        return await self._client._call(
            "/api/1/employees/info",
            EmployeeInfoRequest,
            {"organization_id": organization_id, "id": id},
            EmployeeInfoResponse,
            timeout=timeout,
        )


__all__ = [
    "EmployeesAttendanceResource",
    "EmployeesAttendanceTypeResource",
    "EmployeesCouriersActiveLocationResource",
    "EmployeesCouriersLocationsResource",
    "EmployeesCouriersResource",
    "EmployeesEmployeeResource",
    "EmployeesPositionsResource",
    "EmployeesResource",
    "EmployeesShiftResource",
    "EmployeesShiftsResource",
]
