"""Endpoints under `/api/finance/v1`.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

import builtins
from collections.abc import Mapping, Sequence
from decimal import Decimal
from typing import Any

from iikocloudapi._resource import Resource
from iikocloudapi.models.common import FilterCondition, GetByIDRequest, ListRequest
from iikocloudapi.models.finance import (
    AccountCreateRequest,
    AccountDeleteRequest,
    AccountDeleteResponse,
    AccountFilter,
    AccountGetRequest,
    AccountListRequest,
    AccountListResponse,
    AccountPostingListRequest,
    AccountPostingListResponse,
    AccountResponse,
    AccountRestoreRequest,
    AccountRestoreResponse,
    AccountTransactionsListRequest,
    AccountTransactionsResponse,
    AccountType,
    AccountTypeListRequest,
    AccountUpdateRequest,
    BalanceSheetListRequest,
    BalanceSheetListResponse,
    CashFlowCategoryCascadeResponse,
    CashFlowCategoryCreateRequest,
    CashFlowCategoryDeleteRequest,
    CashFlowCategoryFilter,
    CashFlowCategoryGetRequest,
    CashFlowCategoryListRequest,
    CashFlowCategoryListResponse,
    CashFlowCategoryResponse,
    CashFlowCategoryRestoreRequest,
    CashFlowCategoryUpdateRequest,
    ChartOfAccountsListRequest,
    ChartOfAccountsListResponse,
    DocumentTransactionItem,
    DocumentTransactionsListRequest,
    IncomingServiceCreateItem,
    IncomingServiceCreateRequest,
    IncomingServiceGetResponse,
    IncomingServiceListItem,
    IncomingServiceSaveResponse,
    IncomingServiceUpdateRequest,
    ItemCategoryListRequest,
    ItemCategoryListResponse,
    OutgoingServiceCreateItem,
    OutgoingServiceCreateRequest,
    OutgoingServiceGetResponse,
    OutgoingServiceListItem,
    OutgoingServiceSaveResponse,
    OutgoingServiceUpdateRequest,
    TaxCategoryListRequest,
    TaxCategoryListResponse,
)


class FinanceTaxCategoryResource(Resource):
    """Endpoints under `/api/finance/v1/tax-category/list`."""

    __slots__ = ()

    async def list(
        self,
        *,
        filters: Sequence[FilterCondition | Mapping[str, Any]] | None = None,
        limit: int | None = None,
        offset: int | None = None,
        timeout: float | None = None,
    ) -> TaxCategoryListResponse:
        """Get a list of tax categories.

        `POST /api/finance/v1/tax-category/list`

        Returns a list of tax categories

        Args:
            filters: Request filters. All filters are applied simultaneously (AND)
            limit: Maximum number of records in the response.
            offset: Number of records to skip from the beginning.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `TaxCategoryListResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.Directories/paths/~1api~1finance~1v1~1tax-category~1list/post)
        """
        return await self._client._call(
            "/api/finance/v1/tax-category/list",
            TaxCategoryListRequest,
            {"filters": filters, "limit": limit, "offset": offset},
            TaxCategoryListResponse,
            timeout=timeout,
        )


class FinanceOutgoingServiceResource(Resource):
    """Endpoints under `/api/finance/v1/outgoing_service`."""

    __slots__ = ()

    async def cancel(
        self,
        *,
        document_id: str,
        organization_id: str,
        timeout: float | None = None,
    ) -> OutgoingServiceSaveResponse:
        """Cancel outgoing service act draft.

        `POST /api/finance/v1/outgoing_service/cancel`

        Changes the outgoing service act status from NEW to CANCELED

        Args:
            document_id: Document identifier (GUID)
            organization_id: Organization identifier (GUID)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `OutgoingServiceSaveResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.OutgoingService/paths/~1api~1finance~1v1~1outgoing_service~1cancel/post)
        """
        return await self._client._call(
            "/api/finance/v1/outgoing_service/cancel",
            GetByIDRequest,
            {"document_id": document_id, "organization_id": organization_id},
            OutgoingServiceSaveResponse,
            timeout=timeout,
        )

    async def create(
        self,
        *,
        counteragent: str,
        date: str,
        items: Sequence[OutgoingServiceCreateItem | Mapping[str, Any]],
        organization_id: str,
        comment: str | None = None,
        conception: str | None = None,
        contract_date: str | None = None,
        contract_number: str | None = None,
        document_id: str | None = None,
        due_date: str | None = None,
        is_automatic: bool | None = None,
        is_editable: bool | None = None,
        number: str | None = None,
        revenue_account: str | None = None,
        timeout: float | None = None,
    ) -> OutgoingServiceSaveResponse:
        """Create outgoing service act.

        `POST /api/finance/v1/outgoing_service/create`

        Creates a new outgoing service act

        Args:
            counteragent: Counteragent identifier (GUID)
            date: Document date and time (ISO 8601 YYYY-MM-DDThh:mm:ss.sss±hh:mm)
            items: List of document items
            organization_id: Organization identifier (GUID)
            comment: Comment
            conception: Concept identifier (GUID)
            contract_date: Contract date (ISO 8601 YYYY-MM-DDThh:mm:ss±hh:mm)
            contract_number: Contract number
            document_id: See the API reference.
            due_date: Payment due date
            is_automatic: Automatic document creation flag
            is_editable: Editable flag. true — available for editing
            number: Document number
            revenue_account: Revenue account identifier (GUID)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `OutgoingServiceSaveResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.OutgoingService/paths/~1api~1finance~1v1~1outgoing_service~1create/post)
        """
        return await self._client._call(
            "/api/finance/v1/outgoing_service/create",
            OutgoingServiceCreateRequest,
            {
                "counteragent": counteragent,
                "date": date,
                "items": items,
                "organization_id": organization_id,
                "comment": comment,
                "conception": conception,
                "contract_date": contract_date,
                "contract_number": contract_number,
                "document_id": document_id,
                "due_date": due_date,
                "is_automatic": is_automatic,
                "is_editable": is_editable,
                "number": number,
                "revenue_account": revenue_account,
            },
            OutgoingServiceSaveResponse,
            timeout=timeout,
        )

    async def get(
        self,
        *,
        document_id: str,
        organization_id: str,
        timeout: float | None = None,
    ) -> OutgoingServiceGetResponse:
        """Get outgoing service act.

        `POST /api/finance/v1/outgoing_service/get`

        Gets an outgoing service act by identifier

        Args:
            document_id: Document identifier (GUID)
            organization_id: Organization identifier (GUID)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `OutgoingServiceGetResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.OutgoingService/paths/~1api~1finance~1v1~1outgoing_service~1get/post)
        """
        return await self._client._call(
            "/api/finance/v1/outgoing_service/get",
            GetByIDRequest,
            {"document_id": document_id, "organization_id": organization_id},
            OutgoingServiceGetResponse,
            timeout=timeout,
        )

    async def list(
        self,
        *,
        from_: str,
        organization_id: str,
        to: str,
        timeout: float | None = None,
    ) -> builtins.list[OutgoingServiceListItem]:
        """Export outgoing service acts.

        `POST /api/finance/v1/outgoing_service/list`

        Exports outgoing service acts for the specified period

        Args:
            from_: Period start date (YYYY-MM-DD format)
            organization_id: Organization identifier (GUID)
            to: Period end date (YYYY-MM-DD format)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `list[OutgoingServiceListItem]` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.OutgoingService/paths/~1api~1finance~1v1~1outgoing_service~1list/post)
        """
        return await self._client._call(
            "/api/finance/v1/outgoing_service/list",
            ListRequest,
            {"from_": from_, "organization_id": organization_id, "to": to},
            list[OutgoingServiceListItem],
            timeout=timeout,
        )

    async def post(
        self,
        *,
        document_id: str,
        organization_id: str,
        timeout: float | None = None,
    ) -> OutgoingServiceSaveResponse:
        """Post outgoing service act.

        `POST /api/finance/v1/outgoing_service/post`

        Changes the outgoing service act status from NEW to PROCESSED

        Args:
            document_id: Document identifier (GUID)
            organization_id: Organization identifier (GUID)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `OutgoingServiceSaveResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.OutgoingService/paths/~1api~1finance~1v1~1outgoing_service~1post/post)
        """
        return await self._client._call(
            "/api/finance/v1/outgoing_service/post",
            GetByIDRequest,
            {"document_id": document_id, "organization_id": organization_id},
            OutgoingServiceSaveResponse,
            timeout=timeout,
        )

    async def unpost(
        self,
        *,
        document_id: str,
        organization_id: str,
        timeout: float | None = None,
    ) -> OutgoingServiceSaveResponse:
        """Unpost outgoing service act.

        `POST /api/finance/v1/outgoing_service/unpost`

        Changes the outgoing service act status from PROCESSED to NEW

        Args:
            document_id: Document identifier (GUID)
            organization_id: Organization identifier (GUID)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `OutgoingServiceSaveResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.OutgoingService/paths/~1api~1finance~1v1~1outgoing_service~1unpost/post)
        """
        return await self._client._call(
            "/api/finance/v1/outgoing_service/unpost",
            GetByIDRequest,
            {"document_id": document_id, "organization_id": organization_id},
            OutgoingServiceSaveResponse,
            timeout=timeout,
        )

    async def update(
        self,
        *,
        counteragent: str,
        date: str,
        document_id: str,
        items: Sequence[OutgoingServiceCreateItem | Mapping[str, Any]],
        number: str,
        organization_id: str,
        comment: str | None = None,
        conception: str | None = None,
        contract_date: str | None = None,
        contract_number: str | None = None,
        due_date: str | None = None,
        is_automatic: bool | None = None,
        is_editable: bool | None = None,
        revenue_account: str | None = None,
        timeout: float | None = None,
    ) -> OutgoingServiceSaveResponse:
        """Edit outgoing service act.

        `POST /api/finance/v1/outgoing_service/update`

        Edits an existing outgoing service act

        Args:
            counteragent: Counteragent identifier (GUID)
            date: Document date and time (ISO 8601 YYYY-MM-DDThh:mm:ss.sss±hh:mm)
            document_id: Document identifier (GUID)
            items: List of document items
            number: Document number
            organization_id: Organization identifier (GUID)
            comment: Comment
            conception: Concept identifier (GUID)
            contract_date: Contract date (ISO 8601 YYYY-MM-DDThh:mm:ss±hh:mm)
            contract_number: Contract number
            due_date: Payment due date
            is_automatic: Automatic document creation flag
            is_editable: Editable flag. true — available for editing
            revenue_account: Revenue account identifier (GUID)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `OutgoingServiceSaveResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.OutgoingService/paths/~1api~1finance~1v1~1outgoing_service~1update/post)
        """
        return await self._client._call(
            "/api/finance/v1/outgoing_service/update",
            OutgoingServiceUpdateRequest,
            {
                "counteragent": counteragent,
                "date": date,
                "document_id": document_id,
                "items": items,
                "number": number,
                "organization_id": organization_id,
                "comment": comment,
                "conception": conception,
                "contract_date": contract_date,
                "contract_number": contract_number,
                "due_date": due_date,
                "is_automatic": is_automatic,
                "is_editable": is_editable,
                "revenue_account": revenue_account,
            },
            OutgoingServiceSaveResponse,
            timeout=timeout,
        )


class FinanceItemCategoryResource(Resource):
    """Endpoints under `/api/finance/v1/item-category/list`."""

    __slots__ = ()

    async def list(
        self,
        *,
        filters: Sequence[FilterCondition | Mapping[str, Any]] | None = None,
        limit: int | None = None,
        offset: int | None = None,
        timeout: float | None = None,
    ) -> ItemCategoryListResponse:
        """Get a list of fiscal categories.

        `POST /api/finance/v1/item-category/list`

        Returns a list of fiscal categories

        Args:
            filters: Request filters. All filters are applied simultaneously (AND)
            limit: Maximum number of records in the response.
            offset: Number of records to skip from the beginning.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `ItemCategoryListResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.Directories/paths/~1api~1finance~1v1~1item-category~1list/post)
        """
        return await self._client._call(
            "/api/finance/v1/item-category/list",
            ItemCategoryListRequest,
            {"filters": filters, "limit": limit, "offset": offset},
            ItemCategoryListResponse,
            timeout=timeout,
        )


class FinanceIncomingServiceResource(Resource):
    """Endpoints under `/api/finance/v1/incoming_service`."""

    __slots__ = ()

    async def cancel(
        self,
        *,
        document_id: str,
        organization_id: str,
        timeout: float | None = None,
    ) -> IncomingServiceSaveResponse:
        """Cancel incoming service act draft.

        `POST /api/finance/v1/incoming_service/cancel`

        Changes the incoming service act status from NEW to CANCELED

        Args:
            document_id: Document identifier (GUID)
            organization_id: Organization identifier (GUID)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `IncomingServiceSaveResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.IncomingService/paths/~1api~1finance~1v1~1incoming_service~1cancel/post)
        """
        return await self._client._call(
            "/api/finance/v1/incoming_service/cancel",
            GetByIDRequest,
            {"document_id": document_id, "organization_id": organization_id},
            IncomingServiceSaveResponse,
            timeout=timeout,
        )

    async def create(
        self,
        *,
        counteragent: str,
        date: str,
        items: Sequence[IncomingServiceCreateItem | Mapping[str, Any]],
        organization_id: str,
        comment: str | None = None,
        conception: str | None = None,
        contract_date: str | None = None,
        contract_number: str | None = None,
        document_id: str | None = None,
        due_date: str | None = None,
        employee_pass_to_account: str | None = None,
        incoming_date: str | None = None,
        incoming_document_number: str | None = None,
        invoice: str | None = None,
        is_automatic: bool | None = None,
        is_editable: bool | None = None,
        number: str | None = None,
        revenue_account: str | None = None,
        timeout: float | None = None,
    ) -> IncomingServiceSaveResponse:
        """Create incoming service act.

        `POST /api/finance/v1/incoming_service/create`

        Creates a new incoming service act

        Args:
            counteragent: Counteragent identifier (GUID)
            date: Document date and time (ISO 8601 YYYY-MM-DDThh:mm:ss.sss±hh:mm)
            items: List of document items
            organization_id: Organization identifier (GUID)
            comment: Comment
            conception: Concept identifier (GUID)
            contract_date: Contract date (ISO 8601 YYYY-MM-DDThh:mm:ss±hh:mm)
            contract_number: Contract number
            document_id: See the API reference.
            due_date: Payment due date
            employee_pass_to_account: Charge to employee
            incoming_date: Incoming document date (YYYY-MM-DD)
            incoming_document_number: Incoming external document number
            invoice: Invoice number
            is_automatic: Automatic document creation flag
            is_editable: Editable flag. true — available for editing
            number: Document number
            revenue_account: Revenue account identifier (GUID)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `IncomingServiceSaveResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.IncomingService/paths/~1api~1finance~1v1~1incoming_service~1create/post)
        """
        return await self._client._call(
            "/api/finance/v1/incoming_service/create",
            IncomingServiceCreateRequest,
            {
                "counteragent": counteragent,
                "date": date,
                "items": items,
                "organization_id": organization_id,
                "comment": comment,
                "conception": conception,
                "contract_date": contract_date,
                "contract_number": contract_number,
                "document_id": document_id,
                "due_date": due_date,
                "employee_pass_to_account": employee_pass_to_account,
                "incoming_date": incoming_date,
                "incoming_document_number": incoming_document_number,
                "invoice": invoice,
                "is_automatic": is_automatic,
                "is_editable": is_editable,
                "number": number,
                "revenue_account": revenue_account,
            },
            IncomingServiceSaveResponse,
            timeout=timeout,
        )

    async def get(
        self,
        *,
        document_id: str,
        organization_id: str,
        timeout: float | None = None,
    ) -> IncomingServiceGetResponse:
        """Get incoming service act.

        `POST /api/finance/v1/incoming_service/get`

        Gets an incoming service act by identifier

        Args:
            document_id: Document identifier (GUID)
            organization_id: Organization identifier (GUID)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `IncomingServiceGetResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.IncomingService/paths/~1api~1finance~1v1~1incoming_service~1get/post)
        """
        return await self._client._call(
            "/api/finance/v1/incoming_service/get",
            GetByIDRequest,
            {"document_id": document_id, "organization_id": organization_id},
            IncomingServiceGetResponse,
            timeout=timeout,
        )

    async def list(
        self,
        *,
        from_: str,
        organization_id: str,
        to: str,
        timeout: float | None = None,
    ) -> builtins.list[IncomingServiceListItem]:
        """Export incoming service acts.

        `POST /api/finance/v1/incoming_service/list`

        Exports incoming service acts for the specified period

        Args:
            from_: Period start date (YYYY-MM-DD format)
            organization_id: Organization identifier (GUID)
            to: Period end date (YYYY-MM-DD format)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `list[IncomingServiceListItem]` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.IncomingService/paths/~1api~1finance~1v1~1incoming_service~1list/post)
        """
        return await self._client._call(
            "/api/finance/v1/incoming_service/list",
            ListRequest,
            {"from_": from_, "organization_id": organization_id, "to": to},
            list[IncomingServiceListItem],
            timeout=timeout,
        )

    async def post(
        self,
        *,
        document_id: str,
        organization_id: str,
        timeout: float | None = None,
    ) -> IncomingServiceSaveResponse:
        """Post incoming service act.

        `POST /api/finance/v1/incoming_service/post`

        Changes the incoming service act status from NEW to PROCESSED

        Args:
            document_id: Document identifier (GUID)
            organization_id: Organization identifier (GUID)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `IncomingServiceSaveResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.IncomingService/paths/~1api~1finance~1v1~1incoming_service~1post/post)
        """
        return await self._client._call(
            "/api/finance/v1/incoming_service/post",
            GetByIDRequest,
            {"document_id": document_id, "organization_id": organization_id},
            IncomingServiceSaveResponse,
            timeout=timeout,
        )

    async def unpost(
        self,
        *,
        document_id: str,
        organization_id: str,
        timeout: float | None = None,
    ) -> IncomingServiceSaveResponse:
        """Unpost incoming service act.

        `POST /api/finance/v1/incoming_service/unpost`

        Changes the incoming service act status from PROCESSED to NEW

        Args:
            document_id: Document identifier (GUID)
            organization_id: Organization identifier (GUID)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `IncomingServiceSaveResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.IncomingService/paths/~1api~1finance~1v1~1incoming_service~1unpost/post)
        """
        return await self._client._call(
            "/api/finance/v1/incoming_service/unpost",
            GetByIDRequest,
            {"document_id": document_id, "organization_id": organization_id},
            IncomingServiceSaveResponse,
            timeout=timeout,
        )

    async def update(
        self,
        *,
        counteragent: str,
        date: str,
        document_id: str,
        items: Sequence[IncomingServiceCreateItem | Mapping[str, Any]],
        number: str,
        organization_id: str,
        comment: str | None = None,
        conception: str | None = None,
        contract_date: str | None = None,
        contract_number: str | None = None,
        due_date: str | None = None,
        employee_pass_to_account: str | None = None,
        incoming_date: str | None = None,
        incoming_document_number: str | None = None,
        invoice: str | None = None,
        is_automatic: bool | None = None,
        is_editable: bool | None = None,
        revenue_account: str | None = None,
        timeout: float | None = None,
    ) -> IncomingServiceSaveResponse:
        """Edit incoming service act.

        `POST /api/finance/v1/incoming_service/update`

        Edits an existing incoming service act

        Args:
            counteragent: Counteragent identifier (GUID)
            date: Document date and time (ISO 8601 YYYY-MM-DDThh:mm:ss.sss±hh:mm)
            document_id: Document identifier (GUID)
            items: List of document items
            number: Document number
            organization_id: Organization identifier (GUID)
            comment: Comment
            conception: Concept identifier (GUID)
            contract_date: Contract date (ISO 8601 YYYY-MM-DDThh:mm:ss±hh:mm)
            contract_number: Contract number
            due_date: Payment due date
            employee_pass_to_account: Charge to employee
            incoming_date: Incoming document date (YYYY-MM-DD)
            incoming_document_number: Incoming external document number
            invoice: Invoice number
            is_automatic: Automatic document creation flag
            is_editable: Editable flag. true — available for editing
            revenue_account: Revenue account identifier (GUID)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `IncomingServiceSaveResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.IncomingService/paths/~1api~1finance~1v1~1incoming_service~1update/post)
        """
        return await self._client._call(
            "/api/finance/v1/incoming_service/update",
            IncomingServiceUpdateRequest,
            {
                "counteragent": counteragent,
                "date": date,
                "document_id": document_id,
                "items": items,
                "number": number,
                "organization_id": organization_id,
                "comment": comment,
                "conception": conception,
                "contract_date": contract_date,
                "contract_number": contract_number,
                "due_date": due_date,
                "employee_pass_to_account": employee_pass_to_account,
                "incoming_date": incoming_date,
                "incoming_document_number": incoming_document_number,
                "invoice": invoice,
                "is_automatic": is_automatic,
                "is_editable": is_editable,
                "revenue_account": revenue_account,
            },
            IncomingServiceSaveResponse,
            timeout=timeout,
        )


class FinanceDocumentTransactionsResource(Resource):
    """Endpoints under `/api/finance/v1/document_transactions/list`."""

    __slots__ = ()

    async def list(
        self,
        *,
        document_id: str,
        organization_id: str,
        timeout: float | None = None,
    ) -> builtins.list[DocumentTransactionItem]:
        """Get document transactions.

        `POST /api/finance/v1/document_transactions/list`

        Returns a list of transactions for the specified document

        Args:
            document_id: Document identifier (GUID)
            organization_id: Organization identifier (GUID)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `list[DocumentTransactionItem]` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.DocumentTransactions/paths/~1api~1finance~1v1~1document_transactions~1list/post)
        """
        return await self._client._call(
            "/api/finance/v1/document_transactions/list",
            DocumentTransactionsListRequest,
            {"document_id": document_id, "organization_id": organization_id},
            list[DocumentTransactionItem],
            timeout=timeout,
        )


class FinanceChartOfAccountsResource(Resource):
    """Endpoints under `/api/finance/v1/chart-of-accounts/list`."""

    __slots__ = ()

    async def list(
        self,
        *,
        account_type: str | None = None,
        is_deleted: bool | None = None,
        timeout: float | None = None,
    ) -> ChartOfAccountsListResponse:
        """Chart of accounts.

        `POST /api/finance/v1/chart-of-accounts/list`

        Returns the chart of financial accounts

        Args:
            account_type: Account type (ENUM)
            is_deleted: Deletion flag
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `ChartOfAccountsListResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.ChartOfAccounts/paths/~1api~1finance~1v1~1chart-of-accounts~1list/post)
        """
        return await self._client._call(
            "/api/finance/v1/chart-of-accounts/list",
            ChartOfAccountsListRequest,
            {"account_type": account_type, "is_deleted": is_deleted},
            ChartOfAccountsListResponse,
            timeout=timeout,
        )


class FinanceCashFlowCategoryResource(Resource):
    """Endpoints under `/api/finance/v1/cash-flow-category`."""

    __slots__ = ()

    async def create(
        self,
        *,
        code: str,
        name: str,
        type: str,
        parent_id: str | None = None,
        timeout: float | None = None,
    ) -> CashFlowCategoryResponse:
        """Create cash flow category.

        `POST /api/finance/v1/cash-flow-category/create`

        Creates a cash flow category

        Args:
            code: Cash flow category code
            name: Display name
            type: Cash flow category type. Allowed values: `FINANCE`, `INVESTMENT`, `OPERATIONAL`
            parent_id: Parent cash flow category UUID
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `CashFlowCategoryResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.CashFlowCategory/paths/~1api~1finance~1v1~1cash-flow-category~1create/post)
        """
        return await self._client._call(
            "/api/finance/v1/cash-flow-category/create",
            CashFlowCategoryCreateRequest,
            {"code": code, "name": name, "type": type, "parent_id": parent_id},
            CashFlowCategoryResponse,
            timeout=timeout,
        )

    async def delete(
        self,
        *,
        id: str,
        timeout: float | None = None,
    ) -> CashFlowCategoryCascadeResponse:
        """Delete cash flow category.

        `POST /api/finance/v1/cash-flow-category/delete`

        Marks a cash flow category and its active descendants as deleted

        Args:
            id: Cash flow category UUID. string (UUID)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `CashFlowCategoryCascadeResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.CashFlowCategory/paths/~1api~1finance~1v1~1cash-flow-category~1delete/post)
        """
        return await self._client._call(
            "/api/finance/v1/cash-flow-category/delete",
            CashFlowCategoryDeleteRequest,
            {"id": id},
            CashFlowCategoryCascadeResponse,
            timeout=timeout,
        )

    async def get(
        self,
        *,
        id: str,
        timeout: float | None = None,
    ) -> CashFlowCategoryResponse:
        """Get cash flow category.

        `POST /api/finance/v1/cash-flow-category/get`

        Returns a cash flow category by id

        Args:
            id: Cash flow category UUID. string (UUID)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `CashFlowCategoryResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.CashFlowCategory/paths/~1api~1finance~1v1~1cash-flow-category~1get/post)
        """
        return await self._client._call(
            "/api/finance/v1/cash-flow-category/get",
            CashFlowCategoryGetRequest,
            {"id": id},
            CashFlowCategoryResponse,
            timeout=timeout,
        )

    async def list(
        self,
        *,
        filters: Sequence[CashFlowCategoryFilter | Mapping[str, Any]],
        limit: int,
        offset: int,
        timeout: float | None = None,
    ) -> CashFlowCategoryListResponse:
        """List of cash flow categories.

        `POST /api/finance/v1/cash-flow-category/list`

        Returns a list of cash flow categories

        Args:
            filters: Request filters. All filters are applied simultaneously (AND)
            limit: Maximum number of records in the response.
            offset: Number of records to skip from the beginning.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `CashFlowCategoryListResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.CashFlowCategory/paths/~1api~1finance~1v1~1cash-flow-category~1list/post)
        """
        return await self._client._call(
            "/api/finance/v1/cash-flow-category/list",
            CashFlowCategoryListRequest,
            {"filters": filters, "limit": limit, "offset": offset},
            CashFlowCategoryListResponse,
            timeout=timeout,
        )

    async def restore(
        self,
        *,
        id: str,
        restore_descendants: bool,
        timeout: float | None = None,
    ) -> CashFlowCategoryCascadeResponse:
        """Restore cash flow category.

        `POST /api/finance/v1/cash-flow-category/restore`

        Restores a cash flow category

        Args:
            id: Cash flow category UUID. string (UUID)
            restore_descendants: Flag to restore child accounts
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `CashFlowCategoryCascadeResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.CashFlowCategory/paths/~1api~1finance~1v1~1cash-flow-category~1restore/post)
        """
        return await self._client._call(
            "/api/finance/v1/cash-flow-category/restore",
            CashFlowCategoryRestoreRequest,
            {"id": id, "restore_descendants": restore_descendants},
            CashFlowCategoryCascadeResponse,
            timeout=timeout,
        )

    async def update(
        self,
        *,
        code: str,
        id: str,
        name: str,
        type: str,
        parent_id: str | None = None,
        timeout: float | None = None,
    ) -> CashFlowCategoryResponse:
        """Update cash flow category.

        `POST /api/finance/v1/cash-flow-category/update`

        Updates a cash flow category

        Args:
            code: Cash flow category code
            id: Cash flow category UUID. string (UUID)
            name: Display name
            type: Cash flow category type. Allowed values: `FINANCE`, `INVESTMENT`, `OPERATIONAL`
            parent_id: Parent cash flow category UUID
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `CashFlowCategoryResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.CashFlowCategory/paths/~1api~1finance~1v1~1cash-flow-category~1update/post)
        """
        return await self._client._call(
            "/api/finance/v1/cash-flow-category/update",
            CashFlowCategoryUpdateRequest,
            {"code": code, "id": id, "name": name, "type": type, "parent_id": parent_id},
            CashFlowCategoryResponse,
            timeout=timeout,
        )


class FinanceBalanceSheetResource(Resource):
    """Endpoints under `/api/finance/v1/balance-sheet/list`."""

    __slots__ = ()

    async def list(
        self,
        *,
        balance_at: str | None = None,
        organization_ids: Sequence[str] | None = None,
        timeout: float | None = None,
    ) -> BalanceSheetListResponse:
        """Balance sheet.

        `POST /api/finance/v1/balance-sheet/list`

        Returns account balances as of a given date

        Args:
            balance_at: Date to retrieve balances for (YYYY-MM-DD)
            organization_ids: List of organization UUIDs to filter by. string[] (UUID)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `BalanceSheetListResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.BalanceSheet/paths/~1api~1finance~1v1~1balance-sheet~1list/post)
        """
        return await self._client._call(
            "/api/finance/v1/balance-sheet/list",
            BalanceSheetListRequest,
            {"balance_at": balance_at, "organization_ids": organization_ids},
            BalanceSheetListResponse,
            timeout=timeout,
        )


class FinanceAccountTypeResource(Resource):
    """Endpoints under `/api/finance/v1/account-type/list`."""

    __slots__ = ()

    async def list(
        self,
        *,
        timeout: float | None = None,
    ) -> builtins.list[AccountType]:
        """List of account types.

        `POST /api/finance/v1/account-type/list`

        Returns the list of valid account types

        Args:
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `list[AccountType]` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.AccountType/paths/~1api~1finance~1v1~1account-type~1list/post)
        """
        return await self._client._call(
            "/api/finance/v1/account-type/list",
            AccountTypeListRequest,
            {},
            list[AccountType],
            timeout=timeout,
        )


class FinanceAccountTransactionsResource(Resource):
    """Endpoints under `/api/finance/v1/account_transactions/list`."""

    __slots__ = ()

    async def list(
        self,
        *,
        account_id: str,
        from_: str,
        organization_id: str,
        to: str,
        timeout: float | None = None,
    ) -> AccountTransactionsResponse:
        """Get account transactions.

        `POST /api/finance/v1/account_transactions/list`

        Returns a list of transactions for the specified account

        Args:
            account_id: Account ID. string (UUID). Required
            from_: Period start date (YYYY-MM-DD format)
            organization_id: Organization identifier (GUID)
            to: Period end date (YYYY-MM-DD format)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `AccountTransactionsResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.AccountTransactions/paths/~1api~1finance~1v1~1account_transactions~1list/post)
        """
        return await self._client._call(
            "/api/finance/v1/account_transactions/list",
            AccountTransactionsListRequest,
            {"account_id": account_id, "from_": from_, "organization_id": organization_id, "to": to},
            AccountTransactionsResponse,
            timeout=timeout,
        )


class FinanceAccountPostingResource(Resource):
    """Endpoints under `/api/finance/v1/account-posting/list`."""

    __slots__ = ()

    async def list(
        self,
        *,
        account_id: str | None = None,
        counteragent_id: str | None = None,
        from_: str | None = None,
        organization_ids: Sequence[str] | None = None,
        to: str | None = None,
        timeout: float | None = None,
    ) -> AccountPostingListResponse:
        """Account postings.

        `POST /api/finance/v1/account-posting/list`

        Returns a list of postings for a financial account over a period

        Args:
            account_id: Financial account UUID. string (UUID)
            counteragent_id: Filter by counteragent UUID. string (UUID), nullable
            from_: Period start date (YYYY-MM-DD)
            organization_ids: List of organization UUIDs to filter by. string[] (UUID)
            to: Period end date (YYYY-MM-DD)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `AccountPostingListResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.AccountPosting/paths/~1api~1finance~1v1~1account-posting~1list/post)
        """
        return await self._client._call(
            "/api/finance/v1/account-posting/list",
            AccountPostingListRequest,
            {
                "account_id": account_id,
                "counteragent_id": counteragent_id,
                "from_": from_,
                "organization_ids": organization_ids,
                "to": to,
            },
            AccountPostingListResponse,
            timeout=timeout,
        )


class FinanceAccountResource(Resource):
    """Endpoints under `/api/finance/v1/account`."""

    __slots__ = ()

    async def create(
        self,
        *,
        description: str,
        name: str,
        start_balance_date: str,
        start_balance_sum: Decimal | float,
        type: str,
        code: str | None = None,
        is_custom_transactions_allowed: bool | None = None,
        parent_id: str | None = None,
        timeout: float | None = None,
    ) -> AccountResponse:
        """Create financial account.

        `POST /api/finance/v1/account/create`

        Creates a financial account

        Args:
            description: Account description
            name: Display name
            start_balance_date: Start balance date (YYYY-MM-DD format)
            start_balance_sum: Start balance amount
            type: Account type code
            code: Account code
            is_custom_transactions_allowed: Whether custom transactions are allowed for the account
            parent_id: Parent account UUID
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `AccountResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.Account/paths/~1api~1finance~1v1~1account~1create/post)
        """
        return await self._client._call(
            "/api/finance/v1/account/create",
            AccountCreateRequest,
            {
                "description": description,
                "name": name,
                "start_balance_date": start_balance_date,
                "start_balance_sum": start_balance_sum,
                "type": type,
                "code": code,
                "is_custom_transactions_allowed": is_custom_transactions_allowed,
                "parent_id": parent_id,
            },
            AccountResponse,
            timeout=timeout,
        )

    async def delete(
        self,
        *,
        id: str,
        timeout: float | None = None,
    ) -> AccountDeleteResponse:
        """Delete financial account.

        `POST /api/finance/v1/account/delete`

        Marks a financial account as deleted

        Args:
            id: Account UUID. string (UUID)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `AccountDeleteResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.Account/paths/~1api~1finance~1v1~1account~1delete/post)
        """
        return await self._client._call(
            "/api/finance/v1/account/delete",
            AccountDeleteRequest,
            {"id": id},
            AccountDeleteResponse,
            timeout=timeout,
        )

    async def get(
        self,
        *,
        id: str,
        timeout: float | None = None,
    ) -> AccountResponse:
        """Get financial account.

        `POST /api/finance/v1/account/get`

        Returns a financial account by id

        Args:
            id: Account UUID. string (UUID)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `AccountResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.Account/paths/~1api~1finance~1v1~1account~1get/post)
        """
        return await self._client._call(
            "/api/finance/v1/account/get",
            AccountGetRequest,
            {"id": id},
            AccountResponse,
            timeout=timeout,
        )

    async def list(
        self,
        *,
        filters: Sequence[AccountFilter | Mapping[str, Any]],
        limit: int,
        offset: int,
        timeout: float | None = None,
    ) -> AccountListResponse:
        """List of financial accounts.

        `POST /api/finance/v1/account/list`

        Returns a list of financial accounts

        Args:
            filters: Request filters. All filters are applied simultaneously (AND)
            limit: Maximum number of records in the response.
            offset: Number of records to skip from the beginning.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `AccountListResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.Account/paths/~1api~1finance~1v1~1account~1list/post)
        """
        return await self._client._call(
            "/api/finance/v1/account/list",
            AccountListRequest,
            {"filters": filters, "limit": limit, "offset": offset},
            AccountListResponse,
            timeout=timeout,
        )

    async def restore(
        self,
        *,
        id: str,
        restore_descendants: bool,
        timeout: float | None = None,
    ) -> AccountRestoreResponse:
        """Restore financial account.

        `POST /api/finance/v1/account/restore`

        Restores a deleted financial account

        Args:
            id: Account UUID. string (UUID)
            restore_descendants: Flag to restore child accounts
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `AccountRestoreResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.Account/paths/~1api~1finance~1v1~1account~1restore/post)
        """
        return await self._client._call(
            "/api/finance/v1/account/restore",
            AccountRestoreRequest,
            {"id": id, "restore_descendants": restore_descendants},
            AccountRestoreResponse,
            timeout=timeout,
        )

    async def update(
        self,
        *,
        description: str,
        id: str,
        name: str,
        start_balance_date: str,
        start_balance_sum: Decimal | float,
        type: str,
        code: str | None = None,
        parent_id: str | None = None,
        timeout: float | None = None,
    ) -> AccountResponse:
        """Update financial account.

        `POST /api/finance/v1/account/update`

        Updates a financial account

        Args:
            description: Account description
            id: Account UUID. string (UUID)
            name: Display name
            start_balance_date: Start balance date (YYYY-MM-DD format)
            start_balance_sum: Start balance amount
            type: Account type code
            code: Account code
            parent_id: Parent account UUID
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `AccountResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Finance.Account/paths/~1api~1finance~1v1~1account~1update/post)
        """
        return await self._client._call(
            "/api/finance/v1/account/update",
            AccountUpdateRequest,
            {
                "description": description,
                "id": id,
                "name": name,
                "start_balance_date": start_balance_date,
                "start_balance_sum": start_balance_sum,
                "type": type,
                "code": code,
                "parent_id": parent_id,
            },
            AccountResponse,
            timeout=timeout,
        )


class FinanceResource(Resource):
    """Endpoints under `/api/finance/v1`."""

    __slots__ = ()

    @property
    def account(self) -> FinanceAccountResource:
        """Endpoints under `/api/finance/v1/account`."""
        return FinanceAccountResource(self._client)

    @property
    def account_posting(self) -> FinanceAccountPostingResource:
        """Endpoints under `/api/finance/v1/account-posting/list`."""
        return FinanceAccountPostingResource(self._client)

    @property
    def account_transactions(self) -> FinanceAccountTransactionsResource:
        """Endpoints under `/api/finance/v1/account_transactions/list`."""
        return FinanceAccountTransactionsResource(self._client)

    @property
    def account_type(self) -> FinanceAccountTypeResource:
        """Endpoints under `/api/finance/v1/account-type/list`."""
        return FinanceAccountTypeResource(self._client)

    @property
    def balance_sheet(self) -> FinanceBalanceSheetResource:
        """Endpoints under `/api/finance/v1/balance-sheet/list`."""
        return FinanceBalanceSheetResource(self._client)

    @property
    def cash_flow_category(self) -> FinanceCashFlowCategoryResource:
        """Endpoints under `/api/finance/v1/cash-flow-category`."""
        return FinanceCashFlowCategoryResource(self._client)

    @property
    def chart_of_accounts(self) -> FinanceChartOfAccountsResource:
        """Endpoints under `/api/finance/v1/chart-of-accounts/list`."""
        return FinanceChartOfAccountsResource(self._client)

    @property
    def document_transactions(self) -> FinanceDocumentTransactionsResource:
        """Endpoints under `/api/finance/v1/document_transactions/list`."""
        return FinanceDocumentTransactionsResource(self._client)

    @property
    def incoming_service(self) -> FinanceIncomingServiceResource:
        """Endpoints under `/api/finance/v1/incoming_service`."""
        return FinanceIncomingServiceResource(self._client)

    @property
    def item_category(self) -> FinanceItemCategoryResource:
        """Endpoints under `/api/finance/v1/item-category/list`."""
        return FinanceItemCategoryResource(self._client)

    @property
    def outgoing_service(self) -> FinanceOutgoingServiceResource:
        """Endpoints under `/api/finance/v1/outgoing_service`."""
        return FinanceOutgoingServiceResource(self._client)

    @property
    def tax_category(self) -> FinanceTaxCategoryResource:
        """Endpoints under `/api/finance/v1/tax-category/list`."""
        return FinanceTaxCategoryResource(self._client)


__all__ = [
    "FinanceAccountPostingResource",
    "FinanceAccountResource",
    "FinanceAccountTransactionsResource",
    "FinanceAccountTypeResource",
    "FinanceBalanceSheetResource",
    "FinanceCashFlowCategoryResource",
    "FinanceChartOfAccountsResource",
    "FinanceDocumentTransactionsResource",
    "FinanceIncomingServiceResource",
    "FinanceItemCategoryResource",
    "FinanceOutgoingServiceResource",
    "FinanceResource",
    "FinanceTaxCategoryResource",
]
