"""Endpoints under `/api/licenses/v2/list`.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence

from iikocloudapi._resource import Resource
from iikocloudapi.models.licenses import GetLicenseListRequest, GetLicenseListResponse


class LicensesResource(Resource):
    """Endpoints under `/api/licenses/v2/list`."""

    __slots__ = ()

    async def list(
        self,
        *,
        organization_ids: Sequence[str] | None = None,
        timeout: float | None = None,
    ) -> GetLicenseListResponse:
        """Get license list information for the API login.

        `POST /api/licenses/v2/list`

        Restriction group: `Data: licenses`.

        Args:
            organization_ids: Organization IDs for which license list information will be returned. By default - all organizations from API login.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `GetLicenseListResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Licenses/paths/~1api~1licenses~1v2~1list/post)
        """
        return await self._client._call(
            "/api/licenses/v2/list",
            GetLicenseListRequest,
            {"organization_ids": organization_ids},
            GetLicenseListResponse,
            timeout=timeout,
        )


__all__ = [
    "LicensesResource",
]
