"""Endpoints under `/api/1/loyalty/iiko`.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

import datetime
from collections.abc import Mapping, Sequence
from decimal import Decimal
from typing import Any

from iikocloudapi._resource import Resource
from iikocloudapi.models.loyalty import (
    AddCustomerToProgramRequest,
    AddCustomerToProgramResponse,
    AddMagnetCardRequest,
    AddMagnetCardResponse,
    CalculateCheckinRequest,
    CalculateCheckinResponse,
    CancelHoldMoneyRequest,
    CancelHoldMoneyResponse,
    ChangeCategoryForCustomerRequest,
    ChangeCategoryForCustomerResponse,
    ChangeUserBalanceRequest,
    CheckSmsStatusRequest,
    CheckSmsStatusResponse,
    CounterMetric,
    CounterPeriod,
    CouponInfoRequest,
    CouponInfoResponse,
    CreateOrUpdateCustomerRequest,
    CreateOrUpdateCustomerResponse,
    DeleteCustomersRequest,
    DeleteCustomersResponse,
    DeleteMagnetCardRequest,
    DeleteMagnetCardResponse,
    GetByOrganizationIdRequest,
    GetCategoriesRequest,
    GetCategoriesResponse,
    GetCountersRequest,
    GetCountersResponse,
    GetCustomerInfoRequest,
    GetCustomerInfoResponse,
    GetManualConditionsResponse,
    GetProgramsRequest,
    GetProgramsResponse,
    GetTransactionsReportByPeriodRequest,
    GetTransactionsReportByPeriodResponse,
    GetTransactionsReportByRevisionRequest,
    GetTransactionsReportByRevisionResponse,
    HoldMoneyRequest,
    HoldMoneyResponse,
    IikoNetUserSex,
    LoyaltyDynamicDiscount,
    NotActivatedCouponRequest,
    NotActivatedCouponResponse,
    Order,
    PersonalDataConsentStatus,
    RefillUserBalanceResponse,
    RestoreCustomersRequest,
    RestoreCustomersResponse,
    SendEmailRequest,
    SendEmailResponse,
    SendSmsRequest,
    SendSmsResponse,
    SeriesWithNotActivatedCouponsRequest,
    SeriesWithNotActivatedCouponsResponse,
    SmsSendingPossibilityRequest,
    SmsSendingPossibilityResponse,
    WithdrawUserBalanceResponse,
)


class LoyaltyMessageResource(Resource):
    """Endpoints under `/api/1/loyalty/iiko/message`."""

    __slots__ = ()

    async def send_email(
        self,
        *,
        receiver: str,
        subject: str,
        body: str,
        organization_id: str,
        timeout: float | None = None,
    ) -> SendEmailResponse:
        """Send email.

        `POST /api/1/loyalty/iiko/message/send_email`

        Send email message to specified email address. Sending proceed according iikoCard organization's settings.

        Restriction group: `Loyalty: messages`.

        Args:
            receiver: Email address. Can be null.
            subject: Message subject. Can be null.
            body: Message body. Can be null.
            organization_id: Organization id.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `SendEmailResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Messages/paths/~1api~11~1loyalty~1iiko~1message~1send_email/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/message/send_email",
            SendEmailRequest,
            {"receiver": receiver, "subject": subject, "body": body, "organization_id": organization_id},
            SendEmailResponse,
            timeout=timeout,
        )

    async def send_sms(
        self,
        *,
        phone: str,
        text: str,
        organization_id: str,
        timeout: float | None = None,
    ) -> SendSmsResponse:
        """Send sms.

        `POST /api/1/loyalty/iiko/message/send_sms`

        Send sms message to specified phone number. Sending proceed according iikoCard organization's settings.

        Restriction group: `Loyalty: messages`.

        Args:
            phone: Customer's phone number. Can be null.
            text: Message text. Can be null.
            organization_id: Organization id.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `SendSmsResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Messages/paths/~1api~11~1loyalty~1iiko~1message~1send_sms/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/message/send_sms",
            SendSmsRequest,
            {"phone": phone, "text": text, "organization_id": organization_id},
            SendSmsResponse,
            timeout=timeout,
        )


class LoyaltyCustomerCategoryResource(Resource):
    """Endpoints under `/api/1/loyalty/iiko/customer_category`."""

    __slots__ = ()

    async def __call__(
        self,
        *,
        organization_id: str,
        timeout: float | None = None,
    ) -> GetCategoriesResponse:
        """Get customer categories.

        `POST /api/1/loyalty/iiko/customer_category`

        Get all organization's customer categories.

        Restriction group: `Loyalty: dictionaries`.

        Args:
            organization_id: Organization id.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `GetCategoriesResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Customer-categories/paths/~1api~11~1loyalty~1iiko~1customer_category/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/customer_category",
            GetCategoriesRequest,
            {"organization_id": organization_id},
            GetCategoriesResponse,
            timeout=timeout,
        )

    async def add(
        self,
        *,
        customer_id: str,
        category_id: str,
        organization_id: str,
        timeout: float | None = None,
    ) -> ChangeCategoryForCustomerResponse:
        """Add category for customer.

        `POST /api/1/loyalty/iiko/customer_category/add`

        Add specified category for customer.

        Restriction group: `Guests: changing`.

        Args:
            customer_id: Customer id.
            category_id: Guest category id.
            organization_id: Organization id.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `ChangeCategoryForCustomerResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Customer-categories/paths/~1api~11~1loyalty~1iiko~1customer_category~1add/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/customer_category/add",
            ChangeCategoryForCustomerRequest,
            {"customer_id": customer_id, "category_id": category_id, "organization_id": organization_id},
            ChangeCategoryForCustomerResponse,
            timeout=timeout,
        )

    async def remove(
        self,
        *,
        customer_id: str,
        category_id: str,
        organization_id: str,
        timeout: float | None = None,
    ) -> ChangeCategoryForCustomerResponse:
        """Remove category for customer.

        `POST /api/1/loyalty/iiko/customer_category/remove`

        Remove specified category for customer.

        Restriction group: `Guests: changing`.

        Args:
            customer_id: Customer id.
            category_id: Guest category id.
            organization_id: Organization id.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `ChangeCategoryForCustomerResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Customer-categories/paths/~1api~11~1loyalty~1iiko~1customer_category~1remove/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/customer_category/remove",
            ChangeCategoryForCustomerRequest,
            {"customer_id": customer_id, "category_id": category_id, "organization_id": organization_id},
            ChangeCategoryForCustomerResponse,
            timeout=timeout,
        )


class LoyaltyCustomerWalletResource(Resource):
    """Endpoints under `/api/1/loyalty/iiko/customer/wallet`."""

    __slots__ = ()

    async def cancel_hold(
        self,
        *,
        transaction_id: str,
        organization_id: str,
        timeout: float | None = None,
    ) -> CancelHoldMoneyResponse:
        """Cancel hold money.

        `POST /api/1/loyalty/iiko/customer/wallet/cancel_hold`

        Cancel holding transaction that created earlier.

        Restriction group: `Loyalty: wallets`.

        Args:
            transaction_id: Transaction id.
            organization_id: Organization id.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `CancelHoldMoneyResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Customers/paths/~1api~11~1loyalty~1iiko~1customer~1wallet~1cancel_hold/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/customer/wallet/cancel_hold",
            CancelHoldMoneyRequest,
            {"transaction_id": transaction_id, "organization_id": organization_id},
            CancelHoldMoneyResponse,
            timeout=timeout,
        )

    async def chargeoff(
        self,
        *,
        organization_id: str,
        customer_id: str | None = None,
        wallet_id: str | None = None,
        sum: Decimal | float | None = None,
        comment: str | None = None,
        timeout: float | None = None,
    ) -> WithdrawUserBalanceResponse:
        """Withdraw balance.

        `POST /api/1/loyalty/iiko/customer/wallet/chargeoff`

        Withdraw customer balance.

        Restriction group: `Loyalty: wallets`.

        Args:
            organization_id: Organization id.
            customer_id: Customer id.
            wallet_id: Wallet id.
            sum: Sum of balance change. Must be positive.
            comment: Comment. Can be null.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `WithdrawUserBalanceResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Customers/paths/~1api~11~1loyalty~1iiko~1customer~1wallet~1chargeoff/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/customer/wallet/chargeoff",
            ChangeUserBalanceRequest,
            {
                "organization_id": organization_id,
                "customer_id": customer_id,
                "wallet_id": wallet_id,
                "sum": sum,
                "comment": comment,
            },
            WithdrawUserBalanceResponse,
            timeout=timeout,
        )

    async def hold(
        self,
        *,
        customer_id: str,
        wallet_id: str,
        sum: Decimal | float,
        organization_id: str,
        transaction_id: str | None = None,
        comment: str | None = None,
        timeout: float | None = None,
    ) -> HoldMoneyResponse:
        """Hold money.

        `POST /api/1/loyalty/iiko/customer/wallet/hold`

        Hold customer's money in loyalty program. Payment will be process on POS during processing of an order.

        Restriction group: `Loyalty: wallets`.

        Args:
            customer_id: Customer id.
            wallet_id: Wallet id.
            sum: Sum.
            organization_id: Organization id.
            transaction_id: Predefined transaction id. Random if empty.
            comment: Additional information about holding. Can be null.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `HoldMoneyResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Customers/paths/~1api~11~1loyalty~1iiko~1customer~1wallet~1hold/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/customer/wallet/hold",
            HoldMoneyRequest,
            {
                "customer_id": customer_id,
                "wallet_id": wallet_id,
                "sum": sum,
                "organization_id": organization_id,
                "transaction_id": transaction_id,
                "comment": comment,
            },
            HoldMoneyResponse,
            timeout=timeout,
        )

    async def topup(
        self,
        *,
        organization_id: str,
        customer_id: str | None = None,
        wallet_id: str | None = None,
        sum: Decimal | float | None = None,
        comment: str | None = None,
        timeout: float | None = None,
    ) -> RefillUserBalanceResponse:
        """Refill balance.

        `POST /api/1/loyalty/iiko/customer/wallet/topup`

        Refill customer balance.

        Restriction group: `Loyalty: wallets`.

        Args:
            organization_id: Organization id.
            customer_id: Customer id.
            wallet_id: Wallet id.
            sum: Sum of balance change. Must be positive.
            comment: Comment. Can be null.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `RefillUserBalanceResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Customers/paths/~1api~11~1loyalty~1iiko~1customer~1wallet~1topup/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/customer/wallet/topup",
            ChangeUserBalanceRequest,
            {
                "organization_id": organization_id,
                "customer_id": customer_id,
                "wallet_id": wallet_id,
                "sum": sum,
                "comment": comment,
            },
            RefillUserBalanceResponse,
            timeout=timeout,
        )


class LoyaltyCustomerTransactionsResource(Resource):
    """Endpoints under `/api/1/loyalty/iiko/customer/transactions`."""

    __slots__ = ()

    async def by_date(
        self,
        *,
        customer_id: str,
        date_from: datetime.datetime | str,
        date_to: datetime.datetime | str,
        page_number: int,
        page_size: int,
        organization_id: str,
        timeout: float | None = None,
    ) -> GetTransactionsReportByPeriodResponse:
        """Get transaction report by period.

        `POST /api/1/loyalty/iiko/customer/transactions/by_date`

        Get transaction report for specified customer by provided date range.

        Restriction group: `Guests: info`.

        Args:
            customer_id: Customer id.
            date_from: Report since date in UTC. Included.
            date_to: Report till date in UTC. Included.
            page_number: Page number. Zero based. Previous pages will be skipped.
            page_size: Page size. Ignored if more than max page size on server.
            organization_id: Organization id.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `GetTransactionsReportByPeriodResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Report/paths/~1api~11~1loyalty~1iiko~1customer~1transactions~1by_date/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/customer/transactions/by_date",
            GetTransactionsReportByPeriodRequest,
            {
                "customer_id": customer_id,
                "date_from": date_from,
                "date_to": date_to,
                "page_number": page_number,
                "page_size": page_size,
                "organization_id": organization_id,
            },
            GetTransactionsReportByPeriodResponse,
            timeout=timeout,
        )

    async def by_revision(
        self,
        *,
        customer_id: str,
        page_size: int,
        organization_id: str,
        revision: int | None = None,
        last_transaction_id: str | None = None,
        timeout: float | None = None,
    ) -> GetTransactionsReportByRevisionResponse:
        """Get transaction report by revision.

        `POST /api/1/loyalty/iiko/customer/transactions/by_revision`

        Get transaction report for specified customer by provided revision.

        Restriction group: `Guests: info`.

        Args:
            customer_id: Customer id.
            page_size: Page size. Ignored if more than max size on server..
            organization_id: Organization id.
            revision: Report since revision. Included if LastTransactionId set..
            last_transaction_id: Report since transaction. Excluded. Can't be used without revision..
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `GetTransactionsReportByRevisionResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Report/paths/~1api~11~1loyalty~1iiko~1customer~1transactions~1by_revision/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/customer/transactions/by_revision",
            GetTransactionsReportByRevisionRequest,
            {
                "customer_id": customer_id,
                "page_size": page_size,
                "organization_id": organization_id,
                "revision": revision,
                "last_transaction_id": last_transaction_id,
            },
            GetTransactionsReportByRevisionResponse,
            timeout=timeout,
        )


class LoyaltyCustomerProgramResource(Resource):
    """Endpoints under `/api/1/loyalty/iiko/customer/program/add`."""

    __slots__ = ()

    async def add(
        self,
        *,
        organization_id: str,
        customer_id: str | None = None,
        program_id: str | None = None,
        timeout: float | None = None,
    ) -> AddCustomerToProgramResponse:
        """Add customer to program.

        `POST /api/1/loyalty/iiko/customer/program/add`

        Add new customer for program.

        Restriction group: `Guests: changing`.

        Args:
            organization_id: Organization id.
            customer_id: Customer id.
            program_id: Program id.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `AddCustomerToProgramResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Customers/paths/~1api~11~1loyalty~1iiko~1customer~1program~1add/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/customer/program/add",
            AddCustomerToProgramRequest,
            {"organization_id": organization_id, "customer_id": customer_id, "program_id": program_id},
            AddCustomerToProgramResponse,
            timeout=timeout,
        )


class LoyaltyCustomerCardResource(Resource):
    """Endpoints under `/api/1/loyalty/iiko/customer/card`."""

    __slots__ = ()

    async def add(
        self,
        *,
        customer_id: str,
        card_track: str,
        card_number: str,
        organization_id: str,
        timeout: float | None = None,
    ) -> AddMagnetCardResponse:
        """Add card.

        `POST /api/1/loyalty/iiko/customer/card/add`

        Add new card for customer.

        Restriction group: `Guests: changing`.

        Args:
            customer_id: Customer id.
            card_track: Card track. Can be null.
            card_number: Card number. Can be null.
            organization_id: Organization id.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `AddMagnetCardResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Customers/paths/~1api~11~1loyalty~1iiko~1customer~1card~1add/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/customer/card/add",
            AddMagnetCardRequest,
            {
                "customer_id": customer_id,
                "card_track": card_track,
                "card_number": card_number,
                "organization_id": organization_id,
            },
            AddMagnetCardResponse,
            timeout=timeout,
        )

    async def remove(
        self,
        *,
        customer_id: str,
        card_track: str,
        organization_id: str,
        timeout: float | None = None,
    ) -> DeleteMagnetCardResponse:
        """Delete card.

        `POST /api/1/loyalty/iiko/customer/card/remove`

        Delete existing card for customer.

        Restriction group: `Guests: changing`.

        Args:
            customer_id: Customer id.
            card_track: Card track. Can be null.
            organization_id: Organization id.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `DeleteMagnetCardResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Customers/paths/~1api~11~1loyalty~1iiko~1customer~1card~1remove/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/customer/card/remove",
            DeleteMagnetCardRequest,
            {"customer_id": customer_id, "card_track": card_track, "organization_id": organization_id},
            DeleteMagnetCardResponse,
            timeout=timeout,
        )


class LoyaltyCustomerResource(Resource):
    """Endpoints under `/api/1/loyalty/iiko/customer`."""

    __slots__ = ()

    @property
    def card(self) -> LoyaltyCustomerCardResource:
        """Endpoints under `/api/1/loyalty/iiko/customer/card`."""
        return LoyaltyCustomerCardResource(self._client)

    @property
    def program(self) -> LoyaltyCustomerProgramResource:
        """Endpoints under `/api/1/loyalty/iiko/customer/program/add`."""
        return LoyaltyCustomerProgramResource(self._client)

    @property
    def transactions(self) -> LoyaltyCustomerTransactionsResource:
        """Endpoints under `/api/1/loyalty/iiko/customer/transactions`."""
        return LoyaltyCustomerTransactionsResource(self._client)

    @property
    def wallet(self) -> LoyaltyCustomerWalletResource:
        """Endpoints under `/api/1/loyalty/iiko/customer/wallet`."""
        return LoyaltyCustomerWalletResource(self._client)

    async def create_or_update(
        self,
        *,
        organization_id: str,
        id: str | None = None,
        phone: str | None = None,
        card_track: str | None = None,
        card_number: str | None = None,
        name: str | None = None,
        middle_name: str | None = None,
        sur_name: str | None = None,
        birthday: datetime.datetime | str | None = None,
        email: str | None = None,
        sex: IikoNetUserSex | None = None,
        consent_status: PersonalDataConsentStatus | None = None,
        should_receive_loyalty_info: bool | None = None,
        should_receive_promo_actions_info: bool | None = None,
        referrer_id: str | None = None,
        user_data: str | None = None,
        is_deleted: bool | None = None,
        employee_id: str | None = None,
        comment: str | None = None,
        nullify_empty_fields: bool | None = None,
        timeout: float | None = None,
    ) -> CreateOrUpdateCustomerResponse:
        """Create or update customer.

        `POST /api/1/loyalty/iiko/customer/create_or_update`

        Create or update customer info by id or phone or card track.

        Restriction group: `Guests: creating`.

        Args:
            organization_id: Customer organization id.
            id: Customer id.
            phone: Customer phone. Can be null.
            card_track: Card track. Required if cardNumber set. Can be null.
            card_number: Card number. Required if cardTrack set. Can be null.
            name: Customer name. Can be null.
            middle_name: Customer middle name. Can be null.
            sur_name: Customer surname. Can be null.
            birthday: Customer birthday.
            email: Customer email. Can be null.
            sex: Customer sex. 0 - not specified, 1 - male, 2 - female.
            consent_status: Customer consent status. 0 - unknown, 1 - given, 2 - revoked.
            should_receive_loyalty_info: Customer get loyalty messages (email, sms). If the parameter is not specified for new customers, the value 'true' is used.
            should_receive_promo_actions_info: Customer get promo messages (email, sms). If the parameter is not specified for new customers, the value 'true' is used.
            referrer_id: Id for referrer guest. Null for old integrations, Guid.Empty - for referrer deletion. Can be null.
            user_data: Customer user data. Can be null.
            is_deleted: Customer logical deletion flag.
            employee_id: Employee number or id. Can be null.
            comment: Customer description and additional data. Can be null.
            nullify_empty_fields: If set to true, then empty string values (not null) will overwrite origin guest fields with nulls, otherwise empty fields are ignored.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `CreateOrUpdateCustomerResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Customers/paths/~1api~11~1loyalty~1iiko~1customer~1create_or_update/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/customer/create_or_update",
            CreateOrUpdateCustomerRequest,
            {
                "organization_id": organization_id,
                "id": id,
                "phone": phone,
                "card_track": card_track,
                "card_number": card_number,
                "name": name,
                "middle_name": middle_name,
                "sur_name": sur_name,
                "birthday": birthday,
                "email": email,
                "sex": sex,
                "consent_status": consent_status,
                "should_receive_loyalty_info": should_receive_loyalty_info,
                "should_receive_promo_actions_info": should_receive_promo_actions_info,
                "referrer_id": referrer_id,
                "user_data": user_data,
                "is_deleted": is_deleted,
                "employee_id": employee_id,
                "comment": comment,
                "nullify_empty_fields": nullify_empty_fields,
            },
            CreateOrUpdateCustomerResponse,
            timeout=timeout,
        )

    async def info(
        self,
        *,
        body: GetCustomerInfoRequest | Mapping[str, Any],
        timeout: float | None = None,
    ) -> GetCustomerInfoResponse:
        """Get customer info.

        `POST /api/1/loyalty/iiko/customer/info`

        Get customer info by specified criterion.

        Restriction group: `Guests: info`.

        Args:
            body: Request body.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `GetCustomerInfoResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Customers/paths/~1api~11~1loyalty~1iiko~1customer~1info/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/customer/info",
            GetCustomerInfoRequest,
            body,
            GetCustomerInfoResponse,
            timeout=timeout,
        )


class LoyaltyCouponsResource(Resource):
    """Endpoints under `/api/1/loyalty/iiko/coupons`."""

    __slots__ = ()

    async def by_series(
        self,
        *,
        series: str,
        organization_id: str,
        page_size: int | None = None,
        page: int | None = None,
        timeout: float | None = None,
    ) -> NotActivatedCouponResponse:
        """Get non-activated coupons.

        `POST /api/1/loyalty/iiko/coupons/by_series`

        Get list of non-activated coupons.

        Restriction group: `Loyalty: coupons`.

        Args:
            series: Series. Can be null.
            organization_id: Organization id.
            page_size: Page size.
            page: Page.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `NotActivatedCouponResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Discounts-and-promotions/paths/~1api~11~1loyalty~1iiko~1coupons~1by_series/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/coupons/by_series",
            NotActivatedCouponRequest,
            {"series": series, "organization_id": organization_id, "page_size": page_size, "page": page},
            NotActivatedCouponResponse,
            timeout=timeout,
        )

    async def info(
        self,
        *,
        number: str,
        organization_id: str,
        series: str | None = None,
        timeout: float | None = None,
    ) -> CouponInfoResponse:
        """Get coupon info.

        `POST /api/1/loyalty/iiko/coupons/info`

        Get information about the specified coupon.

        Restriction group: `Loyalty: coupons`.

        Args:
            number: Number. Can be null.
            organization_id: Organization id.
            series: Series. Can be null.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `CouponInfoResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Discounts-and-promotions/paths/~1api~11~1loyalty~1iiko~1coupons~1info/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/coupons/info",
            CouponInfoRequest,
            {"number": number, "organization_id": organization_id, "series": series},
            CouponInfoResponse,
            timeout=timeout,
        )

    async def series(
        self,
        *,
        organization_id: str,
        timeout: float | None = None,
    ) -> SeriesWithNotActivatedCouponsResponse:
        """Get coupon series with non-activated coupons.

        `POST /api/1/loyalty/iiko/coupons/series`

        Get a list of coupon series in which there are not deleted and not activated coupons.

        Restriction group: `Loyalty: coupons`.

        Args:
            organization_id: Organization id.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `SeriesWithNotActivatedCouponsResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Discounts-and-promotions/paths/~1api~11~1loyalty~1iiko~1coupons~1series/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/coupons/series",
            SeriesWithNotActivatedCouponsRequest,
            {"organization_id": organization_id},
            SeriesWithNotActivatedCouponsResponse,
            timeout=timeout,
        )


class LoyaltyResource(Resource):
    """Endpoints under `/api/1/loyalty/iiko`."""

    __slots__ = ()

    @property
    def coupons(self) -> LoyaltyCouponsResource:
        """Endpoints under `/api/1/loyalty/iiko/coupons`."""
        return LoyaltyCouponsResource(self._client)

    @property
    def customer(self) -> LoyaltyCustomerResource:
        """Endpoints under `/api/1/loyalty/iiko/customer`."""
        return LoyaltyCustomerResource(self._client)

    @property
    def customer_category(self) -> LoyaltyCustomerCategoryResource:
        """Endpoints under `/api/1/loyalty/iiko/customer_category`."""
        return LoyaltyCustomerCategoryResource(self._client)

    @property
    def message(self) -> LoyaltyMessageResource:
        """Endpoints under `/api/1/loyalty/iiko/message`."""
        return LoyaltyMessageResource(self._client)

    async def calculate(
        self,
        *,
        order: Order | Mapping[str, Any],
        organization_id: str,
        coupon: str | None = None,
        referrer_id: str | None = None,
        terminal_group_id: str | None = None,
        available_payment_marketing_campaign_ids: Sequence[str] | None = None,
        applicable_manual_conditions: Sequence[str] | None = None,
        dynamic_discounts: Sequence[LoyaltyDynamicDiscount | Mapping[str, Any]] | None = None,
        is_loyalty_trace_enabled: bool | None = None,
        timeout: float | None = None,
    ) -> CalculateCheckinResponse:
        """Calculate checkin.

        `POST /api/1/loyalty/iiko/calculate`

        Calculate discounts and other loyalty items for an order.

        Restriction group: `Loyalty: order calculate`.

        Args:
            order: Order.
            organization_id: Organization id.
            coupon: Obsolete field. Use Order.LoyaltyInfo.Coupon instead. Can be null.
            referrer_id: Referrer id.
            terminal_group_id: Identifier of a target terminal. Should be used only when auto distribution is off and no call center operator is available.
            available_payment_marketing_campaign_ids: List of identifiers of applied campaigns. Should be empty if no payment method is used.
            applicable_manual_conditions: Obsolete field. Use request.Order.LoyaltyInfo.ApplicableManualConditions instead.
            dynamic_discounts: Obsolete field. Use Order.LoyaltyInfo.DynamicDiscounts instead. Can be null..
            is_loyalty_trace_enabled: Loyalty trace is enabled.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `CalculateCheckinResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Discounts-and-promotions/paths/~1api~11~1loyalty~1iiko~1calculate/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/calculate",
            CalculateCheckinRequest,
            {
                "order": order,
                "organization_id": organization_id,
                "coupon": coupon,
                "referrer_id": referrer_id,
                "terminal_group_id": terminal_group_id,
                "available_payment_marketing_campaign_ids": available_payment_marketing_campaign_ids,
                "applicable_manual_conditions": applicable_manual_conditions,
                "dynamic_discounts": dynamic_discounts,
                "is_loyalty_trace_enabled": is_loyalty_trace_enabled,
            },
            CalculateCheckinResponse,
            timeout=timeout,
        )

    async def check_sms_sending_possibility(
        self,
        *,
        organization_id: str,
        timeout: float | None = None,
    ) -> SmsSendingPossibilityResponse:
        """Check sms sending possibility.

        `POST /api/1/loyalty/iiko/check_sms_sending_possibility`

        Check sms sending possibility before send sms message.

        Args:
            organization_id: Organization id.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `SmsSendingPossibilityResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Messages/paths/~1api~11~1loyalty~1iiko~1check_sms_sending_possibility/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/check_sms_sending_possibility",
            SmsSendingPossibilityRequest,
            {"organization_id": organization_id},
            SmsSendingPossibilityResponse,
            timeout=timeout,
        )

    async def check_sms_status(
        self,
        *,
        sms_ids: Sequence[str],
        organization_id: str,
        timeout: float | None = None,
    ) -> CheckSmsStatusResponse:
        """Check SMS status.

        `POST /api/1/loyalty/iiko/check_sms_status`

        Check the status of sending SMS messages.

        Args:
            sms_ids: Sms IDs for checking.
            organization_id: Organization id.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `CheckSmsStatusResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Messages/paths/~1api~11~1loyalty~1iiko~1check_sms_status/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/check_sms_status",
            CheckSmsStatusRequest,
            {"sms_ids": sms_ids, "organization_id": organization_id},
            CheckSmsStatusResponse,
            timeout=timeout,
        )

    async def delete_customers(
        self,
        *,
        customer_ids: Sequence[str],
        organization_id: str,
        timeout: float | None = None,
    ) -> DeleteCustomersResponse:
        """Logical deletion of customers.

        `POST /api/1/loyalty/iiko/delete_customers`

        Mark customers as deleted.

        Args:
            customer_ids: Customer IDs for logical deletion.
            organization_id: Organization id.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `DeleteCustomersResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Customers/paths/~1api~11~1loyalty~1iiko~1delete_customers/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/delete_customers",
            DeleteCustomersRequest,
            {"customer_ids": customer_ids, "organization_id": organization_id},
            DeleteCustomersResponse,
            timeout=timeout,
        )

    async def get_counters(
        self,
        *,
        organization_id: str,
        guest_ids: Sequence[str] | None = None,
        periods: Sequence[CounterPeriod] | None = None,
        metrics: Sequence[CounterMetric] | None = None,
        timeout: float | None = None,
    ) -> GetCountersResponse:
        """Get counters.

        `POST /api/1/loyalty/iiko/get_counters`

        Get customer orders count and sum for different period.

        Args:
            organization_id: Organization id.
            guest_ids: Guest ids.
            periods: Periods.
            metrics: Metrics.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `GetCountersResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Customers/paths/~1api~11~1loyalty~1iiko~1get_counters/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/get_counters",
            GetCountersRequest,
            {"organization_id": organization_id, "guest_ids": guest_ids, "periods": periods, "metrics": metrics},
            GetCountersResponse,
            timeout=timeout,
        )

    async def manual_condition(
        self,
        *,
        organization_id: str | None = None,
        timeout: float | None = None,
    ) -> GetManualConditionsResponse:
        """Get manual conditions.

        `POST /api/1/loyalty/iiko/manual_condition`

        Get all organization's manual conditions.

        Restriction group: `Loyalty: dictionaries`.

        Args:
            organization_id: Organization id.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `GetManualConditionsResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Discounts-and-promotions/paths/~1api~11~1loyalty~1iiko~1manual_condition/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/manual_condition",
            GetByOrganizationIdRequest,
            {"organization_id": organization_id},
            GetManualConditionsResponse,
            timeout=timeout,
        )

    async def program(
        self,
        *,
        organization_id: str,
        without_marketing_campaigns: bool | None = None,
        timeout: float | None = None,
    ) -> GetProgramsResponse:
        """Get programs.

        `POST /api/1/loyalty/iiko/program`

        Get all loyalty programs for organization.

        Restriction group: `Loyalty: dictionaries`.

        Args:
            organization_id: Organization id.
            without_marketing_campaigns: Determines if marketing campaigns not required.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `GetProgramsResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Discounts-and-promotions/paths/~1api~11~1loyalty~1iiko~1program/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/program",
            GetProgramsRequest,
            {"organization_id": organization_id, "without_marketing_campaigns": without_marketing_campaigns},
            GetProgramsResponse,
            timeout=timeout,
        )

    async def restore_customers(
        self,
        *,
        customer_ids: Sequence[str],
        organization_id: str,
        timeout: float | None = None,
    ) -> RestoreCustomersResponse:
        """Logical recovery of customers.

        `POST /api/1/loyalty/iiko/restore_customers`

        Removing deletion flags for customers.

        Args:
            customer_ids: Customer IDs to recover.
            organization_id: Organization id.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `RestoreCustomersResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Customers/paths/~1api~11~1loyalty~1iiko~1restore_customers/post)
        """
        return await self._client._call(
            "/api/1/loyalty/iiko/restore_customers",
            RestoreCustomersRequest,
            {"customer_ids": customer_ids, "organization_id": organization_id},
            RestoreCustomersResponse,
            timeout=timeout,
        )


__all__ = [
    "LoyaltyCouponsResource",
    "LoyaltyCustomerCardResource",
    "LoyaltyCustomerCategoryResource",
    "LoyaltyCustomerProgramResource",
    "LoyaltyCustomerResource",
    "LoyaltyCustomerTransactionsResource",
    "LoyaltyCustomerWalletResource",
    "LoyaltyMessageResource",
    "LoyaltyResource",
]
