"""Endpoints under `/api`.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

from iikocloudapi._resource import Resource
from iikocloudapi.models.general import MenuRequestV3, MenusDataResponse, MenuV3


class MenuResource(Resource):
    """Endpoints under `/api`."""

    __slots__ = ()

    async def __call__(
        self,
        *,
        timeout: float | None = None,
    ) -> MenusDataResponse:
        """External menus with price categories.

        `POST /api/2/menu`

        Restriction group: `Data: menu`.

        Args:
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `MenusDataResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Menu/paths/~1api~12~1menu/post)
        """
        return await self._client._call(
            "/api/2/menu",
            None,
            None,
            MenusDataResponse,
            timeout=timeout,
        )

    async def by_id(
        self,
        *,
        external_menu_id: str,
        organization_id: str,
        price_category_id: str | None = None,
        timeout: float | None = None,
    ) -> MenuV3:
        """Retrieve external menu V3 by ID.

        `POST /api/menu/v3/by_id`

        Generated from Plain menu converter.

        Restriction group: `Data: menu`.

        Args:
            external_menu_id: External menu id Can be obtained by `api/2/menu` operation.
            organization_id: Organization ID. Can be obtained by `/api/1/organizations` operation.
            price_category_id: Price category id. Can be obtained by `api/2/menu` operation.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `MenuV3` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Menu/paths/~1api~1menu~1v3~1by_id/post)
        """
        return await self._client._call(
            "/api/menu/v3/by_id",
            MenuRequestV3,
            {
                "external_menu_id": external_menu_id,
                "organization_id": organization_id,
                "price_category_id": price_category_id,
            },
            MenuV3,
            timeout=timeout,
        )


__all__ = [
    "MenuResource",
]
