"""Endpoints under `/api/1/notifications/send`.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from iikocloudapi._resource import Resource
from iikocloudapi.models.common import CorrelationIdResponse
from iikocloudapi.models.general import SendNotificationRequest


class NotificationsResource(Resource):
    """Endpoints under `/api/1/notifications/send`."""

    __slots__ = ()

    async def send(
        self,
        *,
        body: SendNotificationRequest | Mapping[str, Any],
        timeout: float | None = None,
    ) -> CorrelationIdResponse:
        """Send notification to external systems.

        `POST /api/1/notifications/send`

        Restriction group: `Notifications`.

        Args:
            body: Request body.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `CorrelationIdResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Notifications/paths/~1api~11~1notifications~1send/post)
        """
        return await self._client._call(
            "/api/1/notifications/send",
            SendNotificationRequest,
            body,
            CorrelationIdResponse,
            timeout=timeout,
        )


__all__ = [
    "NotificationsResource",
]
