"""Endpoints under `/api/platform/v1/events`.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

import datetime
from collections.abc import Sequence

from iikocloudapi._resource import Resource
from iikocloudapi.models.platform import (
    EventListRequest,
    EventListResponse,
    EventMetadataListRequest,
    EventMetadataListResponse,
)


class PlatformEventsMetadataResource(Resource):
    """Endpoints under `/api/platform/v1/events/metadata/list`."""

    __slots__ = ()

    async def list(
        self,
        *,
        timeout: float | None = None,
    ) -> EventMetadataListResponse:
        """Event groups and types.

        `POST /api/platform/v1/events/metadata/list`

        Returns a list of event groups and types

        Args:
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `EventMetadataListResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Platform.Events/paths/~1api~1platform~1v1~1events~1metadata~1list/post)
        """
        return await self._client._call(
            "/api/platform/v1/events/metadata/list",
            EventMetadataListRequest,
            {},
            EventMetadataListResponse,
            timeout=timeout,
        )


class PlatformEventsResource(Resource):
    """Endpoints under `/api/platform/v1/events`."""

    __slots__ = ()

    @property
    def metadata(self) -> PlatformEventsMetadataResource:
        """Endpoints under `/api/platform/v1/events/metadata/list`."""
        return PlatformEventsMetadataResource(self._client)

    async def list(
        self,
        *,
        event_types: Sequence[str] | None = None,
        from_revision: int | None = None,
        from_time: datetime.datetime | str | None = None,
        organization_id: str | None = None,
        to_time: datetime.datetime | str | None = None,
        timeout: float | None = None,
    ) -> EventListResponse:
        """List of events.

        `POST /api/platform/v1/events/list`

        Returns a list of events for a period or starting from a given revision. Exactly one mode is required: fromRevision, or both fromTime and toTime. fromRevision cannot be combined with fromTime or toTime.

        Args:
            event_types: Event codes to filter by. If omitted or empty, all events are returned
            from_revision: Revision to request events from (incremental mode), must be zero or greater. Required unless both fromTime and toTime are provided. Cannot be combined with fromTime/toTime
            from_time: Period start, inclusive, date-time format. Required together with toTime when fromRevision is not provided
            organization_id: Organization identifier (GUID). If provided, the request goes to the RMS API; otherwise to the Chain API by userContext.uocId
            to_time: Period end, exclusive, date-time format. Required together with fromTime when fromRevision is not provided
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `EventListResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Platform.Events/paths/~1api~1platform~1v1~1events~1list/post)
        """
        return await self._client._call(
            "/api/platform/v1/events/list",
            EventListRequest,
            {
                "event_types": event_types,
                "from_revision": from_revision,
                "from_time": from_time,
                "organization_id": organization_id,
                "to_time": to_time,
            },
            EventListResponse,
            timeout=timeout,
        )


class PlatformResource(Resource):
    """Endpoints under `/api/platform/v1/events`."""

    __slots__ = ()

    @property
    def events(self) -> PlatformEventsResource:
        """Endpoints under `/api/platform/v1/events`."""
        return PlatformEventsResource(self._client)


__all__ = [
    "PlatformEventsMetadataResource",
    "PlatformEventsResource",
    "PlatformResource",
]
