"""Endpoints under `/api/reporting/v1`.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

import builtins
import datetime
from collections.abc import Mapping, Sequence
from typing import Any

from iikocloudapi._resource import Resource
from iikocloudapi.models.reports import (
    GetIncomePlanRequest,
    GetIncomePlanResponse,
    GetOlapColumnsRequest,
    GetOlapReportRequest,
    GetOlapReportResponse,
    OlapColumn,
    OlapFilterDoc,
    OlapPreset,
    OlapPresetReportRequest,
    OlapPresetsListRequest,
)


class ReportingOlapPresetsResource(Resource):
    """Endpoints under `/api/reporting/v1/olap/presets`."""

    __slots__ = ()

    async def get(
        self,
        *,
        date_from: str,
        date_to: str,
        preset_id: str,
        timeout: float | None = None,
    ) -> GetOlapReportResponse:
        """Get saved OLAP preset data.

        `POST /api/reporting/v1/olap/presets/get`

        Returns the data of a saved OLAP preset by its identifier (`presetId`) for a given period (`dateFrom` — start, `dateTo` — end). A preset is a ready-made report configuration (groupings, aggregates, filters) saved by the restaurant owner; the method lets retrieve a report by that configuration.

        Args:
            date_from: Start of the report period (inclusive) in `yyyy-MM-dd` format
            date_to: End of the report period (exclusive) in `yyyy-MM-dd` format
            preset_id: Identifier of the saved OLAP preset (from `olap/presets/list`)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `GetOlapReportResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Reporting.Olap/paths/~1api~1reporting~1v1~1olap~1presets~1get/post)
        """
        return await self._client._call(
            "/api/reporting/v1/olap/presets/get",
            OlapPresetReportRequest,
            {"date_from": date_from, "date_to": date_to, "preset_id": preset_id},
            GetOlapReportResponse,
            timeout=timeout,
        )

    async def list(
        self,
        *,
        timeout: float | None = None,
    ) -> builtins.list[OlapPreset]:
        """Get saved OLAP presets.

        `POST /api/reporting/v1/olap/presets/list`

        Returns the list of OLAP presets saved in iikoOffice — ready-made report configurations set up by the restaurant owner. Each item contains an identifier (`presetId`) and the preset name. The method returns all saved presets.

        Args:
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `list[OlapPreset]` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Reporting.Olap/paths/~1api~1reporting~1v1~1olap~1presets~1list/post)
        """
        return await self._client._call(
            "/api/reporting/v1/olap/presets/list",
            OlapPresetsListRequest,
            {},
            list[OlapPreset],
            timeout=timeout,
        )


class ReportingOlapColumnsResource(Resource):
    """Endpoints under `/api/reporting/v1/olap/columns/get`."""

    __slots__ = ()

    async def get(
        self,
        *,
        report_type: str,
        timeout: float | None = None,
    ) -> builtins.list[OlapColumn]:
        """Get OLAP report columns.

        `POST /api/reporting/v1/olap/columns/get`

        Returns the list of columns available in the OLAP report of the given type (`reportType`)

        Args:
            report_type: Report type: `SALES` — sales, `TRANSACTIONS` — transactions, `DELIVERIES` — deliveries
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `list[OlapColumn]` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Reporting.Olap/paths/~1api~1reporting~1v1~1olap~1columns~1get/post)
        """
        return await self._client._call(
            "/api/reporting/v1/olap/columns/get",
            GetOlapColumnsRequest,
            {"report_type": report_type},
            list[OlapColumn],
            timeout=timeout,
        )


class ReportingOlapResource(Resource):
    """Endpoints under `/api/reporting/v1/olap`."""

    __slots__ = ()

    @property
    def columns(self) -> ReportingOlapColumnsResource:
        """Endpoints under `/api/reporting/v1/olap/columns/get`."""
        return ReportingOlapColumnsResource(self._client)

    @property
    def presets(self) -> ReportingOlapPresetsResource:
        """Endpoints under `/api/reporting/v1/olap/presets`."""
        return ReportingOlapPresetsResource(self._client)

    async def get(
        self,
        *,
        aggregate_fields: Sequence[str],
        filters: Sequence[OlapFilterDoc | Mapping[str, Any]],
        report_type: str,
        build_summary: bool | None = None,
        group_by_col_fields: Sequence[str] | None = None,
        group_by_row_fields: Sequence[str] | None = None,
        timeout: float | None = None,
    ) -> GetOlapReportResponse:
        """Run OLAP report.

        `POST /api/reporting/v1/olap/get`

        Builds an OLAP report on sales, transactions or deliveries with an arbitrary configuration and returns its data (`data`) and totals (`summary`). This is the main way for an integrator to build analytical data marts and management reporting: the client defines the row and column grouping fields, aggregate fields and filters.
        Field names (`groupByRowFields`, `groupByColFields`, `aggregateFields`, `filters`) are taken from the metadata of the `olap/columns/get` method. The set of available fields changes between versions of the server's internal API, so request the current metadata before building a report.
        Every request must contain a date filter. Dates must use the `yyyy-MM-dd` format. Recommended date fields: `OpenDate.Typed` for SALES and DELIVERIES, `DateTime.DateTyped` (or `DateTime.Typed`) for TRANSACTIONS.
        **Caution!</> A query that is too broad: a long period, a large number of restaurants or fields/groupings, as well as balance fields (`StartBalance.*`, `FinalBalance.*`), which are calculated over the entire transaction history, may take a long time to run or return no result. Split large queries into smaller sequential queries with a narrow period. To get balances, use specialized methods instead of OLAP.

        Args:
            aggregate_fields: Non-empty list of fields to aggregate by (`FieldName` names from `columns/get`)
            filters: Report filters: an array of filter structures; each contains name (`FieldName` from `columns/get`) and `filterType`, remaining fields depend on filterType (see filter models); at least one `DateRange` filter by the `OpenDate.Typed` field is required. For periodType = CUSTOM the period is limited to 31 days inclusive.
            report_type: Report type: `SALES` — sales, `TRANSACTIONS` — transactions, `DELIVERIES` — deliveries
            build_summary: Whether to build totals
            group_by_col_fields: Fields to group columns by (`FieldName` names from `columns/get`)
            group_by_row_fields: Fields to group rows by (`FieldName` names from `columns/get`)
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `GetOlapReportResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Reporting.Olap/paths/~1api~1reporting~1v1~1olap~1get/post)
        """
        return await self._client._call(
            "/api/reporting/v1/olap/get",
            GetOlapReportRequest,
            {
                "aggregate_fields": aggregate_fields,
                "filters": filters,
                "report_type": report_type,
                "build_summary": build_summary,
                "group_by_col_fields": group_by_col_fields,
                "group_by_row_fields": group_by_row_fields,
            },
            GetOlapReportResponse,
            timeout=timeout,
        )


class ReportingIncomePlanResource(Resource):
    """Endpoints under `/api/reporting/v1/income-plan/list`."""

    __slots__ = ()

    async def list(
        self,
        *,
        date_from: datetime.date | str,
        date_to: datetime.date | str,
        organization_id: str,
        timeout: float | None = None,
    ) -> GetIncomePlanResponse:
        """Get income plan.

        `POST /api/reporting/v1/income-plan/list`

        Returns daily planned income values for an organization over the requested period.

        Args:
            date_from: Period start date (inclusive)
            date_to: Period end date (inclusive)
            organization_id: Organization (department) identifier; used to resolve the plan
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `GetIncomePlanResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Reporting.IncomePlan/paths/~1api~1reporting~1v1~1income-plan~1list/post)
        """
        return await self._client._call(
            "/api/reporting/v1/income-plan/list",
            GetIncomePlanRequest,
            {"date_from": date_from, "date_to": date_to, "organization_id": organization_id},
            GetIncomePlanResponse,
            timeout=timeout,
        )


class ReportingResource(Resource):
    """Endpoints under `/api/reporting/v1`."""

    __slots__ = ()

    @property
    def income_plan(self) -> ReportingIncomePlanResource:
        """Endpoints under `/api/reporting/v1/income-plan/list`."""
        return ReportingIncomePlanResource(self._client)

    @property
    def olap(self) -> ReportingOlapResource:
        """Endpoints under `/api/reporting/v1/olap`."""
        return ReportingOlapResource(self._client)


__all__ = [
    "ReportingIncomePlanResource",
    "ReportingOlapColumnsResource",
    "ReportingOlapPresetsResource",
    "ReportingOlapResource",
    "ReportingResource",
]
