"""Endpoints under `/api/1/stop_lists`.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any

from iikocloudapi._resource import Resource
from iikocloudapi.models.common import CorrelationIdResponse, OrderItem
from iikocloudapi.models.general import (
    AddProductsToStopListItem,
    AddProductsToStopListRequest,
    CheckStopListRequest,
    CheckStopListResponse,
    ClearStopListRequest,
    RemoveProductsFromStopListItem,
    RemoveProductsFromStopListRequest,
    StopListsRequest,
    StopListsResponse,
)


class StopListsResource(Resource):
    """Endpoints under `/api/1/stop_lists`."""

    __slots__ = ()

    async def __call__(
        self,
        *,
        organization_ids: Sequence[str],
        return_size: bool | None = None,
        terminal_groups_ids: Sequence[str] | None = None,
        timeout: float | None = None,
    ) -> StopListsResponse:
        """Out-of-stock items.

        `POST /api/1/stop_lists`

        Restriction group: `Data: stoplists`.

        Args:
            organization_ids: Organizations for which out-of-stock lists will be requested. Can be obtained by `/api/1/organizations` operation.
            return_size: Flag indicating the need to return the sizes of the dish.
            terminal_groups_ids: List of terminal groups for which you need to get out-of-stock lists. Can be obtained by `/api/1/terminal_groups` operation.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `StopListsResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Menu/paths/~1api~11~1stop_lists/post)
        """
        return await self._client._call(
            "/api/1/stop_lists",
            StopListsRequest,
            {
                "organization_ids": organization_ids,
                "return_size": return_size,
                "terminal_groups_ids": terminal_groups_ids,
            },
            StopListsResponse,
            timeout=timeout,
        )

    async def add(
        self,
        *,
        organization_id: str,
        terminal_group_id: str,
        items: Sequence[AddProductsToStopListItem | Mapping[str, Any]],
        timeout: float | None = None,
    ) -> CorrelationIdResponse:
        """Add items to out-of-stock list.
        (You should have extra rights to use this method).

        `POST /api/1/stop_lists/add`

        Allowed from version `8.6.1`.

        Restriction group: `Data: changing stoplists`.

        Args:
            organization_id: Organization ID. Can be obtained by `/api/1/organizations` operation.
            terminal_group_id: Terminal group ID. Can be obtained by `/api/1/terminal_groups` operation.
            items: Items for adding to out-of-stock list.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `CorrelationIdResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Menu/paths/~1api~11~1stop_lists~1add/post)
        """
        return await self._client._call(
            "/api/1/stop_lists/add",
            AddProductsToStopListRequest,
            {"organization_id": organization_id, "terminal_group_id": terminal_group_id, "items": items},
            CorrelationIdResponse,
            timeout=timeout,
        )

    async def check(
        self,
        *,
        organization_id: str,
        terminal_group_id: str,
        items: Sequence[OrderItem | Mapping[str, Any]],
        timeout: float | None = None,
    ) -> CheckStopListResponse:
        """Check items in out-of-stock list.

        `POST /api/1/stop_lists/check`

        Restriction group: `Orders: creating`.

        Args:
            organization_id: Organization ID. Can be obtained by `/api/1/organizations` operation.
            terminal_group_id: Front group ID the order must be sent to. Can be obtained by `/api/1/terminal_groups` operation.
            items: Order items.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `CheckStopListResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Menu/paths/~1api~11~1stop_lists~1check/post)
        """
        return await self._client._call(
            "/api/1/stop_lists/check",
            CheckStopListRequest,
            {"organization_id": organization_id, "terminal_group_id": terminal_group_id, "items": items},
            CheckStopListResponse,
            timeout=timeout,
        )

    async def clear(
        self,
        *,
        organization_id: str,
        terminal_group_id: str,
        timeout: float | None = None,
    ) -> CorrelationIdResponse:
        """Clear out-of-stock list.
        (You should have extra rights to use this method).

        `POST /api/1/stop_lists/clear`

        Allowed from version `8.6.1`.

        Restriction group: `Data: changing stoplists`.

        Args:
            organization_id: Organization ID. Can be obtained by `/api/1/organizations` operation.
            terminal_group_id: Terminal group ID. Can be obtained by `/api/1/terminal_groups` operation.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `CorrelationIdResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Menu/paths/~1api~11~1stop_lists~1clear/post)
        """
        return await self._client._call(
            "/api/1/stop_lists/clear",
            ClearStopListRequest,
            {"organization_id": organization_id, "terminal_group_id": terminal_group_id},
            CorrelationIdResponse,
            timeout=timeout,
        )

    async def remove(
        self,
        *,
        organization_id: str,
        terminal_group_id: str,
        items: Sequence[RemoveProductsFromStopListItem | Mapping[str, Any]],
        timeout: float | None = None,
    ) -> CorrelationIdResponse:
        """Remove items from out-of-stock list.
        (You should have extra rights to use this method).

        `POST /api/1/stop_lists/remove`

        Allowed from version `8.6.1`.

        Restriction group: `Data: changing stoplists`.

        Args:
            organization_id: Organization ID. Can be obtained by `/api/1/organizations` operation.
            terminal_group_id: Terminal group ID. Can be obtained by `/api/1/terminal_groups` operation.
            items: Items for removing from out-of-stock list.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `CorrelationIdResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Menu/paths/~1api~11~1stop_lists~1remove/post)
        """
        return await self._client._call(
            "/api/1/stop_lists/remove",
            RemoveProductsFromStopListRequest,
            {"organization_id": organization_id, "terminal_group_id": terminal_group_id, "items": items},
            CorrelationIdResponse,
            timeout=timeout,
        )


__all__ = [
    "StopListsResource",
]
