"""Endpoints under `/api/1/terminal_groups`.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence

from iikocloudapi._resource import Resource
from iikocloudapi.models.common import TerminalGroupsResponse
from iikocloudapi.models.general import (
    AwakeTerminalGroupsRequest,
    AwakeTerminalGroupsResponse,
    TerminalGroupsIsAliveRequest,
    TerminalGroupsIsAliveResponse,
    TerminalGroupsRequest,
)


class TerminalGroupsResource(Resource):
    """Endpoints under `/api/1/terminal_groups`."""

    __slots__ = ()

    async def __call__(
        self,
        *,
        organization_ids: Sequence[str],
        include_disabled: bool | None = None,
        return_external_data: Sequence[str] | None = None,
        timeout: float | None = None,
    ) -> TerminalGroupsResponse:
        """Method that returns information on groups of delivery terminals.

        `POST /api/1/terminal_groups`

        Restriction group: `Data: dictionaries`.

        Args:
            organization_ids: Organizations IDs for which information is requested. Can be obtained by `/api/1/organizations` operation.
            include_disabled: Attribute that shows that response contains disabled terminal groups.
            return_external_data: External data keys that have to be returned.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `TerminalGroupsResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Terminal-groups/paths/~1api~11~1terminal_groups/post)
        """
        return await self._client._call(
            "/api/1/terminal_groups",
            TerminalGroupsRequest,
            {
                "organization_ids": organization_ids,
                "include_disabled": include_disabled,
                "return_external_data": return_external_data,
            },
            TerminalGroupsResponse,
            timeout=timeout,
        )

    async def awake(
        self,
        *,
        organization_ids: Sequence[str],
        terminal_group_ids: Sequence[str],
        timeout: float | None = None,
    ) -> AwakeTerminalGroupsResponse:
        """Awake terminal groups from sleep mode.

        `POST /api/1/terminal_groups/awake`

        Restriction group: `Organizations: settings`.

        Args:
            organization_ids: Organization IDs. Can be obtained by `/api/1/organizations` operation.
            terminal_group_ids: List of terminal groups IDs. Can be obtained by `/api/1/terminal_groups` operation.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `AwakeTerminalGroupsResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Terminal-groups/paths/~1api~11~1terminal_groups~1awake/post)
        """
        return await self._client._call(
            "/api/1/terminal_groups/awake",
            AwakeTerminalGroupsRequest,
            {"organization_ids": organization_ids, "terminal_group_ids": terminal_group_ids},
            AwakeTerminalGroupsResponse,
            timeout=timeout,
        )

    async def is_alive(
        self,
        *,
        terminal_group_ids: Sequence[str],
        organization_id: str | None = None,
        organization_ids: Sequence[str] | None = None,
        timeout: float | None = None,
    ) -> TerminalGroupsIsAliveResponse:
        """Returns information on availability of group of terminals.

        `POST /api/1/terminal_groups/is_alive`

        Restriction group: `POS: availability`.

        Args:
            terminal_group_ids: List of terminal groups IDs. Can be obtained by `/api/1/terminal_groups` operation.
            organization_id: **Deprecated.** Organization ID. Deprecated, use "organizationIds".
            organization_ids: Organization IDs. Can be obtained by `/api/1/organizations` operation.
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `TerminalGroupsIsAliveResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Terminal-groups/paths/~1api~11~1terminal_groups~1is_alive/post)
        """
        return await self._client._call(
            "/api/1/terminal_groups/is_alive",
            TerminalGroupsIsAliveRequest,
            {
                "terminal_group_ids": terminal_group_ids,
                "organization_id": organization_id,
                "organization_ids": organization_ids,
            },
            TerminalGroupsIsAliveResponse,
            timeout=timeout,
        )


__all__ = [
    "TerminalGroupsResource",
]
