"""Endpoints under `/api/terminals/v1`.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Sequence

from iikocloudapi._resource import Resource
from iikocloudapi.models.terminals import (
    CashRegisterListRequest,
    CashRegisterListResponse,
    TerminalListRequest,
    TerminalListResponse,
)


class TerminalsTerminalsResource(Resource):
    """Endpoints under `/api/terminals/v1/terminals/list`."""

    __slots__ = ()

    async def list(
        self,
        *,
        organization_id: str,
        include_anonymous: bool | None = None,
        search: str | None = None,
        timeout: float | None = None,
    ) -> TerminalListResponse:
        """List of terminals.

        `POST /api/terminals/v1/terminals/list`

        Returns a list of terminals

        Args:
            organization_id: Organization identifier (GUID)
            include_anonymous: Include anonymous terminals. Default value: `false`
            search: Filter by terminal name
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `TerminalListResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Terminals.Terminals/paths/~1api~1terminals~1v1~1terminals~1list/post)
        """
        return await self._client._call(
            "/api/terminals/v1/terminals/list",
            TerminalListRequest,
            {"organization_id": organization_id, "include_anonymous": include_anonymous, "search": search},
            TerminalListResponse,
            timeout=timeout,
        )


class TerminalsCashRegistersResource(Resource):
    """Endpoints under `/api/terminals/v1/cash-registers/list`."""

    __slots__ = ()

    async def list(
        self,
        *,
        organization_id: str,
        limit: int | None = None,
        offset: int | None = None,
        search: str | None = None,
        terminal_group_ids: Sequence[str] | None = None,
        timeout: float | None = None,
    ) -> CashRegisterListResponse:
        """List of cash registers.

        `POST /api/terminals/v1/cash-registers/list`

        Returns the list of cash registers of the organization

        Args:
            organization_id: Organization identifier (GUID)
            limit: Items per page. Default value: `50`, from `1` to `1000`
            offset: Offset. Default value: `0`, non-negative
            search: Case-insensitive substring search by name or number
            terminal_group_ids: Filter by terminal group identifiers (UUID). Duplicates do not affect the result
            timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.

        Returns:
            The `CashRegisterListResponse` response.

        [iikoCloud API reference](https://api-ru.iiko.services/docs#tag/Terminals.CashRegisters/paths/~1api~1terminals~1v1~1cash-registers~1list/post)
        """
        return await self._client._call(
            "/api/terminals/v1/cash-registers/list",
            CashRegisterListRequest,
            {
                "organization_id": organization_id,
                "limit": limit,
                "offset": offset,
                "search": search,
                "terminal_group_ids": terminal_group_ids,
            },
            CashRegisterListResponse,
            timeout=timeout,
        )


class TerminalsResource(Resource):
    """Endpoints under `/api/terminals/v1`."""

    __slots__ = ()

    @property
    def cash_registers(self) -> TerminalsCashRegistersResource:
        """Endpoints under `/api/terminals/v1/cash-registers/list`."""
        return TerminalsCashRegistersResource(self._client)

    @property
    def terminals(self) -> TerminalsTerminalsResource:
        """Endpoints under `/api/terminals/v1/terminals/list`."""
        return TerminalsTerminalsResource(self._client)


__all__ = [
    "TerminalsCashRegistersResource",
    "TerminalsResource",
    "TerminalsTerminalsResource",
]
