"""Render the IR to Python source code."""

from __future__ import annotations

import re
from collections import defaultdict
from dataclasses import dataclass, field

from codegen.build import COMMON, IR, EnumDef, FieldDef, MethodDef, ModelDef, UnionDef
from codegen.naming import pascal

GENERATED = "Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand."

_BASE_NAMES = {
    "IikoDateTime",
    "IsoDateTime",
    "IikoModel",
    "OpenIntEnum",
    "OpenStrEnum",
    "OrganizationItems",
    "UNKNOWN",
    "discriminator",
}
_TYPING_NAMES = {"Annotated", "Any", "Literal"}
_ABC_NAMES = {"Mapping", "Sequence"}

MODULE_TITLES = {
    COMMON: "Models shared by several API sections.",
    "general": "Models of the general endpoints: organizations, terminal groups, dictionaries, menu, notifications...",
    "delivery": "Models of the delivery endpoints.",
    "orders": "Models of the table order endpoints.",
    "reserves": "Models of the banquet/reserve endpoints.",
    "webhooks": "Models of webhook settings and webhook events.",
    "licenses": "Models of the license endpoints.",
    "loyalty": "Models of the loyalty (iikoCard) endpoints.",
    "inventory": "Models of the inventory endpoints.",
    "finance": "Models of the finance endpoints.",
    "nomenclature": "Models of the nomenclature management endpoints.",
    "employees": "Models of the employee endpoints.",
    "reports": "Models of the reporting endpoints.",
    "terminals": "Models of the terminal endpoints.",
    "platform": "Models of the platform endpoints.",
}


def docstring(text: str, indent: str) -> list[str]:
    text = text.replace("\\", "\\\\").replace('"""', '\\"\\"\\"').strip()
    if not text:
        return []
    lines = text.split("\n")
    if len(lines) == 1:
        quoted = f'{indent}"""{lines[0]}"""'
        if lines[0].endswith('"'):
            quoted = f'{indent}"""{lines[0]} """'
        return [quoted]
    out = [f'{indent}"""{lines[0]}']
    out += [f"{indent}{line}" if line else "" for line in lines[1:]]
    out.append(f'{indent}"""')
    return out


def one_line(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def first_sentence(text: str) -> str:
    text = one_line(text)
    match = re.match(r"(.+?[.!?])(\s|$)", text)
    return match.group(1) if match else text


_IDENT = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


@dataclass
class Imports:
    module: str
    names: set[str] = field(default_factory=set)

    def add_annotation(self, annotation: str) -> None:
        self.names.update(_IDENT.findall(annotation))

    def render(self, ir: IR, local: set[str]) -> list[str]:
        typing_names = sorted(self.names & _TYPING_NAMES)
        abc = sorted(self.names & _ABC_NAMES)
        base = sorted(self.names & _BASE_NAMES)
        by_module: dict[str, set[str]] = defaultdict(set)
        for name in self.names - local:
            module = ir.module_of.get(name)
            if module and name not in _BASE_NAMES:
                by_module[f"iikocloudapi.models.{module}"].add(name)
        lines = ["from __future__ import annotations", ""]
        std = []
        if "builtins" in self.names:
            std.append("import builtins")
        if "datetime" in self.names:
            std.append("import datetime")
        if abc:
            std.append(f"from collections.abc import {', '.join(abc)}")
        if "Decimal" in self.names:
            std.append("from decimal import Decimal")
        if typing_names:
            std.append(f"from typing import {', '.join(typing_names)}")
        lines += std
        third = []
        pyd = sorted(self.names & {"Field", "Tag"})
        if pyd:
            third.append(f"from pydantic import {', '.join(pyd)}")
        if "deprecated" in self.names:
            third.append("from typing_extensions import deprecated")
        if third:
            lines += ["", *third]
        first = []
        if base:
            first.append(f"from iikocloudapi._base import {', '.join(base)}")
        if "Resource" in self.names:
            first.append("from iikocloudapi._resource import Resource")
        for module in sorted(by_module):
            if module == self.module:
                continue
            first.append(f"from {module} import {', '.join(sorted(by_module[module]))}")
        if first:
            lines += ["", *first]
        return lines


def render_enum(enum: EnumDef) -> list[str]:
    base = "OpenIntEnum" if enum.kind == "int" else "OpenStrEnum"
    lines = [f"class {enum.name}({base}):"]
    lines += docstring(enum.description or f"{enum.name} values.", "    ")
    lines.append("")
    for name, value, label in enum.members:
        lines.append(f"    {name} = {value!r}")
        if label:
            lines += docstring(label[:1].upper() + label[1:] + ("" if label.endswith(".") else "."), "    ")
    return lines


def render_field(f: FieldDef) -> list[str]:
    kwargs = []
    if f.explicit_alias:
        kwargs.append(f"alias={f.alias!r}")
    kwargs += [f"{k}={v!r}" for k, v in f.extras.items()]
    value = f.default
    if kwargs:
        value = f"Field({', '.join(([f'default={f.default}'] if f.default is not None else []) + kwargs)})"
    line = f"    {f.name}: {f.annotation}"
    if value is not None:
        line += f" = {value}"
    if f.override:
        line += "  # pyright: ignore[reportIncompatibleVariableOverride]"
    return [line, *docstring(f.description, "    ")]


def render_model(model: ModelDef) -> list[str]:
    base = model.base or "IikoModel"
    if model.name == "OrganizationItems":
        return []
    lines = [f"class {model.name}({base}):"]
    lines += docstring(model.description or f"{model.name}.", "    ")
    own = [
        d
        for d in model.discriminators
        if any(f.name == d and (f.always_send or f.default not in (None, "None")) for f in model.fields)
    ]
    if own:
        lines += ["", f"    __always_sent__ = ({', '.join(repr(d) for d in dict.fromkeys(own))},)"]
    if model.variants:
        name, tags = model.variants
        lines += ["", f"    __variants__ = ({name!r}, ({', '.join(repr(t) for t in tags)},))"]
    if model.fields:
        lines.append("")
    for f in model.fields:
        lines += render_field(f)
    return lines


def render_union(union: UnionDef) -> list[str]:
    members = [f'Annotated[{name}, Tag("{value}")]' for value, name in union.members]
    members.append(f"Annotated[{union.fallback}, Tag(UNKNOWN)]")
    known = ", ".join(repr(str(value)) for value, _ in union.members)
    lines = [f"{union.name} = Annotated["]
    lines.append("    " + "\n    | ".join(members) + ",")
    lines.append(f"    discriminator({union.discriminator_alias!r}, {union.discriminator_name!r}, ({known},)),")
    lines.append("]")
    doc = union.description or f"Any of the {union.name} variants."
    doc += (
        f"\n\nOne of {', '.join(f'`{name}`' for _, name in union.members)}, selected by `{union.discriminator_name}`."
        f" Values unknown to this library are parsed as `{union.fallback}`."
    )
    lines += docstring(doc, "")
    return lines


def render_models_module(ir: IR, module: str) -> str:
    enums, models, unions = ir.module_items(module)
    imports = Imports(module=f"iikocloudapi.models.{module}")
    local = {e.name for e in enums} | {m.name for m in models} | {u.name for u in unions}
    if enums:
        imports.names.add("OpenIntEnum" if any(e.kind == "int" for e in enums) else "OpenStrEnum")
        if any(e.kind == "str" for e in enums):
            imports.names.add("OpenStrEnum")
    for model in models:
        imports.names.add(model.base or "IikoModel")
        for f in model.fields:
            imports.add_annotation(f.annotation)
            if f.default and "." in f.default:
                imports.add_annotation(f.default)
            if f.explicit_alias or f.extras:
                imports.names.add("Field")
    for union in unions:
        imports.names |= {"Annotated", "Tag", "UNKNOWN", "discriminator"} | union.deps
    parts = [f'"""{MODULE_TITLES.get(module, "Models.")}\n\n{GENERATED}\n"""', ""]
    parts += imports.render(ir, local)
    body: list[list[str]] = []
    body += [render_enum(e) for e in enums]
    body += [render_model(m) for m in models if m.name != "OrganizationItems"]
    body += [render_union(u) for u in unions]
    exported = sorted(local | ({"OrganizationItems"} if module == COMMON else set()))
    if module == COMMON:
        parts.append("from iikocloudapi._base import OrganizationItems")
    out = "\n".join(parts) + "\n\n\n" + "\n\n\n".join("\n".join(b) for b in body if b)
    out += "\n\n\n__all__ = [\n" + "".join(f"    {name!r},\n" for name in exported) + "]\n"
    return out


def render_models_init(ir: IR) -> str:
    lines = [
        '"""All request and response models of the iikoCloud API.',
        "",
        "Every model is also available from its section module, e.g. ``iikocloudapi.models.delivery``.",
        "",
        GENERATED,
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]
    names_by_module: dict[str, list[str]] = defaultdict(list)
    for name, module in ir.module_of.items():
        names_by_module[module].append(name)
    exported = []
    for module in sorted(names_by_module):
        names = sorted(names_by_module[module])
        exported += names
        lines.append(f"from iikocloudapi.models.{module} import (")
        lines += [f"    {name} as {name}," for name in names]
        lines.append(")")
    lines += ["", "__all__ = ["] + [f"    {name!r}," for name in sorted(exported)] + ["]", ""]
    return "\n".join(lines)


@dataclass
class Node:
    path: tuple[str, ...]
    children: dict[str, Node] = field(default_factory=dict)
    methods: list[MethodDef] = field(default_factory=list)
    call: MethodDef | None = None

    @property
    def class_name(self) -> str:
        return "".join(pascal(segment) for segment in self.path) + "Resource"

    def walk(self) -> list[Node]:
        nodes: list[Node] = [self]
        for child in self.children.values():
            nodes += child.walk()
        return nodes

    def prefix_url(self) -> str:
        urls = [m.op.url for m in self.all_methods()]
        common = urls[0]
        for url in urls[1:]:
            while not url.startswith(common):
                common = common[: common.rfind("/")]
        return common

    def all_methods(self) -> list[MethodDef]:
        result = list(self.methods) + ([self.call] if self.call else [])
        for child in self.children.values():
            result += child.all_methods()
        return result


def resource_tree(methods: list[MethodDef]) -> Node:
    root = Node(path=())
    prefixes = {m.op.path[:i] for m in methods for i in range(1, len(m.op.path))}
    for method in methods:
        node = root
        for depth, segment in enumerate(method.op.path[:-1], start=1):
            node = node.children.setdefault(segment, Node(path=method.op.path[:depth]))
        last = method.op.path[-1]
        if method.op.path in prefixes:
            child = node.children.setdefault(last, Node(path=method.op.path))
            child.call = method
        else:
            node.methods.append(method)
    return root


def method_docstring(method: MethodDef) -> str:
    op = method.op
    summary = op.summary.rstrip()
    if summary and not summary.endswith((".", "!", "?")):
        summary += "."
    parts = [summary or f"POST {op.url}", f"`POST {op.url}`"]
    from codegen.build import clean_text  # noqa: PLC0415

    description = clean_text(op.description)
    description = re.sub(
        r"This method is a command\. Use `?api/1/commands/status`? method to get the progress status\.\s*",
        "",
        description,
    ).strip()
    if description:
        parts.append(description)
    if op.deprecated:
        parts.append("Warning:\n    iikoCloud marks this endpoint as deprecated.")
    if op.is_command:
        parts.append(
            "Note:\n    This method is a command: it only starts the operation. Pass the response to\n"
            "    `IikoCloud.wait()` to wait for the result."
        )
    params = list(method.params)
    if method.body_param:
        params = [method.body_param]
    args = []
    for p in params:
        desc = one_line(p.description) or "See the API reference."
        args.append(f"    {p.name}: {desc}")
    args.append("    timeout: Server-side timeout in seconds (`Timeout` header). Defaults to the client setting.")
    parts.append("Args:\n" + "\n".join(args))
    if method.response != "None":
        parts.append(f"Returns:\n    The `{method.response.removeprefix('builtins.')}` response.")
    parts.append(f"[iikoCloud API reference]({op.docs_url})")
    return "\n\n".join(parts)


def render_method(method: MethodDef, name: str) -> list[str]:
    lines = []
    if method.op.deprecated:
        lines.append(f'    @deprecated("{method.op.url} is deprecated by iikoCloud")')
    signature = [f"    async def {name}(", "        self,"]
    params = [method.body_param] if method.body_param else method.params
    if params:
        signature.append("        *,")
    for p in params:
        default = " = None" if not p.required else ""
        signature.append(f"        {p.name}: {p.input_annotation}{default},")
    if not params:
        signature.append("        *,")
    signature.append("        timeout: float | None = None,")
    signature.append(f"    ) -> {method.response}:")
    lines += signature
    lines += docstring(method_docstring(method), "        ")
    if method.body_param:
        request_type, data = method.body_param.annotation, "body"
    elif method.request_model:
        request_type = method.request_model
        data = "{" + ", ".join(f'"{p.name}": {p.name}' for p in method.params) + "}"
    else:
        request_type, data = "None", "None"
    response = "None" if method.response == "None" else method.response_runtime
    lines.append("        return await self._client._call(")
    lines.append(f'            "{method.op.url}",')
    lines.append(f"            {request_type},")
    lines.append(f"            {data},")
    lines.append(f"            {response},")
    lines.append("            timeout=timeout,")
    lines.append("        )")
    return lines


def method_imports(method: MethodDef, imports: Imports) -> None:
    params = [method.body_param] if method.body_param else method.params
    for p in params:
        imports.add_annotation(p.input_annotation)
        if method.body_param:
            imports.add_annotation(p.annotation)
    imports.add_annotation(method.response)
    if method.request_model:
        imports.names.add(method.request_model)
    if method.op.deprecated:
        imports.names.add("deprecated")


def render_resource_class(node: Node) -> list[str]:
    lines = [f"class {node.class_name}(Resource):"]
    lines += docstring(f"Endpoints under `{node.prefix_url()}`.", "    ")
    lines += ["", "    __slots__ = ()"]
    for name, child in sorted(node.children.items()):
        lines += [
            "",
            "    @property",
            f"    def {name}(self) -> {child.class_name}:",
            *docstring(f"Endpoints under `{child.prefix_url()}`.", "        "),
            f"        return {child.class_name}(self._client)",
        ]
    if node.call:
        lines.append("")
        lines += render_method(node.call, "__call__")
    for method in sorted(node.methods, key=lambda m: m.name):
        lines.append("")
        lines += render_method(method, method.name)
    return lines


def render_resource_module(ir: IR, top: Node) -> str:
    nodes = top.walk()
    imports = Imports(module=f"iikocloudapi.resources.{top.path[0]}")
    imports.names |= {"Resource", "Any", "Mapping"}
    for node in nodes:
        for method in node.methods + ([node.call] if node.call else []):
            method_imports(method, imports)
    local = {n.class_name for n in nodes}
    parts = [f'"""Endpoints under `{top.prefix_url()}`.\n\n{GENERATED}\n"""', ""]
    parts += imports.render(ir, local)
    classes = ["\n".join(render_resource_class(n)) for n in reversed(nodes)]
    exported = sorted(local)
    out = "\n".join(parts) + "\n\n\n" + "\n\n\n".join(classes)
    out += "\n\n\n__all__ = [\n" + "".join(f"    {n!r},\n" for n in exported) + "]\n"
    return out


def render_resources_init(ir: IR, root: Node) -> str:
    imports = Imports(module="iikocloudapi.resources")
    imports.names |= {"Resource", "Any", "Mapping"}
    for method in root.methods:
        method_imports(method, imports)
    parts = [f'"""The root of the generated API resources.\n\n{GENERATED}\n"""', ""]
    parts += imports.render(ir, set())
    child_imports = [
        f"from iikocloudapi.resources.{name} import {child.class_name}" for name, child in sorted(root.children.items())
    ]
    parts += child_imports
    lines = ["class IikoCloudResources(Resource):"]
    lines += docstring("All iikoCloud API endpoints, grouped by their URL.", "    ")
    lines += ["", "    __slots__ = ()"]
    for name, child in sorted(root.children.items()):
        lines += [
            "",
            "    @property",
            f"    def {name}(self) -> {child.class_name}:",
            *docstring(f"Endpoints under `{child.prefix_url()}`.", "        "),
            f"        return {child.class_name}(self._client)",
        ]
    for method in sorted(root.methods, key=lambda m: m.name):
        lines.append("")
        lines += render_method(method, method.name)
    out = "\n".join(parts) + "\n\n\n" + "\n".join(lines)
    out += '\n\n\n__all__ = ["IikoCloudResources"]\n'
    return out


def render_all(ir: IR) -> dict[str, str]:
    files: dict[str, str] = {}
    for module in ir.modules:
        files[f"iikocloudapi/models/{module}.py"] = render_models_module(ir, module)
    files["iikocloudapi/models/__init__.py"] = render_models_init(ir)
    root = resource_tree(ir.methods)
    for name, child in root.children.items():
        files[f"iikocloudapi/resources/{name}.py"] = render_resource_module(ir, child)
    files["iikocloudapi/resources/__init__.py"] = render_resources_init(ir, root)
    return files
