"""Models shared by several API sections.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

from decimal import Decimal
from typing import Annotated, Any, Literal

from pydantic import Field, Tag

from iikocloudapi._base import UNKNOWN, IikoDateTime, IikoModel, OpenStrEnum, OrganizationItems, discriminator


class AddressFormatType(OpenStrEnum):
    """Address format type."""

    LEGACY = "Legacy"
    CITY = "City"
    INTERNATIONAL = "International"
    INT_NO_POSTCODE = "IntNoPostcode"


class AddressHintsServiceType(OpenStrEnum):
    """Address hints service type."""

    DA_DATA = "DaData"
    GET_ADDRESS = "GetAddress"
    YA = "Ya"
    GOOGLE_PLACES = "GooglePlaces"


class CreationStatus(OpenStrEnum):
    """Order creation status."""

    SUCCESS = "Success"
    IN_PROGRESS = "InProgress"
    ERROR = "Error"


class DeliveryOrderPaymentSettings(OpenStrEnum):
    """Delivery payment time option."""

    WHEN_ORDER_ON_THE_WAY = "WhenOrderOnTheWay"
    WHEN_ORDER_CLOSED = "WhenOrderClosed"


class DeliveryServiceType(OpenStrEnum):
    """Order type."""

    DELIVERY_BY_COURIER = "DeliveryByCourier"
    DELIVERY_BY_CLIENT = "DeliveryByClient"


class DeliverySettingsServiceType(OpenStrEnum):
    """Delivery settings service type."""

    COURIER_ONLY = "CourierOnly"
    SELF_SERVICE_ONLY = "SelfServiceOnly"
    COURIER_AND_SELF_SERVICE = "CourierAndSelfService"


class DeliveryStatus(OpenStrEnum):
    """Delivery order statuses."""

    UNCONFIRMED = "Unconfirmed"
    WAIT_COOKING = "WaitCooking"
    READY_FOR_COOKING = "ReadyForCooking"
    COOKING_STARTED = "CookingStarted"
    COOKING_COMPLETED = "CookingCompleted"
    WAITING = "Waiting"
    ON_WAY = "OnWay"
    DELIVERED = "Delivered"
    CLOSED = "Closed"
    CANCELLED = "Cancelled"


class ErrorCode(OpenStrEnum):
    """ErrorCode values."""

    COMMON = "Common"
    ILLEGAL_DELIVERY_STATUS = "IllegalDeliveryStatus"
    CUSTOMER_NAME_NOT_SPECIFIED = "CustomerNameNotSpecified"
    PRODUCT_NOT_FOUND = "ProductNotFound"
    MARKETING_SOURCE_NOT_FOUND = "MarketingSourceNotFound"
    PAYMENT_TYPE_NOT_FOUND = "PaymentTypeNotFound"
    PRODUCT_SIZE_NOT_FOUND = "ProductSizeNotFound"
    PRODUCT_GROUP_NOT_FOUND = "ProductGroupNotFound"
    ORDER_NOT_FOUND = "OrderNotFound"
    CONCEPTION_NOT_FOUND = "ConceptionNotFound"
    DUPLICATED_ORDER_ID = "DuplicatedOrderId"
    TERMINAL_GROUP_ID_NOT_DETERMINED = "TerminalGroupIdNotDetermined"
    TERMINAL_GROUP_UNREGISTERED = "TerminalGroupUnregistered"
    INVALID_PHONE = "InvalidPhone"
    MODIFIER_DUPLICATED = "ModifierDuplicated"
    PRODUCT_CAN_BUY_FROM_CASHDESK = "ProductCanBuyFromCashdesk"
    DELIVERY_OPINION_MARK_INVALID = "DeliveryOpinionMarkInvalid"
    WRONG_DELIVERY_STATUS_FOR_OPINION = "WrongDeliveryStatusForOpinion"
    OPINION_COMMENT_TOO_LONG = "OpinionCommentTooLong"
    SURVEY_ITEM_NOT_FOUND = "SurveyItemNotFound"
    PAYMENT_TYPE_CAN_NOT_BE_USED_AS_EXTERNAL = "PaymentTypeCanNotBeUsedAsExternal"
    ADDRESS_NOT_FOUND = "AddressNotFound"
    HOME_NOT_FOUND = "HomeNotFound"
    IIKONET_PAYMENT_ADDITIONAL_DATA_CAN_NOT_BE_PARSED = "IikonetPaymentAdditionalDataCanNotBeParsed"
    IIKONET_PAYMENT_EXTERNAL_ID_NOT_FOUND = "IikonetPaymentExternalIdNotFound"
    IIKONET_PAYMENT_SUM_LESS_THAN_MARKETING_DISCOUNT = "IikonetPaymentSumLessThanMarketingDiscount"
    DISCOUNT_CARD_NOT_FOUND = "DiscountCardNotFound"
    DISCOUNT_CARD_TYPE_MODE_FORBIDDEN = "DiscountCardTypeModeForbidden"
    IIKOCARD5_PAYMENT_ADDITIONAL_DATA_CAN_NOT_BE_PARSED = "Iikocard5PaymentAdditionalDataCanNotBeParsed"
    IIKOCARD5_PAYMENT_EXTERNAL_ID_NOT_FOUND = "Iikocard5PaymentExternalIdNotFound"
    IIKOCARD5_PAYMENT_SUM_LESS_THAN_MARKETING_DISCOUNT = "Iikocard5PaymentSumLessThanMarketingDiscount"
    IIKOCARD5_PAYMENT_CAN_NOT_CREATE_CUSTOM_DATA = "Iikocard5PaymentCanNotCreateCustomData"
    COURIER_ID_DOES_NOT_EXIST = "CourierIdDoesNotExist"
    COURIER_DOES_NOT_OWN_ORDER = "CourierDoesNotOwnOrder"
    WRONG_DELIVERY_STATUS = "WrongDeliveryStatus"
    CAN_NOT_ASSIGN_COURIER_TO_ORDER = "CanNotAssignCourierToOrder"
    USER_NOT_FOUND_BY_EXTERNAL_PASSWORD = "UserNotFoundByExternalPassword"
    USER_NOT_FOUND = "UserNotFound"
    IIKOCARD51_PAYMENT_ADDITIONAL_DATA_CAN_NOT_BE_PARSED = "Iikocard51PaymentAdditionalDataCanNotBeParsed"
    IIKOCARD51_PAYMENT_CREDENTIAL_NOT_FOUND = "Iikocard51PaymentCredentialNotFound"
    IIKOCARD51_PAYMENT_SEARCH_SCOPE_NOT_FOUND = "Iikocard51PaymentSearchScopeNotFound"
    COMBO_DUPLICATED = "ComboDuplicated"
    INVALID_REFERENCE_TO_COMBO = "InvalidReferenceToCombo"
    INVALID_COMBO_ITEMS_AMOUNT = "InvalidComboItemsAmount"
    INVALID_COMBO_ITEMS_GUEST = "InvalidComboItemsGuest"
    INVALID_REFERENCE_TO_GUEST = "InvalidReferenceToGuest"
    GUEST_DUPLICATED = "GuestDuplicated"
    GUEST_NAME_NOT_SPECIFIED = "GuestNameNotSpecified"
    ORDER_TYPE_NOT_FOUND = "OrderTypeNotFound"
    ORDER_SERVICE_TYPE_DOES_NOT_MATCH_SELF_SERVICE_MODE = "OrderServiceTypeDoesNotMatchSelfServiceMode"
    DELIVERY_DATE_NOT_SPECIFIED = "DeliveryDateNotSpecified"
    ORDER_STATUS_CHANGED_IN_IIKO_FRONT = "OrderStatusChangedInIikoFront"
    PAYMENT_ADDITIONAL_DATA_TOO_LONG = "PaymentAdditionalDataTooLong"
    PAYMENT_SUM_SHOULD_BE_POSITIVE = "PaymentSumShouldBePositive"
    DISCOUNT_SUM_NOT_SPECIFIED = "DiscountSumNotSpecified"
    INVALID_DISCOUNT_ITEM = "InvalidDiscountItem"
    REQUEST_PRODUCT_PRICE_IS_NOT_EQUAL_TO_FRONT_PRICE = "RequestProductPriceIsNotEqualToFrontPrice"
    ORDER_ITEMS_NOT_EXISTS = "OrderItemsNotExists"
    ENTITY_ALREADY_IN_USE = "EntityAlreadyInUse"
    DISCOUNT_ITEM_POSITION_NOT_FOUND = "DiscountItemPositionNotFound"
    DISCOUNT_ITEM_DUPLICATE_POSITIONS = "DiscountItemDuplicatePositions"
    NON_UNQIUE_ORDER_ITEM_POSITION = "NonUnqiueOrderItemPosition"
    EMPTY_ORDER_ITEM_POSITION = "EmptyOrderItemPosition"
    INCORRECT_ORDER_TYPE = "IncorrectOrderType"
    INCORRECT = "Incorrect"
    TERMINAL_GROUP_DISABLED = "TerminalGroupDisabled"
    ORGANIZATION_UNREGISTERED = "OrganizationUnregistered"
    ORGANIZATION_DISABLED = "OrganizationDisabled"
    TOO_SMALL_DELIVERY_DATE = "TooSmallDeliveryDate"
    IIKO_FRONT_TOO_OLD_VERSION = "IikoFrontTooOldVersion"
    DUPLICATED_RESERVE_ID = "DuplicatedReserveId"
    TIPS_TYPE_NOT_APPLICABLE = "TipsTypeNotApplicable"
    ANONYMOUS_CUSTOMER_DISABLED = "AnonymousCustomerDisabled"
    MAY_BE_INCONSISTENT_UPDATES = "MayBeInconsistentUpdates"
    INCONSISTENT_UPDATES = "InconsistentUpdates"
    LINE1_DISABLED = "Line1Disabled"
    INTERNAL_SERVER_ERROR = "InternalServerError"
    UNKNOWN_ERROR = "UnknownError"


class Gender(OpenStrEnum):
    """Sex."""

    NOT_SPECIFIED = "NotSpecified"
    MALE = "Male"
    FEMALE = "Female"


class IikoCardSearchScope(OpenStrEnum):
    """IikoCardSearchScope values."""

    RESERVED = "Reserved"
    PHONE = "Phone"
    CARD_NUMBER = "CardNumber"
    CARD_TRACK = "CardTrack"
    PAYMENT_TOKEN = "PaymentToken"
    FIND_FACE_ID = "FindFaceId"


class OrderItemStatus(OpenStrEnum):
    """Order item status."""

    ADDED = "Added"
    PRINTED_NOT_COOKING = "PrintedNotCooking"
    COOKING_STARTED = "CookingStarted"
    COOKING_COMPLETED = "CookingCompleted"
    SERVED = "Served"


class OrderServiceType(OpenStrEnum):
    """Order type."""

    COMMON = "Common"
    DELIVERY_BY_COURIER = "DeliveryByCourier"
    DELIVERY_BY_CLIENT = "DeliveryByClient"


class OrderStatus(OpenStrEnum):
    """Describes the status of an order."""

    NEW = "New"
    BILL = "Bill"
    CLOSED = "Closed"
    DELETED = "Deleted"


class PaymentTypeKind(OpenStrEnum):
    """Payment type kind."""

    UNKNOWN = "Unknown"
    CASH = "Cash"
    CARD = "Card"
    CREDIT = "Credit"
    WRITEOFF = "Writeoff"
    VOUCHER = "Voucher"
    EXTERNAL = "External"
    SMART_SALE = "SmartSale"
    SBERBANK = "Sberbank"
    TRPOS = "Trpos"


class ReserveCancelReason(OpenStrEnum):
    """Reason why planned event failed."""

    CLIENT_NOT_APPEARED = "ClientNotAppeared"
    CLIENT_REFUSED = "ClientRefused"
    OTHER = "Other"


class ReserveStatus(OpenStrEnum):
    """Describes the status of a reserve or a banquet."""

    NEW = "New"
    STARTED = "Started"
    CLOSED = "Closed"


class RetrievedOrderStatus(OpenStrEnum):
    """Describes the status of an order."""

    NEW = "New"
    BILL = "Bill"
    CLOSED = "Closed"
    DELETED = "Deleted"


class SplitOrderBetweenCashRegisters(OpenStrEnum):
    """Need to split order between cash registers."""

    DISABLED = "Disabled"
    ALLOWED = "Allowed"
    REQUIRED = "Required"


class AddOrderPaymentsRequest(IikoModel):
    """Request for add order payments."""

    order_id: str
    """Order ID."""
    tips: list[TipsPayment] | None = None
    """Order tips."""
    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    payments: list[Payment]
    """Order payments."""


class AddressBase(IikoModel):
    """Order delivery address"""

    __variants__ = (
        "type",
        (
            "legacy",
            "city",
        ),
    )

    type: str


class AddressCity(AddressBase):
    """Order delivery address."""

    __always_sent__ = ("type",)

    type: Literal["city"] = "city"  # pyright: ignore[reportIncompatibleVariableOverride]
    line1: str
    """Address line 1.
    Contains the primary address information.

    Allowed from version `8.7.6`.
    """
    flat: str | None = None
    """Apartment."""
    entrance: str | None = None
    """Entrance."""
    floor: str | None = None
    """Floor."""
    doorphone: str | None = None
    """Intercom."""
    region_id: str | None = None
    """Delivery area ID."""


class AddressLegacy(AddressBase):
    """Order delivery legacy address."""

    __always_sent__ = ("type",)

    type: Literal["legacy"] = "legacy"  # pyright: ignore[reportIncompatibleVariableOverride]
    street: DeliveryStreet
    """Street.
    It's required specify only "classifierId" or "id" or "name" and "city".
    """
    index: str | None = None
    """Postcode."""
    house: str
    """House."""
    building: str | None = None
    """Building."""
    flat: str | None = None
    """Apartment.
    In case useUaeAddressingSystem enabled max length - 100, otherwise - 10.
    """
    entrance: str | None = None
    """Entrance."""
    floor: str | None = None
    """Floor."""
    doorphone: str | None = None
    """Intercom."""
    region_id: str | None = None
    """Delivery area ID."""


class CustomerBase(IikoModel):
    """Customer base info."""

    __variants__ = (
        "type",
        (
            "regular",
            "one-time",
        ),
    )

    type: str


class AnonymousCustomer(CustomerBase):
    """'One-time' customer:
    - should be used if a customer does not agree to take part in the store's loyalty programs or an aggregator (external system) does not provide customer details
    - customer details will NOT be added to the store's customer database and will be used ONLY to complete the current order
    """

    __always_sent__ = ("type",)

    type: Literal["one-time"] = "one-time"  # pyright: ignore[reportIncompatibleVariableOverride]
    name: str
    """Customer name."""


class CancelInfo(IikoModel):
    """Order cancellation details"""

    when_cancelled: IikoDateTime
    """Cancellation time (Local for delivery terminal)."""
    cause: RetrievedCancelCause
    """Delivery cancellation reason."""
    comment: str | None = None
    """Delivery cancellation comment."""


class PaymentBase(IikoModel):
    """Base class of delivery order payment item."""

    __variants__ = (
        "payment_type_kind",
        (
            "Cash",
            "Card",
            "LoyaltyCard",
            "External",
        ),
    )

    payment_type_kind: str
    sum: Decimal
    """Amount due."""
    payment_type_id: str
    """Payment type.

    Can be obtained by `/api/1/payment_types` operation.
    """
    is_processed_externally: bool | None = None
    """Whether payment item is processed by external payment system (made from outside)."""
    payment_additional_data: PaymentAdditionalData | None = None
    """Additional payment parameters."""
    is_fiscalized_externally: bool | None = None
    """Whether the payment item is externally fiscalized.

    Allowed from version `7.6.3`.
    """
    is_prepay: bool | None = None
    """**Deprecated.** Whether the payment item is prepay. Unavailable for `paymentKindType.LoyaltyCard`.

    Allowed from version `8.2.6`.
    """


class CardPayment(PaymentBase):
    """Bank card payment."""

    __always_sent__ = ("payment_type_kind",)

    payment_type_kind: Literal["Card"] = "Card"  # pyright: ignore[reportIncompatibleVariableOverride]
    number: str | None = None
    """**Deprecated.** Card No.
    In iikoFront, it is possible to make card payment without card No.
    """


class PaymentAdditionalDataBase(IikoModel):
    """Additional payment data."""

    __variants__ = (
        "type",
        (
            "LoyaltyCard",
            "Card",
            "External",
        ),
    )

    type: str


class CardPaymentAdditionalData(PaymentAdditionalDataBase):
    """Additional data for Card payment item."""

    __always_sent__ = ("type",)

    type: Literal["Card"] = "Card"  # pyright: ignore[reportIncompatibleVariableOverride]
    number: str | None = None
    """Card No.
    In iikoFront, it is possible to make card payment without card No.
    If this property is set, the above `number` property is ignored.
    """
    custom_data: str | None = None
    """Custom data.

    Allowed from version `8.8.6`.
    """
    card_type: str | None = None
    """Card type (VISA, MasterCard, etc...).

    Allowed from version `9.3.6`.
    """


class TipsPaymentBase(IikoModel):
    """Base class of delivery order payment item."""

    __variants__ = (
        "payment_type_kind",
        (
            "Cash",
            "Card",
            "External",
        ),
    )

    payment_type_kind: str
    tips_type_id: str | None = None
    """Tips type ID.

    Can be obtained by `/api/1/tips_types` operation.
    """
    sum: Decimal
    """Amount due."""
    payment_type_id: str
    """Payment type.

    Can be obtained by `/api/1/payment_types` operation.
    """
    is_processed_externally: bool | None = None
    """Whether payment item is processed by external payment system (made from outside)."""
    payment_additional_data: PaymentAdditionalData | None = None
    """Additional payment parameters."""
    is_fiscalized_externally: bool | None = None
    """Whether the payment item is externally fiscalized.

    Allowed from version `7.6.3`.
    """
    is_prepay: bool | None = None
    """**Deprecated.** Whether the payment item is prepay. Unavailable for `paymentKindType.LoyaltyCard`.

    Allowed from version `8.2.6`.
    """


class CardTipsPayment(TipsPaymentBase):
    """Bank card tips payment."""

    __always_sent__ = ("payment_type_kind",)

    payment_type_kind: Literal["Card"] = "Card"  # pyright: ignore[reportIncompatibleVariableOverride]
    number: str | None = None
    """Card No.
    In iikoFront, it is possible to make card payment without card No.
    """


class CashPayment(PaymentBase):
    """Cash payment.

    No additional fields for base class.
    """

    __always_sent__ = ("payment_type_kind",)

    payment_type_kind: Literal["Cash"] = "Cash"  # pyright: ignore[reportIncompatibleVariableOverride]


class CashTipsPayment(TipsPaymentBase):
    """Cash tips payment.

    No additional fields for base class.
    """

    __always_sent__ = ("payment_type_kind",)

    payment_type_kind: Literal["Cash"] = "Cash"  # pyright: ignore[reportIncompatibleVariableOverride]


class ChangeExternalDataRequest(IikoModel):
    """Request for change of delivery or table order external data."""

    organization_id: str
    """Organization ID."""
    order_id: str
    """Order ID."""
    external_data: list[ExternalData]
    """External data to change."""


class ChangePaymentsRequest(IikoModel):
    """Change order's payments request."""

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    order_id: str
    """Order ID."""
    payments: list[Payment]
    """Order payments."""
    tips: list[TipsPayment] | None = None
    """Order tips."""


class ChequeAdditionalInfo(IikoModel):
    """Cheque additional information according to russian federal law #54."""

    need_receipt: bool
    """Whether paper cheque should be printed."""
    email: str | None = None
    """Email to send cheque information or null if the cheque shouldn't be sent by email."""
    settlement_place: str | None = None
    """Settlement place."""
    phone: str | None = None
    """Phone to send cheque information (by sms) or null if the cheque shouldn't be sent by sms."""
    retail_address: str | None = None
    """Retail address.

    Allowed from version `9.4.6`.
    """
    is_internet_payment: bool | None = None
    """Whether the settlement is an internet payment transaction.

    Allowed from version `9.4.6`.
    """


class Combo(IikoModel):
    """Combo in order."""

    id: str
    """Combo ID.
    MUST be unique for the whole system. Therefore it must be generated with Guid.NewGuid().
    """
    name: str
    """Name of combo."""
    amount: int
    """Quantity."""
    price: Decimal
    """Price of one combo."""
    source_id: str
    """Combo validity ID."""
    program_id: str | None = None
    """Card program ID.

    Allowed from version `7.6.1`.
    """
    size_id: str | None = None
    """Size ID. Required if combo has a size scale.

    Allowed from version `8.5.6`.
    """


class ComboItemInformation(IikoModel):
    """Combo details if order item belongs to combo"""

    combo_id: str
    """Created combo ID.
    Must be one of combos.id generated values.
    """
    combo_source_id: str
    """Action ID that defines combo."""
    combo_group_id: str
    """Combo group ID to which item belongs."""
    combo_group_name: str | None = None
    """Combo group name to which item belongs."""


class CompoundItemTemplate(IikoModel):
    """Modifier scheme information."""

    id: str
    """ID."""
    name: str
    """Name."""


class OrderItemBase(IikoModel):
    """Order item."""

    __variants__ = (
        "type",
        (
            "Product",
            "Compound",
        ),
    )

    type: str
    amount: Decimal
    """Quantity."""
    product_size_id: str | None = None
    """Size ID. Required if a stock list item has a size scale."""
    combo_information: ComboItemInformation | None = None
    """Combo details if combo includes order item."""
    comment: str | None = None
    """Comment."""


class CompoundOrderItem(OrderItemBase):
    """Order item: composite item."""

    __always_sent__ = ("type",)

    type: Literal["Compound"] = "Compound"  # pyright: ignore[reportIncompatibleVariableOverride]
    primary_component: CompoundOrderItemComponent
    """Main component."""
    secondary_component: CompoundOrderItemComponent | None = None
    """Minor component."""
    common_modifiers: list[Modifier] | None = None
    """Indivisible modifiers."""


class CompoundOrderItemComponent(IikoModel):
    """Item component"""

    product_id: str
    """Item ID."""
    modifiers: list[Modifier] | None = None
    """Modifiers."""
    price: Decimal | None = None
    """Price."""
    position_id: str | None = None
    """Unique identifier of the item in the order.
    MUST be unique for the whole system. Therefore it must be generated with Guid.NewGuid().
    If sent null, it generates automatically on iikoTransport side.
    """


class Coordinates(IikoModel):
    """Coordinate details."""

    latitude: Decimal
    """Latitude."""
    longitude: Decimal
    """Longitude."""


class CorrelationIdResponse(IikoModel):
    """Wrapping object (external) for CorrelationId return."""

    correlation_id: str
    """Operation ID."""


class CourierInfo(IikoModel):
    """Driver information."""

    courier: RetrievedEmployee
    """Order driver."""
    is_courier_selected_manually: bool
    """Whether driver is selected manually."""


class DeletionMethod(IikoModel):
    """Deletion method."""

    id: str
    """ID."""
    comment: str | None = None
    """Comment."""
    removal_type: RetrievedRemovalType
    """Write-off type."""


class DeliveriesResponseOrderPaymentType(IikoModel):
    """Payment type.

    Can be obtained by `/api/1/payment_types` operation.
    """

    id: str
    """ID."""
    name: str
    """Name."""
    kind: PaymentTypeKind
    """Payment type classifier."""


class DeliveriesResponseOrderStreet(IikoModel):
    """Street."""

    id: str
    """ID."""
    name: str
    """Name."""
    city: RetrievedCity
    """City."""


class DeliveryPoint(IikoModel):
    """Delivery location details."""

    coordinates: Coordinates | None = None
    """Delivery address coordinates.
    Allowed from version `7.7.3`.
    """
    address: Address | None = None
    """Order delivery address.

    The use of type **City** is allowed if the parameter **addressFormatType == City**.

    Can be obtained by `/api/1/organizations` or `/api/1/organizations/settings` operations (`addressFormatType` parameter).
    """
    external_cartography_id: str | None = None
    """Delivery location custom code in customer's API system."""
    comment: str | None = None
    """Additional information."""


class DeliveryStreet(IikoModel):
    """Street."""

    classifier_id: str | None = None
    """Street ID in classifier, e.g., address database.
    \\n > For using in the Russian Federation only.
    """
    id: str | None = None
    """ID.

    Can be obtained by `/api/1/streets/by_city` operation.
    """
    name: str | None = None
    """Name."""
    city: str | None = None
    """City name."""


class DiscountBase(IikoModel):
    """Discount/surcharge."""

    __variants__ = (
        "type",
        (
            "RMS",
            "iikoCard",
        ),
    )

    type: str


class DiscountCard(IikoModel):
    """Discount card."""

    track: str
    """Track of discount card to be applied to order."""


class DiscountItem(IikoModel):
    """Discount."""

    discount_type: DiscountType
    """Discount type.

    Can be obtained by `/api/1/discounts` operation.
    """
    sum: Decimal
    """Total."""
    selective_positions: list[str] | None = None
    """Order item positions."""
    selective_positions_with_sum: list[PositionWithSum] | None = None
    """Order item positions with position discount sum.

    Allowed from version `8.5.6`.
    """


class DiscountType(IikoModel):
    """Discount type."""

    id: str
    """ID."""
    name: str
    """Name."""


class DiscountsInfo(IikoModel):
    """Information on discounts/surcharges to be applied to order.

    Whether map or non-blank list of discounts must be set.
    """

    card: DiscountCard | None = None
    """Track of discount card to be applied to order."""
    discounts: list[Discount] | None = None
    """Discounts/surcharges.

    Type **iikoCard** allowed from version `7.4.4`.
    """
    fixed_loyalty_discounts: bool | None = None
    """Whether loyalty discounts should be fixed."""


class DynamicDiscount(IikoModel):
    """Dynamic discount."""

    manual_condition_id: str
    """Applied manual condition ID."""
    sum: Decimal
    """Discount sum."""


class ErrorInfo(IikoModel):
    """DTO for error details transfer."""

    code: ErrorCode
    """Error code."""
    message: str | None = None
    """Localized message."""
    description: str | None = None
    """**Deprecated.** Localized message."""
    additional_data: Any | None = None
    """Additional information."""
    error_reason: str | None = None
    """Error reason."""


class OrganizationInfoBase(IikoModel):
    """Organization details."""

    __always_sent__ = ("name",)

    __variants__ = (
        "response_type",
        (
            "Simple",
            "Extended",
        ),
    )

    response_type: str
    id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    name: str | None = None
    """Organization name."""
    code: str | None = None
    """Organization`s code."""
    external_data: list[ExternalDataEntry] | None = None
    """Organization`s external data."""


class ExtendedOrganizationInfo(OrganizationInfoBase):
    """Organization details."""

    __always_sent__ = (
        "country",
        "restaurant_address",
        "currency_iso_name",
        "currency_minimum_denomination",
        "country_phone_code",
        "marketing_source_required_in_delivery",
        "default_delivery_city_id",
        "delivery_city_ids",
        "delivery_service_type",
        "default_call_center_payment_type_id",
        "order_item_comment_enabled",
        "inn",
        "is_confirmation_enabled",
        "confirm_allowed_interval_in_minutes",
        "response_type",
    )

    response_type: Literal["Extended"] = "Extended"  # pyright: ignore[reportIncompatibleVariableOverride]
    country: str | None = None
    """Country."""
    restaurant_address: str | None = None
    """Restaurant address."""
    latitude: Decimal
    """Latitude."""
    longitude: Decimal
    """Longitude."""
    use_uae_addressing_system: bool
    """Regional setting "Use the UAE Addressing System"."""
    version: str
    """RMS version."""
    currency_iso_name: str | None = None
    """ISO currency code (for example: RUB, USD, EUR)."""
    currency_minimum_denomination: Decimal | None = None
    """Value rounding of position."""
    country_phone_code: str | None = None
    """Country dialing code."""
    marketing_source_required_in_delivery: bool | None = None
    """Require mandatory marketing source input when creating a delivery."""
    default_delivery_city_id: str | None = None
    """Default delivery city."""
    delivery_city_ids: list[str] | None = None
    """Delivery cities."""
    delivery_service_type: DeliverySettingsServiceType | None = None
    """Delivery type."""
    delivery_order_payment_settings: DeliveryOrderPaymentSettings | None = None
    """Delivery order payment settings."""
    default_call_center_payment_type_id: str | None = None
    """Default payment type for CallCenter."""
    order_item_comment_enabled: bool | None = None
    """Allow text comments for order items (in all restaurant sections)."""
    inn: str | None = None
    """Restaurant`s INN (Taxpayer Identification Number)."""
    address_format_type: AddressFormatType
    """Address format type."""
    is_confirmation_enabled: bool | None = None
    """Determines whether to use delivery confirmation."""
    confirm_allowed_interval_in_minutes: int | None = None
    """Confirm orders time interval."""
    is_cloud: bool
    """Determines whether organization is hosted in iikoCloud."""
    is_anonymous_guests_allowed: bool | None = None
    """If the store allows orders for anonymous guests, then it is not necessary to transfer
    information about the guest as part of the delivery order. You can only transfer
    the phone number and optionally name of the guest, which will not be stored in the guest base
    and will only be used for the delivery of a current delivery order.
    """
    address_lookup: list[AddressHintsServiceType]
    """Available address lookup services."""


class ExternalCourierService(IikoModel):
    """ECS info (external courier service)."""

    id: str
    """ECS setting record id. Unique through all organizations."""
    name: str
    """ECS name."""


class ExternalData(IikoModel):
    """Order external data."""

    key: str
    """Key."""
    value: str
    """Value."""
    is_public: bool | None = None
    """The transmitted data may contain both technical identifiers and information useful for the restaurant employee.
    If it is necessary for the data to be included in the sales report, then this parameter must be set to TRUE, otherwise to FALSE.
    """


class ExternalDataEntry(IikoModel):
    """External data key and value pair."""

    key: str
    """External data key."""
    value: str
    """External data value."""


class ExternalPayment(PaymentBase):
    """External payment type"""

    __always_sent__ = ("payment_type_kind",)

    payment_type_kind: Literal["External"] = "External"  # pyright: ignore[reportIncompatibleVariableOverride]


class ExternalPaymentAdditionalData(PaymentAdditionalDataBase):
    """Additional data for external payment item."""

    __always_sent__ = ("type",)

    type: Literal["External"] = "External"  # pyright: ignore[reportIncompatibleVariableOverride]
    custom_data: str
    """Payment custom data."""


class ExternalTipsPayment(TipsPaymentBase):
    """External tips payment type"""

    __always_sent__ = ("payment_type_kind",)

    payment_type_kind: Literal["External"] = "External"  # pyright: ignore[reportIncompatibleVariableOverride]


class FilterCondition(IikoModel):
    """FilterCondition."""

    field: str | None = None
    """Field name for filtering"""
    op: str | None = None
    """Operation ("eq", "ne", "gt", "gte", "lt", "lte", "in", "nin", "like", "blank", "notblank")"""
    value: Any | None = None
    """Value for filtering by the field"""


class GetByIDRequest(IikoModel):
    """GetByIDRequest."""

    document_id: str
    """Document identifier (GUID)"""
    organization_id: str
    """Organization identifier (GUID)"""


class GetOrganizationsRequest(IikoModel):
    """Request for organizations."""

    organization_ids: list[str] | None = None
    """Organizations IDs which have to be returned. By default - all organizations from apiLogin.

    Can be obtained by `/api/1/organizations` operation.
    """
    return_additional_info: bool | None = None
    """A sign whether additional information about the organization should be returned (RMS version, country, restaurantAddress, etc.),
    or only minimal information should be returned (id and name).
    """
    include_disabled: bool | None = None
    """Attribute that shows that response contains disabled organizations."""
    return_external_data: list[str] | None = None
    """External data keys that have to be returned."""


class GetOrganizationsResponse(IikoModel):
    """Response to request for organizations."""

    correlation_id: str
    """Operation ID."""
    organizations: list[OrganizationInfo]
    """List of organizations.

    Can be obtained by `/api/1/organizations` operation.
    """


class Guests(IikoModel):
    """Information on guests."""

    count: int
    """Number of persons in order. This field defines the number of cutlery sets"""
    split_between_persons: bool | None = None
    """Attribute that shows whether order must be split among guests."""


class IdentifierCode(IikoModel):
    """Product code."""

    value: str | None = None
    """Product code value."""


class IikoCardDiscount(DiscountBase):
    """Card discount/surcharge."""

    __always_sent__ = ("type",)

    type: Literal["iikoCard"] = "iikoCard"  # pyright: ignore[reportIncompatibleVariableOverride]
    program_id: str
    """Card program ID."""
    program_name: str
    """Card program name."""
    discount_items: list[IikoCardDiscountItem]
    """Discount information for order items."""


class IikoCardDiscountItem(IikoModel):
    """Card discount/surcharge item."""

    position_id: str
    """Position ID of order item."""
    sum: Decimal
    """Discount/surcharge sum."""
    amount: Decimal
    """Amount."""


class ItemDeletedInfo(IikoModel):
    """Order cancellation details."""

    deletion_method: DeletionMethod
    """Deletion method."""


class ListRequest(IikoModel):
    """ListRequest."""

    from_: str = Field(alias="from")
    """Period start date (YYYY-MM-DD format)"""
    organization_id: str
    """Organization identifier (GUID)"""
    to: str
    """Period end date (YYYY-MM-DD format)"""


class LoyaltyCardPayment(PaymentBase):
    """Payment with Card loyalty system."""

    __always_sent__ = ("payment_type_kind",)

    payment_type_kind: Literal["LoyaltyCard"] = "LoyaltyCard"  # pyright: ignore[reportIncompatibleVariableOverride]


class LoyaltyCardPaymentAdditionalData(PaymentAdditionalDataBase):
    """Additional data for LoyaltyApp payment item."""

    __always_sent__ = ("type",)

    type: Literal["LoyaltyCard"] = "LoyaltyCard"  # pyright: ignore[reportIncompatibleVariableOverride]
    credential: str
    """Guest credential, authorizing payment."""
    search_scope: IikoCardSearchScope
    """Guest credential search scope."""


class LoyaltyInfo(IikoModel):
    """Information about Loyalty app."""

    coupon: str | None = None
    """Coupon No. that was considered when calculating loyalty program."""
    applicable_manual_conditions: list[str] | None = None
    """Information about applied manual conditions."""
    dynamic_discounts: list[DynamicDiscount] | None = None
    """Dynamic discounts.

    Allowed from version `9.4.6`.
    """


class Modifier(IikoModel):
    """Modifier."""

    product_id: str
    """Modifier item ID.

    Can be obtained by `/api/1/nomenclature` operation.
    """
    amount: Decimal
    """Quantity."""
    product_group_id: str | None = None
    """Modifiers group ID (for group modifier). Required for a group modifier.

    Can be obtained by `/api/1/nomenclature` operation.
    """
    price: Decimal | None = None
    """Unit price."""
    position_id: str | None = None
    """Unique identifier of the item in the order.
    MUST be unique for the whole system. Therefore it must be generated with Guid.NewGuid().
    If sent null, it generates automatically on iikoTransport side.
    """


class OrderCombo(IikoModel):
    """Combo in order."""

    id: str
    """Combo ID."""
    name: str
    """Name of combo."""
    amount: int
    """Number of combos."""
    price: Decimal
    """Price of combo. Given for 1 combo, without regard to amount."""
    source_id: str
    """Combo action ID."""
    size: RetrievedProductSize | None = None
    """Size."""


class OrderInfo(IikoModel):
    """Order."""

    id: str
    """Delivery order ID."""
    pos_id: str | None = None
    """POS delivery order ID."""
    external_number: str | None = None
    """Order external number."""
    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    timestamp: int
    """Timestamp of most recent order change that took place on iikoTransport server."""
    creation_status: CreationStatus
    """Order creation status. In case of asynchronous creation, it allows to track the instance an order was validated/created in iikoFront."""
    error_info: ErrorInfo | None = None
    """Order creation error details.
    Required only if "creationStatus"="Error".
    """
    order: RetrievedOrder | None = None
    """Order creation details.
    Field is filled up if "creationStatus"="Success".
    """


class OrderItemIdentifierCode(IikoModel):
    """OrderItem's IdentifierCode."""

    id: str
    """Id of order's position."""
    code: IdentifierCode
    """Product code."""
    flags: list[str]
    """Application flags."""


class OrderItemModifier(IikoModel):
    """Order item modifier."""

    product: RetrievedProduct
    """Item."""
    amount: Decimal
    """Quantity."""
    amount_independent_of_parent_amount: bool
    """Whether quantity of modifier depends on quantity of item."""
    codes: list[list[OrderItemIdentifierCode]] | None = None
    """List of product codes. Each outer list item represents a separate product unit;
    each inner list contains codes associated with that unit.

    Allowed from version `9.3.6`.
    """
    product_group: ProductGroup | None = None
    """Group of modifiers (in case of a group modifier)."""
    price: Decimal
    """Price per item unit. Can be sent different from the price in RMS."""
    price_predefined: bool
    """Whether price is predefined."""
    result_sum: Decimal
    """Total amount per item including tax, discounts/surcharges."""
    deleted: ItemDeletedInfo | None = None
    """Item deletion details. If specified, the item is deleted."""
    position_id: str | None = None
    """Unique identifier of the item in the order and for the whole system."""
    default_amount: int | None = None
    """Default amount."""
    hide_if_default_amount: bool | None = None
    """Hide modifier in UI if "amount" equals "defaultAmount"."""
    tax_percent: Decimal | None = None
    """Tax rate."""
    free_of_charge_amount: int | None = None
    """Free of charge amount."""


class PaymentItem(IikoModel):
    """Delivery order payment component."""

    payment_type: DeliveriesResponseOrderPaymentType
    """Payment type.

    Can be obtained by `/api/1/payment_types` operation.
    """
    sum: Decimal
    """Amount due."""
    is_preliminary: bool
    """Whether payment item is preliminary."""
    is_external: bool
    """Payment item is external (created via biz.API)."""
    is_processed_externally: bool
    """Payment item is processed by external payment system."""
    is_fiscalized_externally: bool | None = None
    """Whether the payment item is externally fiscalized.

    Allowed from version `7.6.3`.
    """
    is_prepay: bool
    """Whether the payment item is prepay.

    Allowed from version `7.7.6`.
    """


class PositionWithSum(IikoModel):
    """Order item positions with position discount sum."""

    position_id: str
    """Order item position ID."""
    sum: Decimal
    """Position discount sum."""


class PriceCategory(IikoModel):
    """Price category of the order."""

    id: str
    """Id of price category."""
    name: str | None = None
    """Name of price category."""


class Problem(IikoModel):
    """Order problem details."""

    has_problem: bool
    """Has problem."""
    description: str | None = None
    """Problem description."""


class ProductGroup(IikoModel):
    """Item category."""

    id: str
    """ID."""
    name: str
    """Name."""


class ProductOrderItem(OrderItemBase):
    """Order item: item."""

    __always_sent__ = ("type",)

    type: Literal["Product"] = "Product"  # pyright: ignore[reportIncompatibleVariableOverride]
    product_id: str
    """ID of menu item.

    Can be obtained by `/api/1/nomenclature` operation.
    """
    modifiers: list[Modifier] | None = None
    """Modifiers."""
    price: Decimal
    """Price per item unit. Can be sent different from the price in the base menu."""
    position_id: str | None = None
    """Unique identifier of the item in the order.
    MUST be unique for the whole system. Therefore it must be generated with Guid.NewGuid().
    If sent null, it generates automatically on iikoTransport side.
    """


class RegularCustomer(CustomerBase):
    """'Regular' customer:
    - can be used only if a customer agrees to take part in the store's loyalty programs
    - customer details will be added (updated) to the store's customer database
    - benefits (accumulation of rewards, etc.) of active loyalty programs will be made available to the customer
    """

    __always_sent__ = ("type",)

    type: Literal["regular"] = "regular"  # pyright: ignore[reportIncompatibleVariableOverride]
    id: str | None = None
    """Existing customer ID in RMS.
    If null - the phone number is searched in database, otherwise the new customer is created in RMS.
    """
    name: str | None = None
    """Name of customer.
    Required for new customers (i.e. if "id" == null)
    Not required if "id" specified.
    """
    surname: str | None = None
    """Last name."""
    comment: str | None = None
    """Comment."""
    birthdate: IikoDateTime | None = None
    """Date of birth."""
    email: str | None = None
    """Email."""
    should_receive_promo_actions_info: bool | None = None
    """**Deprecated.** Deprecated, use "shouldReceiveOrderStatusNotifications" instead."""
    should_receive_order_status_notifications: bool | None = None
    """Whether customer receives order status notification messages."""
    gender: Gender | None = None
    """Gender."""


class Reserve(IikoModel):
    """Banquet/reserve."""

    customer: RetrievedCustomer
    """Client that placed the reserve."""
    guests_count: int
    """Estimated guests count."""
    comment: str | None = None
    """Optional comment for reserve or banquet."""
    duration_in_minutes: int
    """Estimated banquet duration."""
    should_remind: bool
    """Whether to remind staff to prepare table beforehand."""
    status: ReserveStatus
    """Status of the reserve or banquet."""
    cancel_reason: ReserveCancelReason | None = None
    """The reserve cancellation reason or null if the reserve hasn't been canceled."""
    table_ids: list[str]
    """Reserved table IDs."""
    estimated_start_time: IikoDateTime
    """Estimated time when reserve will be closed or banquet will be started."""
    guests_coming_time: IikoDateTime | None = None
    """Time when guests came and reserve was closed or banquet was started."""
    phone: str | None = None
    """Telephone number."""
    event_type: str | None = None
    """Event type.

    Allowed from version `8.5.6`.
    """
    order: RetrievedReserveOrder | None = None
    """Order. Used only at a banquet."""


class ReserveInfo(IikoModel):
    """Banquet/reserve."""

    id: str
    """Banquet/reserve ID."""
    external_number: str | None = None
    """Banquet/reserve external number."""
    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    timestamp: int
    """Timestamp of most recent banquet/reserve change that took place on iikoTransport server."""
    creation_status: CreationStatus
    """Banquet/reserve creation status. In case of asynchronous creation, it allows to track the instance an banquet/reserve was validated/created in iikoFront."""
    error_info: ErrorInfo | None = None
    """Banquet/reserve creation error details.
    Required only if "creationStatus"="Error".
    """
    is_deleted: bool
    """Banquet/reserve is deleted."""
    reserve: Reserve | None = None
    """Banquet/reserve."""


class RetrievedAddress(IikoModel):
    """Address details."""

    __always_sent__ = ("region",)

    street: DeliveriesResponseOrderStreet | None = None
    """Street."""
    index: str | None = None
    """Postcode."""
    house: str | None = None
    """House."""
    building: str | None = None
    """Building."""
    flat: str | None = None
    """Apartment."""
    entrance: str | None = None
    """Entrance."""
    floor: str | None = None
    """Floor."""
    doorphone: str | None = None
    """Intercom."""
    region: RetrievedRegion | None = None
    """Region"""
    line1: str | None = None
    """Address line 1.
    Contains the primary address information.
    """


class RetrievedCustomerBase(IikoModel):
    """Delivery customer."""

    __variants__ = (
        "type",
        (
            "regular",
            "one-time",
        ),
    )

    type: str


class RetrievedAnonymousCustomer(RetrievedCustomerBase):
    """'One-time' customer:
    - should be used if a customer does not agree to take part in the store's loyalty programs or an aggregator (external system) does not provide customer details
    - customer details will NOT be added to the store's customer database and will be used ONLY to complete the current order
    """

    __always_sent__ = ("type",)

    type: Literal["one-time"] = "one-time"  # pyright: ignore[reportIncompatibleVariableOverride]
    name: str
    """Customer name."""


class RetrievedCancelCause(IikoModel):
    """Delivery cancellation reason."""

    id: str
    """ID."""
    name: str
    """Description."""


class RetrievedCity(IikoModel):
    """City."""

    id: str
    """ID."""
    name: str
    """Name."""


class RetrievedComboItemInformation(IikoModel):
    """Information on order item to combo relation."""

    combo_id: str
    """New combo ID."""
    combo_source_id: str
    """Action ID that defines combo."""
    group_id: str
    """Combo group ID to which item belongs."""
    group_name: str | None = None
    """Combo group name to which item belongs."""


class RetrievedOrderItemBase(IikoModel):
    """Order item."""

    __variants__ = (
        "type",
        (
            "Product",
            "Compound",
            "Service",
        ),
    )

    type: str
    status: OrderItemStatus
    """Item cooking status."""
    deleted: ItemDeletedInfo | None = None
    """Item deletion details. If filled up, item is deleted."""
    amount: Decimal
    """Quantity."""
    comment: str | None = None
    """Comment."""
    when_printed: IikoDateTime | None = None
    """Printing time (Local for the terminal)."""
    size: RetrievedProductSize | None = None
    """Size."""
    combo_information: RetrievedComboItemInformation | None = None
    """Combo details, if order item is part of combo."""


class RetrievedCompoundOrderItem(RetrievedOrderItemBase):
    """Order item: composite item."""

    __always_sent__ = ("type",)

    type: Literal["Compound"] = "Compound"  # pyright: ignore[reportIncompatibleVariableOverride]
    primary_component: RetrievedCompoundOrderItemComponent
    """Main component."""
    secondary_component: RetrievedCompoundOrderItemComponent | None = None
    """Additional component."""
    common_modifiers: list[OrderItemModifier] | None = None
    """Indivisible modifiers."""
    template: CompoundItemTemplate | None = None
    """Modifier scheme."""


class RetrievedCompoundOrderItemComponent(IikoModel):
    """Part of composite item."""

    product: RetrievedProduct
    """Item."""
    modifiers: list[OrderItemModifier] | None = None
    """Modifiers."""
    price: Decimal
    """Price per item unit. Can be sent different from the price in the base menu."""
    cost: Decimal
    """Item total including tax, discounts/surcharges."""
    price_predefined: bool
    """Whether price is predefined."""
    position_id: str | None = None
    """Unique identifier of the item in the order and for the whole system."""
    tax_percent: Decimal | None = None
    """Tax rate."""
    result_sum: Decimal | None = None
    """Total amount per item including tax, discounts/surcharges."""


class RetrievedConception(IikoModel):
    """Concept."""

    id: str
    """ID."""
    name: str
    """Name."""
    code: str
    """Code."""


class RetrievedDeliveryPoint(IikoModel):
    """Delivery address coordinates."""

    coordinates: Coordinates | None = None
    """Delivery address coordinates."""
    address: RetrievedAddress | None = None
    """Delivery address details."""
    external_cartography_id: str | None = None
    """Address ID in external mapping system."""
    comment: str | None = None
    """Comment."""


class RetrievedDynamicDiscount(IikoModel):
    """Dynamic discount."""

    manual_condition_id: str
    """Applied manual condition ID."""
    sum: Decimal
    """Discount sum."""


class RetrievedEmployee(IikoModel):
    """Employee."""

    id: str
    """ID."""
    name: str
    """Name."""
    phone: str | None = None
    """Phone."""


class RetrievedExternalData(IikoModel):
    """Order external data."""

    key: str
    """Key."""
    value: str
    """Public."""


class RetrievedGuestsInfo(IikoModel):
    """Information about order guests."""

    count: int
    """Number of persons."""
    split_between_persons: bool
    """Attribute that shows whether order must be split among guests."""


class RetrievedLoyaltyInfo(IikoModel):
    """Information about Loyalty app."""

    coupon: str | None = None
    """Coupon No. that was considered when calculating loyalty program."""
    applied_manual_conditions: list[str] | None = None
    """Information about applied manual conditions."""
    dynamic_discounts: list[RetrievedDynamicDiscount] | None = None
    """Dynamic discounts.

    Allowed from version `9.4.6`.
    """


class RetrievedMarketingSource(IikoModel):
    """Marketing source."""

    id: str
    """ID."""
    name: str
    """Name."""


class RetrievedOrder(IikoModel):
    """Order details."""

    __always_sent__ = (
        "guests_info",
        "order_type",
        "processed_payments_sum",
    )

    parent_delivery_id: str | None = None
    """ID of delivery serving as source for splitting by FCRs."""
    customer: RetrievedCustomer | None = None
    """Delivery customer."""
    phone: str
    """Delivery phone number."""
    phone_extension: str | None = None
    """Extension delivery phone number."""
    delivery_point: RetrievedDeliveryPoint | None = None
    """Delivery point details.

    Not required if order type is customer pickup. Otherwise, required.
    """
    status: DeliveryStatus
    """Delivery status.

    Delivery status `ReadyForCooking` is deprecated from version `9.0.6`.
    """
    cancel_info: CancelInfo | None = None
    """Delivery cancellation details.

    Required only if delivery is canceled, i.e. status=Canceled.
    """
    courier_info: CourierInfo | None = None
    """Driver information."""
    complete_before: IikoDateTime
    """Order fulfillment time (Local for the terminal)."""
    when_created: IikoDateTime
    """Delivery creation time in iikoFront (Local for the terminal)."""
    when_confirmed: IikoDateTime | None = None
    """Delivery confirmation time (Local for the terminal)."""
    when_printed: IikoDateTime | None = None
    """Service printing time (Local for the terminal)."""
    when_cooking_completed: IikoDateTime | None = None
    """Cooking completion time (Local for the terminal)."""
    when_sended: IikoDateTime | None = None
    """Delivery dispatch time (Local for the terminal)."""
    when_delivered: IikoDateTime | None = None
    """Actual delivery time (Local for delivery terminal)."""
    comment: str | None = None
    """Order comment."""
    problem: Problem | None = None
    """Problem flag."""
    operator: RetrievedEmployee | None = None
    """Operator that took order."""
    marketing_source: RetrievedMarketingSource | None = None
    """Marketing source."""
    delivery_duration: int | None = None
    """Duration of delivery (in minutes)."""
    index_in_courier_route: int | None = None
    """Ordinal number in route list.

    Field is filled up at the time of delivery allocation by logistics in iikoFront.
    If logistics is not in use, the field is not filled up.
    """
    cooking_start_time: IikoDateTime
    """The time when you need to start cooking an order (Local for the terminal)."""
    is_deleted: bool | None = None
    """**Deprecated.** Order is deleted."""
    when_received_by_api: IikoDateTime | None = None
    """**Deprecated.** Moment of time when CloudAPI received the request to create the order (UTC)."""
    when_received_from_front: IikoDateTime | None = None
    """**Deprecated.** Moment of time when the order first received and saved from iikoFront (UTC)."""
    moved_from_delivery_id: str | None = None
    """Tells that this delivery has been moved from terminal group
    with id *MovedFromTerminalGroupId* by cancelling delivery with deliveryId *MovedFromDeliveryId*.

    Allowed from version `7.5.4`.
    """
    moved_from_terminal_group_id: str | None = None
    """Tells that this delivery has been moved from terminal group
    with id *MovedFromTerminalGroupId* by cancelling delivery with deliveryId *MovedFromDeliveryId*.

    Allowed from version `7.5.4`.
    """
    moved_from_organization_id: str | None = None
    """Tells that this delivery has been moved from terminal group
    with id *MovedFromTerminalGroupId* by cancelling delivery with deliveryId *MovedFromDeliveryId*.

    Allowed from version `7.5.4`.
    """
    external_courier_service: ExternalCourierService | None = None
    """ECS info.

    Allowed from version `7.7.7`.
    """
    moved_to_delivery_id: str | None = None
    """Tells that this delivery has been canceled and moved to terminal group
    with id *MovedToTerminalGroupId*.
    """
    moved_to_terminal_group_id: str | None = None
    moved_to_organization_id: str | None = None
    menu_id: str | None = None
    """External menu ID."""
    delivery_zone: str | None = None
    """Name of delivery zone."""
    locked_at: IikoDateTime | None = None
    """Timestamp of when the order was taken for editing (lock)."""
    estimated_time: IikoDateTime | None = None
    """Delivery estimated time."""
    is_asap: bool | None = None
    """Whether to deliver as soon as possible."""
    when_packed: IikoDateTime | None = None
    """Delivery packing time (Local for the terminal)."""
    price_category: PriceCategory | None = None
    """Price category of the order.

    Allowed from version `9.0.5`.
    """
    tracking_link: str | None = None
    """Order's tracking link."""
    sum: Decimal
    """Order amount (after discount or surcharge)."""
    number: int
    """Delivery No."""
    source_key: str | None = None
    """Delivery source."""
    when_bill_printed: IikoDateTime | None = None
    """Invoice printing time (guest bill time)."""
    when_closed: IikoDateTime | None = None
    """Delivery closing time (Local for delivery terminal)."""
    conception: RetrievedConception | None = None
    """Concept."""
    guests_info: RetrievedGuestsInfo | None = None
    """Information about order guests."""
    items: list[RetrievedOrderItem]
    """Order items."""
    combos: list[OrderCombo] | None = None
    """Combo."""
    payments: list[PaymentItem] | None = None
    """Payments."""
    tips: list[TipsPaymentItem] | None = None
    """Tips."""
    discounts: list[DiscountItem] | None = None
    """Discounts."""
    order_type: RetrievedOrderType | None = None
    """Order type."""
    terminal_group_id: str
    """ID of the terminal group where the order is located."""
    processed_payments_sum: Decimal | None = None
    """The amount of processed payments.

    null - only for unsupported POS versions.

    Allowed from version `7.6.0`.
    """
    loyalty_info: RetrievedLoyaltyInfo | None = None
    """Information about Loyalty app.

    null - only for unsupported POS versions.
    """
    external_data: list[RetrievedExternalData] | None = None
    """Order external data.

    Allowed from version `8.0.6`.
    """


class RetrievedOrderType(IikoModel):
    """Order type."""

    id: str
    """ID."""
    name: str
    """Name."""
    order_service_type: OrderServiceType
    """Order type."""


class RetrievedProduct(IikoModel):
    """Item."""

    id: str
    """ID."""
    name: str
    """Name."""


class RetrievedProductOrderItem(RetrievedOrderItemBase):
    """Order item: item."""

    __always_sent__ = ("type",)

    type: Literal["Product"] = "Product"  # pyright: ignore[reportIncompatibleVariableOverride]
    product: RetrievedProduct
    """Item."""
    modifiers: list[OrderItemModifier] | None = None
    """Modifiers."""
    codes: list[list[OrderItemIdentifierCode]] | None = None
    """List of product codes. Each outer list item represents a separate product unit;
    each inner list contains codes associated with that unit.

    Allowed from version `9.2.6`.
    """
    price: Decimal
    """Price per item unit. Can be sent different from the price in the base menu."""
    cost: Decimal
    """Total cost per item without tax, discounts/surcharges."""
    price_predefined: bool
    """Whether price is predefined."""
    position_id: str | None = None
    """Unique identifier of the item in the order and for the whole system."""
    tax_percent: Decimal | None = None
    """Tax rate."""
    result_sum: Decimal | None = None
    """Total amount per item including tax, discounts/surcharges."""


class RetrievedProductSize(IikoModel):
    """Item size."""

    id: str
    """ID."""
    name: str
    """Name."""


class RetrievedRegion(IikoModel):
    """Delivery district (part of delivery address)."""

    id: str
    """ID."""
    name: str
    """Name."""


class RetrievedRegularCustomer(RetrievedCustomerBase):
    """RetrievedRegularCustomer."""

    __always_sent__ = ("type",)

    type: Literal["regular"] = "regular"  # pyright: ignore[reportIncompatibleVariableOverride]
    id: str
    """Customer ID."""
    name: str
    """Name."""
    surname: str | None = None
    """Last name."""
    comment: str | None = None
    """Comment."""
    gender: Gender | None = None
    """Sex."""
    in_blacklist: bool | None = None
    """Is client in blacklist."""
    blacklist_reason: str | None = None
    """Reason why client was added to blacklist."""
    birthdate: IikoDateTime | None = None
    """Date of birth.

    Allowed from version `7.6.1`.
    """


class RetrievedRemovalType(IikoModel):
    """Write-off type."""

    id: str
    """ID."""
    name: str
    """Name."""


class RetrievedReserveOrder(IikoModel):
    """Order."""

    __always_sent__ = (
        "guests_info",
        "order_type",
        "processed_payments_sum",
    )

    menu_id: str | None = None
    """External menu ID."""
    sum: Decimal
    """Order amount (after discount or surcharge)."""
    number: int
    """Delivery No."""
    source_key: str | None = None
    """Delivery source."""
    when_bill_printed: IikoDateTime | None = None
    """Invoice printing time (guest bill time)."""
    when_closed: IikoDateTime | None = None
    """Delivery closing time (Local for delivery terminal)."""
    conception: RetrievedConception | None = None
    """Concept."""
    guests_info: RetrievedGuestsInfo | None = None
    """Information about order guests."""
    items: list[RetrievedOrderItem]
    """Order items."""
    combos: list[OrderCombo] | None = None
    """Combo."""
    payments: list[PaymentItem] | None = None
    """Payments."""
    tips: list[TipsPaymentItem] | None = None
    """Tips."""
    discounts: list[DiscountItem] | None = None
    """Discounts."""
    order_type: RetrievedOrderType | None = None
    """Order type."""
    terminal_group_id: str
    """ID of the terminal group where the order is located."""
    processed_payments_sum: Decimal | None = None
    """The amount of processed payments.

    null - only for unsupported POS versions.

    Allowed from version `7.6.0`.
    """
    loyalty_info: RetrievedLoyaltyInfo | None = None
    """Information about Loyalty app.

    null - only for unsupported POS versions.
    """
    external_data: list[RetrievedExternalData] | None = None
    """Order external data.

    Allowed from version `8.0.6`.
    """


class RetrievedTableOrder(IikoModel):
    """Order."""

    __always_sent__ = (
        "guests_info",
        "order_type",
        "processed_payments_sum",
    )

    table_ids: list[str]
    """Table IDs.

    Can be obtained by `/api/1/reserve/available_restaurant_sections` operation.
    """
    customer: RetrievedRegularCustomer | None = None
    """Guest.

    Allowed from version `7.5.2`.
    """
    phone: str | None = None
    """Guest phone.

    Allowed from version `7.5.2`.
    """
    status: RetrievedOrderStatus
    """Order status."""
    when_created: IikoDateTime | None = None
    """Order creation date (terminal time zone)."""
    waiter: RetrievedEmployee | None = None
    """Order waiter."""
    tab_name: str | None = None
    """Tab name (only for fastfood terminals group in tab mode)."""
    split_order_between_cash_registers: SplitOrderBetweenCashRegisters | None = None
    """Need to split order between cash registers.

    Not empty for orders in statuses New or Bill.
    """
    menu_id: str | None = None
    """External menu ID."""
    price_category: PriceCategory | None = None
    """Price Category of the order.

    Allowed from version `9.0.5`.
    """
    sum: Decimal
    """Order amount (after discount or surcharge)."""
    number: int
    """Delivery No."""
    source_key: str | None = None
    """Delivery source."""
    when_bill_printed: IikoDateTime | None = None
    """Invoice printing time (guest bill time)."""
    when_closed: IikoDateTime | None = None
    """Delivery closing time (Local for delivery terminal)."""
    conception: RetrievedConception | None = None
    """Concept."""
    guests_info: RetrievedGuestsInfo | None = None
    """Information about order guests."""
    items: list[RetrievedOrderItem]
    """Order items."""
    combos: list[OrderCombo] | None = None
    """Combo."""
    payments: list[PaymentItem] | None = None
    """Payments."""
    tips: list[TipsPaymentItem] | None = None
    """Tips."""
    discounts: list[DiscountItem] | None = None
    """Discounts."""
    order_type: RetrievedOrderType | None = None
    """Order type."""
    terminal_group_id: str
    """ID of the terminal group where the order is located."""
    processed_payments_sum: Decimal | None = None
    """The amount of processed payments.

    null - only for unsupported POS versions.

    Allowed from version `7.6.0`.
    """
    loyalty_info: RetrievedLoyaltyInfo | None = None
    """Information about Loyalty app.

    null - only for unsupported POS versions.
    """
    external_data: list[RetrievedExternalData] | None = None
    """Order external data.

    Allowed from version `8.0.6`.
    """


class RetrievedTipsType(IikoModel):
    """The tips type."""

    id: str
    """Tips type ID.

    Can be obtained by `/api/1/tips_types` operation.
    """
    name: str
    """Tips type name."""


class RmsDiscount(DiscountBase):
    """RMS discount/surcharge.

    Amount must be specified only if discount has "assign amount" setting enabled.
    In any other case, amount must not be specified.
    """

    __always_sent__ = ("type",)

    type: Literal["RMS"] = "RMS"  # pyright: ignore[reportIncompatibleVariableOverride]
    discount_type_id: str
    """Discount type.

    Can be obtained by `/api/1/discounts` operation.
    """
    sum: Decimal | None = None
    """Discount/surcharge sum."""
    selective_positions: list[str] | None = None
    """Order item positions."""


class ServiceOrderItem(RetrievedOrderItemBase):
    """Order item: service."""

    __always_sent__ = ("type",)

    type: Literal["Service"] = "Service"  # pyright: ignore[reportIncompatibleVariableOverride]
    service: RetrievedProduct
    """Item."""
    cost: Decimal
    """Total cost per item without tax, discounts/surcharges."""


class SimpleOrganizationInfo(OrganizationInfoBase):
    """Organization details."""

    __always_sent__ = ("response_type",)

    response_type: Literal["Simple"] = "Simple"  # pyright: ignore[reportIncompatibleVariableOverride]


class TableOrderInfo(IikoModel):
    """Order."""

    id: str
    """Order ID."""
    pos_id: str | None = None
    """POS order ID."""
    external_number: str | None = None
    """Order external number."""
    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    timestamp: int
    """Timestamp of most recent order change that took place on iikoTransport server."""
    creation_status: CreationStatus
    """Order creation status. In case of asynchronous creation, it allows to track the instance an order was validated/created in iikoFront."""
    error_info: ErrorInfo | None = None
    """Order creation error details.
    Required only if "creationStatus"="Error".
    """
    order: RetrievedTableOrder | None = None
    """Order creation details.
    Field is filled up if "creationStatus"="Success".
    """


class TerminalGroup(IikoModel):
    """DTO containing terminal groups details"""

    __always_sent__ = ("address",)

    id: str
    """Delivery group ID.

    Can be obtained by `/api/1/terminal_groups` operation.
    """
    organization_id: str
    """Organization ID to which delivery group belongs.

    Can be obtained by `/api/1/organizations` operation.
    """
    name: str
    """Terminal group name."""
    address: str | None = None
    """**Deprecated.** Group address. Not used."""
    time_zone: str
    """Terminal group time zone."""
    external_data: list[ExternalDataEntry] | None = None
    """Terminal group external data."""
    pos_version: str | None = None
    """Version of the iikoFront."""


class TerminalGroupsResponse(IikoModel):
    """DTO containing terminal groups details."""

    correlation_id: str
    """Operation ID."""
    terminal_groups: list[OrganizationItems[TerminalGroup]]
    """List of terminal groups broken down by organizations."""
    terminal_groups_in_sleep: list[OrganizationItems[TerminalGroup]]
    """Terminal groups are in sleep mode because they are not active.

    Can be awakened by `/api/1/terminal_groups/awake` operation.
    """


class TipsPaymentItem(IikoModel):
    """Delivery order tips payment component."""

    tips_type: RetrievedTipsType | None = None
    """Tips type."""
    payment_type: DeliveriesResponseOrderPaymentType
    """Payment type.

    Can be obtained by `/api/1/payment_types` operation.
    """
    sum: Decimal
    """Amount due."""
    is_preliminary: bool
    """Whether payment item is preliminary."""
    is_external: bool
    """Payment item is external (created via biz.API)."""
    is_processed_externally: bool
    """Payment item is processed by external payment system."""
    is_fiscalized_externally: bool | None = None
    """Whether the payment item is externally fiscalized.

    Allowed from version `7.6.3`.
    """
    is_prepay: bool
    """Whether the payment item is prepay.

    Allowed from version `7.7.6`.
    """


class WarningInfo(IikoModel):
    """Warning info."""

    code: str | None = Field(default=None, alias="Code")
    """Code of an error. Can be null."""
    error_code: str | None = Field(default=None, alias="ErrorCode")
    """Error code. Can be null."""
    message: str | None = Field(default=None, alias="Message")
    """Description of an error. Can be null."""


Address = Annotated[
    Annotated[AddressLegacy, Tag("legacy")]
    | Annotated[AddressCity, Tag("city")]
    | Annotated[AddressBase, Tag(UNKNOWN)],
    discriminator(
        "type",
        "type",
        (
            "legacy",
            "city",
        ),
    ),
]
"""Order delivery address

One of `AddressLegacy`, `AddressCity`, selected by `type`. Values unknown to this library are parsed as `AddressBase`.
"""


Customer = Annotated[
    Annotated[RegularCustomer, Tag("regular")]
    | Annotated[AnonymousCustomer, Tag("one-time")]
    | Annotated[CustomerBase, Tag(UNKNOWN)],
    discriminator(
        "type",
        "type",
        (
            "regular",
            "one-time",
        ),
    ),
]
"""Customer base info.

One of `RegularCustomer`, `AnonymousCustomer`, selected by `type`. Values unknown to this library are parsed as `CustomerBase`.
"""


Discount = Annotated[
    Annotated[RmsDiscount, Tag("RMS")]
    | Annotated[IikoCardDiscount, Tag("iikoCard")]
    | Annotated[DiscountBase, Tag(UNKNOWN)],
    discriminator(
        "type",
        "type",
        (
            "RMS",
            "iikoCard",
        ),
    ),
]
"""Discount/surcharge.

One of `RmsDiscount`, `IikoCardDiscount`, selected by `type`. Values unknown to this library are parsed as `DiscountBase`.
"""


OrderItem = Annotated[
    Annotated[ProductOrderItem, Tag("Product")]
    | Annotated[CompoundOrderItem, Tag("Compound")]
    | Annotated[OrderItemBase, Tag(UNKNOWN)],
    discriminator(
        "type",
        "type",
        (
            "Product",
            "Compound",
        ),
    ),
]
"""Order item.

One of `ProductOrderItem`, `CompoundOrderItem`, selected by `type`. Values unknown to this library are parsed as `OrderItemBase`.
"""


OrganizationInfo = Annotated[
    Annotated[SimpleOrganizationInfo, Tag("Simple")]
    | Annotated[ExtendedOrganizationInfo, Tag("Extended")]
    | Annotated[OrganizationInfoBase, Tag(UNKNOWN)],
    discriminator(
        "responseType",
        "response_type",
        (
            "Simple",
            "Extended",
        ),
    ),
]
"""Organization details.

One of `SimpleOrganizationInfo`, `ExtendedOrganizationInfo`, selected by `response_type`. Values unknown to this library are parsed as `OrganizationInfoBase`.
"""


Payment = Annotated[
    Annotated[CashPayment, Tag("Cash")]
    | Annotated[CardPayment, Tag("Card")]
    | Annotated[LoyaltyCardPayment, Tag("LoyaltyCard")]
    | Annotated[ExternalPayment, Tag("External")]
    | Annotated[PaymentBase, Tag(UNKNOWN)],
    discriminator(
        "paymentTypeKind",
        "payment_type_kind",
        (
            "Cash",
            "Card",
            "LoyaltyCard",
            "External",
        ),
    ),
]
"""Base class of delivery order payment item.

One of `CashPayment`, `CardPayment`, `LoyaltyCardPayment`, `ExternalPayment`, selected by `payment_type_kind`. Values unknown to this library are parsed as `PaymentBase`.
"""


PaymentAdditionalData = Annotated[
    Annotated[LoyaltyCardPaymentAdditionalData, Tag("LoyaltyCard")]
    | Annotated[CardPaymentAdditionalData, Tag("Card")]
    | Annotated[ExternalPaymentAdditionalData, Tag("External")]
    | Annotated[PaymentAdditionalDataBase, Tag(UNKNOWN)],
    discriminator(
        "type",
        "type",
        (
            "LoyaltyCard",
            "Card",
            "External",
        ),
    ),
]
"""Additional payment data.

One of `LoyaltyCardPaymentAdditionalData`, `CardPaymentAdditionalData`, `ExternalPaymentAdditionalData`, selected by `type`. Values unknown to this library are parsed as `PaymentAdditionalDataBase`.
"""


RetrievedCustomer = Annotated[
    Annotated[RetrievedRegularCustomer, Tag("regular")]
    | Annotated[RetrievedAnonymousCustomer, Tag("one-time")]
    | Annotated[RetrievedCustomerBase, Tag(UNKNOWN)],
    discriminator(
        "type",
        "type",
        (
            "regular",
            "one-time",
        ),
    ),
]
"""Delivery customer.

One of `RetrievedRegularCustomer`, `RetrievedAnonymousCustomer`, selected by `type`. Values unknown to this library are parsed as `RetrievedCustomerBase`.
"""


RetrievedOrderItem = Annotated[
    Annotated[RetrievedProductOrderItem, Tag("Product")]
    | Annotated[RetrievedCompoundOrderItem, Tag("Compound")]
    | Annotated[ServiceOrderItem, Tag("Service")]
    | Annotated[RetrievedOrderItemBase, Tag(UNKNOWN)],
    discriminator(
        "type",
        "type",
        (
            "Product",
            "Compound",
            "Service",
        ),
    ),
]
"""Order item.

One of `RetrievedProductOrderItem`, `RetrievedCompoundOrderItem`, `ServiceOrderItem`, selected by `type`. Values unknown to this library are parsed as `RetrievedOrderItemBase`.
"""


TipsPayment = Annotated[
    Annotated[CashTipsPayment, Tag("Cash")]
    | Annotated[CardTipsPayment, Tag("Card")]
    | Annotated[ExternalTipsPayment, Tag("External")]
    | Annotated[TipsPaymentBase, Tag(UNKNOWN)],
    discriminator(
        "paymentTypeKind",
        "payment_type_kind",
        (
            "Cash",
            "Card",
            "External",
        ),
    ),
]
"""Base class of delivery order payment item.

One of `CashTipsPayment`, `CardTipsPayment`, `ExternalTipsPayment`, selected by `payment_type_kind`. Values unknown to this library are parsed as `TipsPaymentBase`.
"""


__all__ = [
    "AddOrderPaymentsRequest",
    "Address",
    "AddressBase",
    "AddressCity",
    "AddressFormatType",
    "AddressHintsServiceType",
    "AddressLegacy",
    "AnonymousCustomer",
    "CancelInfo",
    "CardPayment",
    "CardPaymentAdditionalData",
    "CardTipsPayment",
    "CashPayment",
    "CashTipsPayment",
    "ChangeExternalDataRequest",
    "ChangePaymentsRequest",
    "ChequeAdditionalInfo",
    "Combo",
    "ComboItemInformation",
    "CompoundItemTemplate",
    "CompoundOrderItem",
    "CompoundOrderItemComponent",
    "Coordinates",
    "CorrelationIdResponse",
    "CourierInfo",
    "CreationStatus",
    "Customer",
    "CustomerBase",
    "DeletionMethod",
    "DeliveriesResponseOrderPaymentType",
    "DeliveriesResponseOrderStreet",
    "DeliveryOrderPaymentSettings",
    "DeliveryPoint",
    "DeliveryServiceType",
    "DeliverySettingsServiceType",
    "DeliveryStatus",
    "DeliveryStreet",
    "Discount",
    "DiscountBase",
    "DiscountCard",
    "DiscountItem",
    "DiscountType",
    "DiscountsInfo",
    "DynamicDiscount",
    "ErrorCode",
    "ErrorInfo",
    "ExtendedOrganizationInfo",
    "ExternalCourierService",
    "ExternalData",
    "ExternalDataEntry",
    "ExternalPayment",
    "ExternalPaymentAdditionalData",
    "ExternalTipsPayment",
    "FilterCondition",
    "Gender",
    "GetByIDRequest",
    "GetOrganizationsRequest",
    "GetOrganizationsResponse",
    "Guests",
    "IdentifierCode",
    "IikoCardDiscount",
    "IikoCardDiscountItem",
    "IikoCardSearchScope",
    "ItemDeletedInfo",
    "ListRequest",
    "LoyaltyCardPayment",
    "LoyaltyCardPaymentAdditionalData",
    "LoyaltyInfo",
    "Modifier",
    "OrderCombo",
    "OrderInfo",
    "OrderItem",
    "OrderItemBase",
    "OrderItemIdentifierCode",
    "OrderItemModifier",
    "OrderItemStatus",
    "OrderServiceType",
    "OrderStatus",
    "OrganizationInfo",
    "OrganizationInfoBase",
    "OrganizationItems",
    "Payment",
    "PaymentAdditionalData",
    "PaymentAdditionalDataBase",
    "PaymentBase",
    "PaymentItem",
    "PaymentTypeKind",
    "PositionWithSum",
    "PriceCategory",
    "Problem",
    "ProductGroup",
    "ProductOrderItem",
    "RegularCustomer",
    "Reserve",
    "ReserveCancelReason",
    "ReserveInfo",
    "ReserveStatus",
    "RetrievedAddress",
    "RetrievedAnonymousCustomer",
    "RetrievedCancelCause",
    "RetrievedCity",
    "RetrievedComboItemInformation",
    "RetrievedCompoundOrderItem",
    "RetrievedCompoundOrderItemComponent",
    "RetrievedConception",
    "RetrievedCustomer",
    "RetrievedCustomerBase",
    "RetrievedDeliveryPoint",
    "RetrievedDynamicDiscount",
    "RetrievedEmployee",
    "RetrievedExternalData",
    "RetrievedGuestsInfo",
    "RetrievedLoyaltyInfo",
    "RetrievedMarketingSource",
    "RetrievedOrder",
    "RetrievedOrderItem",
    "RetrievedOrderItemBase",
    "RetrievedOrderStatus",
    "RetrievedOrderType",
    "RetrievedProduct",
    "RetrievedProductOrderItem",
    "RetrievedProductSize",
    "RetrievedRegion",
    "RetrievedRegularCustomer",
    "RetrievedRemovalType",
    "RetrievedReserveOrder",
    "RetrievedTableOrder",
    "RetrievedTipsType",
    "RmsDiscount",
    "ServiceOrderItem",
    "SimpleOrganizationInfo",
    "SplitOrderBetweenCashRegisters",
    "TableOrderInfo",
    "TerminalGroup",
    "TerminalGroupsResponse",
    "TipsPayment",
    "TipsPaymentBase",
    "TipsPaymentItem",
    "WarningInfo",
]
