"""Models of the delivery endpoints.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

from decimal import Decimal
from typing import Annotated, Literal

from pydantic import Field, Tag

from iikocloudapi._base import (
    UNKNOWN,
    IikoDateTime,
    IikoModel,
    OpenIntEnum,
    OpenStrEnum,
    OrganizationItems,
    discriminator,
)
from iikocloudapi.models.common import (
    ChequeAdditionalInfo,
    Combo,
    Customer,
    DeliveryPoint,
    DeliveryServiceType,
    DeliveryStatus,
    DiscountsInfo,
    ExternalData,
    Guests,
    LoyaltyInfo,
    OrderInfo,
    OrderItem,
    Payment,
    TipsPayment,
)


class ActionOnValidationRejection(OpenIntEnum):
    """Actions on problems with auto-assignment."""

    VALUE_1 = 1
    VALUE_2 = 2


class DeliveryGeocodeServiceType(OpenIntEnum):
    """Geocoding service."""

    VALUE_1 = 1
    VALUE_2 = 2
    VALUE_3 = 3
    VALUE_4 = 4


class DeliveryRestrictionRejectCode(OpenStrEnum):
    """Delivery restrictions reject cause code."""

    UNDEFINED = "Undefined"
    SUM_IS_LESS_THEN_MINIMUM = "SumIsLessThenMinimum"
    DAY_OF_WEEK_IS_UNACCEPTABLE = "DayOfWeekIsUnacceptable"
    DELIVERY_TIME_IS_UNACCEPTABLE = "DeliveryTimeIsUnacceptable"
    OUT_OF_TERMINAL_ZONE = "OutOfTerminalZone"


class DeliveryRestrictionsMode(OpenIntEnum):
    """Delivery restrictions mode."""

    VALUE_0 = 0
    VALUE_1 = 1
    VALUE_2 = 2


class DeliveryStatusForUpdate(OpenStrEnum):
    """Delivery order statuses for update requests."""

    WAITING = "Waiting"
    ON_WAY = "OnWay"
    DELIVERED = "Delivered"


class HousesRangeType(OpenIntEnum):
    """Type of house number range."""

    VALUE_0 = 0
    VALUE_1 = 1
    VALUE_2 = 2
    VALUE_3 = 3


class OrderDraftSortProperty(OpenStrEnum):
    """OrderDraft sorting property."""

    COMPLETE_BEFORE = "CompleteBefore"
    CUSTOMER = "Customer"


class OrderSortProperty(OpenStrEnum):
    """Order sorting property."""

    NUMBER = "Number"
    COMPLETE_BEFORE = "CompleteBefore"
    SUM = "Sum"
    CUSTOMER = "Customer"
    COURIER = "Courier"
    STATUS = "Status"
    ORDER_TYPE_NAME = "OrderTypeName"


class SortDirection(OpenStrEnum):
    """Sorting direction."""

    ASCENDING = "Ascending"
    DESCENDING = "Descending"


class AddOrderItemsRequest(IikoModel):
    """Request for add order items."""

    order_id: str
    """Order ID."""
    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    items: list[OrderItem]
    """Order items (may include ProductOrderItem or CompoundOrderItem)."""
    combos: list[Combo] | None = None
    """Combos.

    Allowed from version `7.6.1`.
    """


class AllowedItemWithDuration(IikoModel):
    """Suitable terminal group with delivery duration and other parameters."""

    __always_sent__ = (
        "zone",
        "delivery_service_product_id",
    )

    terminal_group_id: str
    """Terminal group ID.

    Can be obtained by `/api/1/terminal_groups` operation.
    """
    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    delivery_duration_in_minutes: int
    """Delivery duration in minutes."""
    zone: str | None = None
    """Delivery zone name which this TerminalGroupId belongs to."""
    delivery_service_product_id: str | None = None
    """Link to "delivery service payment"."""


class CancelDeliveryConfirmationRequest(IikoModel):
    """Request for cancel delivery confirmation."""

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    order_id: str
    """Order ID."""


class CancelOrderRequest(IikoModel):
    """Request for cancel the order."""

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    order_id: str
    """Order ID."""
    moved_order_id: str | None = None
    """Fill this field with id of the new order if current order has been moved to the new RMS/terminal group."""
    cancel_cause_id: str | None = None
    """Cancel order dictionary item id.

    Allowed from version `7.7.1`.
    """
    cancel_comment: str | None = None
    """Comment to the delivery cancellation.

    Allowed from version `8.7.6`.
    """
    removal_type_id: str | None = None
    """Removal type (for delete printed order items).

    Allowed from version `7.7.1`.
    """
    removal_comment: str | None = Field(default=None, min_length=0, max_length=255)
    """Comment to the charge-off.

    Allowed from version `8.7.6`.
    """
    user_id_for_writeoff: str | None = None
    """User for writeoff (for delete printed order items).

    Allowed from version `7.7.1`.
    """


class ChangeCompleteBeforeRequest(IikoModel):
    """Request for change time when client wants the order to be delivered."""

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    order_id: str
    """Order ID."""
    new_complete_before: IikoDateTime
    """New time when client wants the order to be delivered (Local for delivery terminal)."""


class ChangeDeliveryCommentRequest(IikoModel):
    """Request for change delivery comment."""

    organization_id: str
    """Organization ID."""
    order_id: str
    """Order ID."""
    comment: str
    """New delivery comment."""


class ChangeDeliveryOperatorRequest(IikoModel):
    """Request for assign/change the order operator."""

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    order_id: str
    """Order ID."""
    operator_id: str
    """Operator to assign the order to."""


class ChangeDeliveryPointRequest(IikoModel):
    """Request for change order's delivery point information."""

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    order_id: str
    """Order ID."""
    new_delivery_point: DeliveryPoint
    """New address of delivery."""


class ChangeDriverInfoRequest(IikoModel):
    """Request for change driver info."""

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    order_id: str
    """Order ID."""
    driver_id: str | None = None
    """Driver ID.

    Can be obtained by `/api/1/employees/couriers` operation.
    """
    estimated_time: IikoDateTime | None = None
    """Delivery estimated time."""


class ChangeServiceTypeRequestBase(IikoModel):
    """Request for change order's delivery type."""

    __variants__ = (
        "new_service_type",
        (
            "DeliveryByCourier",
            "DeliveryByClient",
        ),
    )

    new_service_type: str
    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    order_id: str
    """Order ID."""


class ChangeServiceTypeDeliveryByClient(ChangeServiceTypeRequestBase):
    """Change order's delivery type to DeliveryByClient."""

    __always_sent__ = ("new_service_type",)

    new_service_type: Literal["DeliveryByClient"] = "DeliveryByClient"  # pyright: ignore[reportIncompatibleVariableOverride]


class ChangeServiceTypeDeliveryByCourier(ChangeServiceTypeRequestBase):
    """Change order's delivery type to DeliveryByCourier."""

    __always_sent__ = ("new_service_type",)

    new_service_type: Literal["DeliveryByCourier"] = "DeliveryByCourier"  # pyright: ignore[reportIncompatibleVariableOverride]
    delivery_point: DeliveryPoint
    """Address of delivery."""


class CitiesRequest(IikoModel):
    """Organization request DTO."""

    organization_ids: list[str]
    """IDs of organizations that require data return.

    Can be obtained by `/api/1/organizations` operation.
    """
    include_deleted: bool | None = None
    """Include deleted cities in response."""


class CitiesResponse(IikoModel):
    """Service response with list of cities."""

    correlation_id: str
    """Operation ID."""
    cities: list[OrganizationItems[City]]
    """List of cities."""


class City(IikoModel):
    """City DTO."""

    id: str
    """City ID in RMS."""
    name: str
    """Name."""
    external_revision: int | None = None
    """External revision."""
    is_deleted: bool
    """Is-Deleted attribute."""
    classifier_id: str | None = None
    """ID in classifier, e.g., address database."""
    additional_info: str | None = None
    """City additional information."""


class CloseDeliveryOrderRequest(IikoModel):
    """Request for close table order."""

    delivery_date: IikoDateTime | None = None
    """Actual delivery time. If empty local iikoFront time will used.

    Allowed from version `8.0.6`.
    """
    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    order_id: str
    """Order ID."""


class CommitDraftRequest(IikoModel):
    """Delivery order draft commitment request."""

    organization_id: str
    """Organization ID of the new order.

    Can be obtained by `/api/1/organizations` operation.
    """
    terminal_group_id: str | None = None
    """Front group ID the order must be sent to.

    Can be obtained by `/api/1/terminal_groups` operation.
    """
    create_order_settings: CreateOrderSettings | None = None
    """Order creation parameters."""
    order_id: str
    """ID of the order."""


class ConfirmDeliveryRequest(IikoModel):
    """Request for confirm delivery."""

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    order_id: str
    """Order ID."""


class CreateDraftRequest(IikoModel):
    """Draft creation model."""

    organization_id: str
    """Organization ID of the new order.

    Can be obtained by `/api/1/organizations` operation.
    """
    order: DeliveryOrderDraft
    """Order item."""
    terminal_group_id: str | None = None
    """Front group ID the order must be sent to.

    Can be obtained by `/api/1/terminal_groups` operation.
    """


class CreateOrSaveDraftResponse(IikoModel):
    """Wrapping object (external) for a delivery order draft creation/update return."""

    correlation_id: str
    """Operation ID."""
    order_id: str
    """Order draft order ID."""


class CreateOrderRequest(IikoModel):
    """Order creation model."""

    organization_id: str
    """Organization ID of the new order.

    Can be obtained by `/api/1/organizations` operation.
    """
    terminal_group_id: str | None = None
    """Front group ID the order must be sent to.

    Can be obtained by `/api/1/terminal_groups` operation.
    """
    create_order_settings: CreateOrderSettings | None = None
    """Order creation parameters."""
    order: DeliveryOrder
    """Order."""


class CreateOrderSettings(IikoModel):
    """Order creation options."""

    transport_to_front_timeout: int | None = None
    """Timeout in seconds that specifies how much time is given for order to reach iikoFront.
    After this time, order is nullified if iikoFront doesn't take it. By default - 8 seconds.
    """
    check_stop_list: bool | None = None
    """Flag indicating whether there's need to check order items in out-of-stock list.

    Unable if `terminalGroupId` is null.
    """


class DeleteDraftRequest(IikoModel):
    """Delivery order draft deletion request."""

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    order_id: str
    """ID of the order."""


class DeliveryOrder(IikoModel):
    """Delivery order."""

    menu_id: str | None = None
    """External menu ID."""
    id: str | None = None
    """Order ID. Must be unique.
    If sent null, it generates automatically on iikoTransport side.
    """
    external_number: str | None = Field(default=None, min_length=0, max_length=50)
    """Order external number.

    Allowed from version `8.0.6`.
    """
    complete_before: IikoDateTime | None = None
    """Order fulfillment date.
    Date and time must be local for delivery terminal, without time zone (take a look at example).
    If null, order is urgent and time is calculated based on customer settings,
    i.e. the shortest delivery time possible.
    Permissible values: from current day and 60 days on.
    """
    phone: str = Field(min_length=8, max_length=40)
    """Telephone number.
    Must begin with symbol "+" and must be at least 8 digits.
    """
    phone_extension: str | None = Field(default=None, min_length=1, max_length=10)
    """Extension telephone number.
    Must contain only digits and have length from 1 to 10 symbols.

    Allowed from version `9.2.5`.
    """
    order_type_id: str | None = None
    """Order type ID.

    Can be obtained by `/api/1/deliveries/order_types` operation.

    Only one of the fields must be defined: **orderTypeId** or **orderServiceType**.
    """
    order_service_type: DeliveryServiceType | None = None
    """Order service type.
    Only one of the fields must be defined: **orderTypeId** or **orderServiceType**.

    Allowed from version `7.0.3`.
    """
    delivery_point: DeliveryPoint | None = None
    """Delivery point details.
    Not required in case of customer pickup. Otherwise, required.
    """
    comment: str | None = None
    """Order comment."""
    customer: Customer | None = None
    """Customer.

    'Regular' customer:

    - can be used only if a customer agrees to take part in the store's loyalty programs
    - customer details will be added (updated) to the store's customer database
    - benefits (accumulation of rewards, etc.) of active loyalty programs will be made available to the customer

    'One-time' customer:

    - should be used if a customer does not agree to take part in the store's loyalty programs or an aggregator (external system) does not provide customer details
    - customer details will NOT be added to the store's customer database and will be used ONLY to complete the current order
    """
    guests: Guests | None = None
    """Guest details. Not equal to the customer who makes an order."""
    marketing_source_id: str | None = None
    """Marketing source (advertisement) ID.

    Can be obtained by `/api/1/marketing_sources` operation.
    """
    operator_id: str | None = None
    """Operator ID.

    Allowed from version `7.6.3`.
    """
    delivery_duration: int | None = None
    """Delivery duration.

    Allowed from version `8.8.6`.
    """
    delivery_zone: str | None = None
    """Name of delivery zone.

    Allowed from version `8.8.6`.
    """
    price_category_id: str | None = None
    """Price category id of the order.

    Can be obtained by `/api/2/menu` operation.

    Allowed from version `9.0.5`.
    """
    items: list[OrderItem]
    """Order items."""
    combos: list[Combo] | None = None
    """Combos included in order."""
    payments: list[Payment] | None = None
    """Order payment components.

    Type **LoyaltyCard** allowed from version `7.1.5`.
    """
    tips: list[TipsPayment] | None = None
    """Order tips components."""
    source_key: str | None = None
    """The string key (marker) of the source (partner - api user) that created the order. Needed to limit the visibility of orders for external integration."""
    discounts_info: DiscountsInfo | None = None
    """Discounts/surcharges."""
    loyalty_info: LoyaltyInfo | None = None
    """Information about Loyalty app."""
    cheque_additional_info: ChequeAdditionalInfo | None = None
    """Cheque additional information."""
    external_data: list[ExternalData] | None = None
    """Order external data.

    Allowed from version `8.0.6`.
    """


class DeliveryOrderDraft(IikoModel):
    """Delivery order draft."""

    menu_id: str
    """External menu ID."""
    id: str | None = None
    """Order ID. Must be unique.
    If sent null, it generates automatically on iikoTransport side.
    """
    external_number: str | None = None
    """Order external number.

    Allowed from version `8.0.6`.
    """
    complete_before: IikoDateTime | None = None
    """Order fulfillment date.
    Date and time must be local for delivery terminal, without time zone (take a look at example).
    If null, order is urgent and time is calculated based on customer settings,
    i.e. the shortest delivery time possible.
    Permissible values: from current day and 60 days on.
    """
    phone: str
    """Telephone number.
    Must begin with symbol "+" and must be at least 8 digits.
    """
    phone_extension: str | None = None
    """Extension telephone number.
    Must contain only digits and have length from 1 to 10 symbols.

    Allowed from version `9.2.5`.
    """
    order_type_id: str | None = None
    """Order type ID.

    Can be obtained by `/api/1/deliveries/order_types` operation.

    Only one of the fields must be defined: **orderTypeId** or **orderServiceType**.
    """
    order_service_type: DeliveryServiceType | None = None
    """Order service type.
    Only one of the fields must be defined: **orderTypeId** or **orderServiceType**.

    Allowed from version `7.0.3`.
    """
    delivery_point: DeliveryPoint | None = None
    """Delivery point details.
    Not required in case of customer pickup. Otherwise, required.
    """
    comment: str | None = None
    """Order comment."""
    customer: Customer | None = None
    """Customer.

    'Regular' customer:

    - can be used only if a customer agrees to take part in the store's loyalty programs
    - customer details will be added (updated) to the store's customer database
    - benefits (accumulation of rewards, etc.) of active loyalty programs will be made available to the customer

    'One-time' customer:

    - should be used if a customer does not agree to take part in the store's loyalty programs or an aggregator (external system) does not provide customer details
    - customer details will NOT be added to the store's customer database and will be used ONLY to complete the current order
    """
    guests: Guests | None = None
    """Guest details. Not equal to the customer who makes an order."""
    marketing_source_id: str | None = None
    """Marketing source (advertisement) ID.

    Can be obtained by `/api/1/marketing_sources` operation.
    """
    operator_id: str | None = None
    """Operator ID.

    Allowed from version `7.6.3`.
    """
    delivery_duration: int | None = None
    """Delivery duration.

    Allowed from version `8.8.6`.
    """
    delivery_zone: str | None = None
    """Name of delivery zone.

    Allowed from version `8.8.6`.
    """
    price_category_id: str | None = None
    """Price category id of the order.

    Can be obtained by `/api/2/menu` operation.

    Allowed from version `9.0.5`.
    """
    items: list[OrderItem]
    """Order items."""
    combos: list[Combo] | None = None
    """Combos included in order."""
    payments: list[Payment] | None = None
    """Order payment components.

    Type **LoyaltyCard** allowed from version `7.1.5`.
    """
    tips: list[TipsPayment] | None = None
    """Order tips components."""
    source_key: str | None = None
    """The string key (marker) of the source (partner - api user) that created the order. Needed to limit the visibility of orders for external integration."""
    discounts_info: DiscountsInfo | None = None
    """Discounts/surcharges."""
    loyalty_info: LoyaltyInfo | None = None
    """Information about Loyalty app."""
    cheque_additional_info: ChequeAdditionalInfo | None = None
    """Cheque additional information."""
    external_data: list[ExternalData] | None = None
    """Order external data.

    Allowed from version `8.0.6`.
    """


class DeliveryRestrictionItem(IikoModel):
    """Item of delivery restrictions."""

    __always_sent__ = (
        "min_sum",
        "terminal_group_id",
        "organization_id",
        "zone",
        "from_",
        "to",
        "delivery_service_product_id",
    )

    min_sum: Decimal | None = None
    """The minimum order amount for a given point in a given time interval in this delivery zone."""
    terminal_group_id: str | None = None
    """Terminal group ID.

    Can be obtained by `/api/1/terminal_groups` operation.
    """
    organization_id: str | None = None
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    zone: str | None = None
    """Name of delivery zone from cartography."""
    week_map: int
    """Days of the week."""
    from_: int | None = Field(default=None, alias="from")
    """The time from which the point can process orders from the selected zone, in minutes from the beginning of the day."""
    to: int | None = None
    """The maximum time at which a point can carry an order to a given zone, in minutes from the beginning of the day."""
    priority: int
    """Priority of point in delivery zone."""
    delivery_duration_in_minutes: int
    """Delivery duration in delivery zone."""
    delivery_service_product_id: str | None = None
    """Link to "delivery service payment"."""


class DeliveryRestrictions(IikoModel):
    """Delivery restrictions."""

    __always_sent__ = (
        "delivery_regions_map_url",
        "default_min_sum",
        "default_from",
        "default_to",
        "default_delivery_service_product_id",
        "external_assignation_service_url",
    )

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    delivery_geocode_service_type: DeliveryGeocodeServiceType
    """Geocoding service type."""
    delivery_regions_map_url: str | None = None
    """Link to the map of delivery service regions."""
    default_delivery_duration_in_minutes: int
    """General standard of delivery time."""
    default_self_service_duration_in_minutes: int
    """Default pickup time."""
    use_same_delivery_duration: bool
    """Indication that all delivery points in all delivery zones use common delivery time limits."""
    use_same_min_sum: bool
    """Indication that all delivery points for all delivery zones use the total minimum order amount."""
    default_min_sum: Decimal | None = None
    """Total minimum order amount."""
    use_same_work_time_interval: bool
    """Indication that all delivery points in all zones use common time limits."""
    default_from: int | None = None
    """The beginning of the interval of the total work time for all points and delivery zones,
    in minutes from the beginning of the day.
    """
    default_to: int | None = None
    """End of the total work time interval for all points and delivery zones,
    in minutes from the beginning of the day.
    """
    use_same_restrictions_on_all_week: bool
    """Indication that all delivery points in all zones use the same schedule for all days of the week."""
    restrictions: list[DeliveryRestrictionItem]
    """Restrictions."""
    delivery_zones: list[DeliveryZone]
    """Delivery zones."""
    reject_on_geocoding_error: bool
    """Reject delivery if we could not geocode the address."""
    add_delivery_service_cost: bool
    """Add shipping cost to order."""
    use_same_delivery_service_product: bool
    """Indication that the cost is the same for all points of delivery."""
    default_delivery_service_product_id: str | None = None
    """Link to "delivery service payment"."""
    use_external_assignation_service: bool
    """Use external delivery distribution service."""
    front_trusts_call_center_check: bool
    """Indication whether or not to trust on the fronts the call center mapping restrictions from the call center
    if the composition of the order has not changed since the last check. If true, then trust.
    """
    external_assignation_service_url: str | None = None
    """Address of external delivery distribution service."""
    require_exact_address_for_geocoding: bool
    """Require an exact geocoding address."""
    zones_mode: DeliveryRestrictionsMode
    """Delivery restrictions mode."""
    auto_assign_external_deliveries: bool
    """Automatically assigned delivery method based on cartography."""
    action_on_validation_rejection: ActionOnValidationRejection
    """Action on problems with auto-assignment."""


class DeliveryRestrictionsCoordinates(IikoModel):
    """Coordinate details."""

    latitude: Decimal
    """Latitude."""
    longitude: Decimal
    """Longitude."""


class DeliveryZone(IikoModel):
    """Delivery zone."""

    name: str
    """Polygon name."""
    coordinates: list[DeliveryRestrictionsCoordinates]
    """A set of points describing a polygon."""
    addresses: list[DeliveryZoneAddressBinding]
    """A set of addresses describing a polygon.

    Available only for manual delivery zones.
    """


class DeliveryZoneAddressBinding(IikoModel):
    """Delivery zone polygon, defined by the combination of street, index and house numbers."""

    street_id: str
    """ID of the delivery zone's street."""
    postcode: str
    """Postcode."""
    houses: HousesRange
    """Range of house numbers in the delivery zone."""


class FilterDraftsRequest(IikoModel):
    """Request for the list of order drafts by several filters."""

    organization_ids: list[str]
    """Organization ID for which the order drafts search will be performed.

    Can be obtained by `/api/1/organizations` operation.
    """
    date_from: IikoDateTime | None = None
    """Draft creation time (UTC). Lower limit."""
    date_to: IikoDateTime | None = None
    """Draft creation time (UTC). Upper limit."""
    phone: str | None = None
    """Phone number."""
    limit: int | None = None
    """Desirable size of result set (50 by default)."""
    offset: int | None = None
    """Offset from the beginning of full result set for paging."""
    source_keys: list[str] | None = None
    """Delivery sources (DeliveryClub, PH and etc.)"""
    terminal_group_ids: list[str] | None = None
    """List of terminal groups IDs."""
    search_text: str | None = None
    """Value for search. Used for prefix search."""
    sort_property: OrderDraftSortProperty | None = None
    """Sorting property."""
    sort_direction: SortDirection | None = None
    """Sorting direction."""
    operator_ids: list[str] | None = None
    """List of drafts operator IDs."""
    order_type_ids: list[str] | None = None
    """List of drafts order type IDs."""


class FilterDraftsResponse(IikoModel):
    """Wrapping object (external) for a delivery order drafts return."""

    correlation_id: str
    """Operation ID."""
    drafts: list[OrderDraft]
    """Order drafts list."""


class GetAllowedRestrictionsRequest(IikoModel):
    """Request to identify suitable terminal groups."""

    organization_id: str | None = None
    """**Deprecated.** Organization ID. Deprecated, use "organizationIds"."""
    organization_ids: list[str] | None = None
    """Organization IDs.

    Can be obtained by `/api/1/organizations` operation.
    """
    delivery_address: RestrictionsAddress | None = None
    """Delivery address."""
    order_location: OrderLocation | None = None
    """Order location."""
    order_items: list[RestrictionsOrderItem] | None = None
    """Order list."""
    is_courier_delivery: bool
    """Type of delivery service."""
    delivery_date: IikoDateTime | None = None
    """Delivery date (Local for delivery terminal)."""
    delivery_sum: Decimal | None = None
    """Sum."""
    discount_sum: Decimal | None = None
    """Discounts sum."""


class GetAllowedRestrictionsResponse(IikoModel):
    """Response for a request to identify suitable terminal groups."""

    __always_sent__ = (
        "reject_cause",
        "address_external_id",
        "location",
    )

    correlation_id: str
    """Operation ID."""
    is_allowed: bool
    """A sign of successful verification."""
    reject_cause: str | None = None
    """**Deprecated.** Reject cause."""
    address_external_id: str | None = None
    """Delivery address ID in external mapping system."""
    location: OrderLocation | None = None
    """Coordinates returned by geocoding service."""
    allowed_items: list[AllowedItemWithDuration]
    """Suitable terminal groups with a delivery duration for them."""
    rejected_items: list[RejectItem]
    """Rejected items with cause."""


class GetDeliveryRestrictionsRequest(IikoModel):
    """Request for delivery restrictions."""

    organization_ids: list[str]
    """Organizations IDs which delivery restrictions have to be returned.

    Can be obtained by `/api/1/organizations` operation.
    """


class GetDeliveryRestrictionsResponse(IikoModel):
    """Response for delivery restrictions."""

    correlation_id: str
    """Operation ID."""
    delivery_restrictions: list[DeliveryRestrictions]
    """Delivery restrictions."""


class GetDraftRequest(IikoModel):
    """Request for an order draft by ID."""

    organization_id: str
    """Organization ID for which the order search will be performed.

    Can be obtained by `/api/1/organizations` operation.
    """
    order_id: str
    """Order ID."""


class GetDraftResponse(IikoModel):
    """Wrapping object (external) for an order draft."""

    correlation_id: str
    """Operation ID."""
    order: DeliveryOrderDraft
    """Order draft object."""
    locked_by_user: str | None = None
    """ID of the employee who is currently editing this draft."""
    locked_at: IikoDateTime | None = None
    """Timestamp of when the draft was taken for editing (lock)."""
    organization_id: str
    """Organization ID."""
    terminal_group_id: str | None = None
    """Terminal group ID."""
    created_at: IikoDateTime
    """Draft creation time (UTC)."""


class HousesRange(IikoModel):
    """Range of house numbers in the delivery zone.
    It can work in two modes:
    a) HousesRangeType.SpecificNumbers - list of house numbers. If the house is on this list - it is in the range
    b) Rest HousesRangeType. Defines a range of numbers from StartingNumber to MaxNumber.
    Since it is necessary to compare numbers - only supports numeric house numbers.
    Type determines the admissibility of even/odd numbers.
    """

    type: HousesRangeType
    """Type of house number range."""
    starting_number: int
    """Starting house number."""
    max_number: int
    """Maximum house number."""
    is_unlimited_range: bool
    """Unlimited range."""
    specific_numbers: list[str]
    """Specific numbers."""


class LockOrUnlockDraftRequest(IikoModel):
    """Delivery order draft lock or unlock request."""

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    order_id: str
    """ID of the order."""
    employee_id: str
    """ID of the employee."""


class MarketingSource(IikoModel):
    """DTO for marketing source in iikoRMS."""

    id: str
    """Marketing source ID."""
    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    name: str
    """Marketing source name."""
    external_revision: int | None = None
    """External system revision number."""
    is_deleted: bool | None = None
    """IsDeleted attribute of marketing source."""
    attached_sources: list[str]
    """Attached marketing sources."""


class MarketingSourcesRequest(IikoModel):
    """Request for marketing sources."""

    organization_ids: list[str]
    """Organizations IDs which marketing sources have to be returned.

    Can be obtained by `/api/1/organizations` operation.
    """


class MarketingSourcesResponse(IikoModel):
    """Response to request for marketing sources by organization."""

    correlation_id: str
    marketing_sources: list[MarketingSource]
    """List of marketing sources."""


class OrderDraft(IikoModel):
    """Order draft object."""

    id: str
    """Order ID."""
    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    locked_by_user: str | None = None
    """ID of the employee, who is editing this draft."""
    locked_at: IikoDateTime | None = None
    """Timestamp of when the draft was taken for editing (lock)."""
    order: DeliveryOrderDraft
    """Order."""
    terminal_group_id: str | None = None
    """Terminal group ID."""
    created_at: IikoDateTime
    """Draft creation time (UTC)."""


class OrderLocation(IikoModel):
    """Order location."""

    latitude: Decimal
    """Latitude."""
    longitude: Decimal
    """Longitude."""


class OrderPaymentItem(IikoModel):
    """Payments details."""

    sum: Decimal
    """Amount due"""
    payment_type_id: str
    """Payment type ID."""
    is_processed_externally: bool
    """Payment item is processed by external payment system."""


class OrderResponse(IikoModel):
    """Wrapping object (external) for a delivery order return."""

    correlation_id: str
    """Operation ID."""
    order_info: OrderInfo
    """Delivery order."""


class OrdersByDeliveryDateAndFilterRequest(IikoModel):
    """Request for information about orders from external source and based on additional filters."""

    organization_ids: list[str]
    """Organization ID for which an order search will be performed.

    Can be obtained by `/api/1/organizations` operation.
    """
    terminal_group_ids: list[str] | None = None
    """List of terminal groups IDs."""
    delivery_date_from: IikoDateTime | None = None
    """Order delivery date (Local for delivery terminal). Lower limit.

    The guaranteed order availability period is the last 7 days. To access earlier orders, use the `/api/1/deliveries/history/by_delivery_date_and_phone` method.
    """
    delivery_date_to: IikoDateTime | None = None
    """Order delivery date (Local for delivery terminal). Upper limit."""
    statuses: list[DeliveryStatus] | None = None
    """Allowed order statuses."""
    has_problem: bool | None = None
    """If true, delivery has a problem.
    Conditions under which the order has a problem:
    * order.problem.hasProblem is true;
    * order status is Unconfirmed and CookingStartTime before now;
    * order status is ReadyForCooking and (CookingStartTime + timeToCookingErrorTimeout) before now;
    * order status is CookingCompleted or Waiting and (CookingStartTime + cookingTimeout) before now.
    """
    order_service_type: DeliveryServiceType | None = None
    """Order service type."""
    search_text: str | None = None
    """Value for search. Used for prefix search."""
    time_to_cooking_error_timeout: int | None = None
    """Error timeout for status time to cooking, in seconds."""
    cooking_timeout: int | None = None
    """Expected cooking time, in seconds."""
    sort_property: OrderSortProperty | None = None
    """Sorting property."""
    sort_direction: SortDirection | None = None
    """Sorting direction."""
    rows_count: int | None = None
    """Maximum number of items returned."""
    source_keys: list[str] | None = None
    """Source keys."""
    order_ids: list[str] | None = None
    """Order IDs.

    Must be null if "posOrderIds" is not null.
    """
    pos_order_ids: list[str] | None = None
    """POS order IDs.

    Must be null if "orderIds" is not null.
    """


class OrdersByDeliveryDateAndPhoneRequest(IikoModel):
    """Request for a list of orders by phone number."""

    __always_sent__ = ("phone",)

    phone: str | None = None
    """Delivery order phone number."""
    delivery_date_from: IikoDateTime | None = None
    """Order delivery date (Local for delivery terminal). Lower limit.

    The guaranteed order availability period is the last 7 days. To access earlier orders, use the `/api/1/deliveries/history/by_delivery_date_and_phone` method.
    """
    delivery_date_to: IikoDateTime | None = None
    """Order delivery date (Local for delivery terminal). Upper limit."""
    organization_ids: list[str]
    """Organization ID for which an order search will be performed.

    Can be obtained by `/api/1/organizations` operation.
    """
    start_revision: int | None = None
    """Revision start number beginning from which (but not including) new/edited orders will be returned."""
    source_keys: list[str] | None = None
    """Source keys."""
    rows_count: int | None = None
    """Maximum number of items returned.

    If null, all items will be returned.
    """


class OrdersByDeliveryDateAndStatusRequest(IikoModel):
    """Request for information about orders."""

    organization_ids: list[str]
    """Organization ID for which an order search will be performed.

    Can be obtained by `/api/1/organizations` operation.
    """
    delivery_date_from: IikoDateTime
    """Order delivery date (Local for delivery terminal). Lower limit.

    The guaranteed order availability period is the last 7 days. To access earlier orders, use the `/api/1/deliveries/history/by_delivery_date_and_phone` method.
    """
    delivery_date_to: IikoDateTime | None = None
    """Order delivery date (Local for delivery terminal). Upper limit."""
    statuses: list[DeliveryStatus] | None = None
    """Allowed order statuses."""
    source_keys: list[str] | None = None
    """Source keys."""
    courier_ids: list[str] | None = None
    """List of driver IDs."""


class OrdersByIdRequest(IikoModel):
    """Request for information about orders using IDs."""

    organization_id: str
    """Organization ID for which an order search will be performed.

    Can be obtained by `/api/1/organizations` operation.
    """
    order_ids: list[str] | None = None
    """IDs of orders information on which is required.

    Required if "posOrderIds" is null. Must be null if "posOrderIds" is not null.

    Maximum allowed "orderIds" to request - `200`.

    The guaranteed order availability period is the last 7 days. To access earlier orders, use the `/api/1/deliveries/history/by_delivery_date_and_phone` method.
    """
    source_keys: list[str] | None = None
    """Source keys."""
    pos_order_ids: list[str] | None = None
    """POS order IDs information on which is required.

    Required if "orderIds" is null. Must be null if "orderIds" is not null.

    Maximum allowed "posOrderIds" to request - `200`.

    The guaranteed order availability period is the last 7 days. To access earlier orders, use the `/api/1/deliveries/history/by_delivery_date_and_phone` method.
    """
    return_external_data_keys: list[str] | None = None
    """Keys for retrun external data information."""
    return_locked_by_user: bool | None = None
    """Whether to check and return LockedByUser property (see FullOrderUpdateRequest.EmployeeId)."""


class OrdersByOrganization(IikoModel):
    """Orders grouped by organization."""

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    orders: list[OrderInfo]
    """List of orders by organization."""


class OrdersByRevisionRequest(IikoModel):
    """Request for a list of edited orders starting from specified revision number."""

    start_revision: int
    """Revision start number beginning from which (but not including) new/edited orders will be returned.

    Maximum revision offset to request - `3 hours`.
    """
    organization_ids: list[str]
    """Organization ID for which an order search will be performed.

    Can be obtained by `/api/1/organizations` operation.
    """
    source_keys: list[str] | None = None
    """Source keys."""


class OrdersHistoryByDeliveryDateAndPhoneRequest(IikoModel):
    """Request for a list of historical orders by phone number."""

    phone: str
    """Delivery order phone number."""
    delivery_date_from: IikoDateTime | None = None
    """Order delivery date (Local for delivery terminal). Lower limit.

    Order details are stored for 90 days.
    """
    delivery_date_to: IikoDateTime | None = None
    """Order delivery date (Local for delivery terminal). Upper limit.

    Order details are stored for 90 days.
    """
    organization_ids: list[str]
    """Organization ID for which an order search will be performed.

    Can be obtained by `/api/1/organizations` operation.
    """
    start_revision: int | None = None
    """Revision start number beginning from which (but not including) orders will be returned.

    Maximum revision offset to request - `3 hours`.
    """
    source_keys: list[str] | None = None
    """Source keys."""
    rows_count: int
    """Maximum number of items returned.

    Maximum numbers of items to request - `200`.
    """


class OrdersResponse(IikoModel):
    """Wrapping object (external) for return of delivery orders."""

    correlation_id: str
    orders: list[OrderInfo]
    """Orders."""


class OrdersWithRevisionResponse(IikoModel):
    """Wrapping object (external) for return of delivery orders."""

    correlation_id: str
    """Operation ID."""
    max_revision: int
    """Maximum revision value per all orders."""
    orders_by_organizations: list[OrdersByOrganization]
    """Orders."""


class PrintBillRequest(IikoModel):
    """Request to print bill."""

    organization_id: str
    """Organization ID."""
    order_id: str
    """Order ID."""


class PrintDeliveryBillRequest(IikoModel):
    """Request to print delivery bill."""

    organization_id: str
    """Organization ID."""
    order_id: str
    """Order ID."""


class Region(IikoModel):
    """Delivery district DTO."""

    id: str
    """Region ID in RMS."""
    name: str
    """Name."""
    external_revision: int | None = None
    """External revision."""
    is_deleted: bool
    """Is-Deleted attribute."""


class RegionsRequest(IikoModel):
    """Organization request DTO."""

    organization_ids: list[str]
    """IDs of organizations that require data return.

    Can be obtained by `/api/1/organizations` operation.
    """


class RegionsResponse(IikoModel):
    """Service response with list of districts."""

    correlation_id: str
    """Operation ID."""
    regions: list[OrganizationItems[Region]]
    """List of districts."""


class RejectItem(IikoModel):
    """Rejected item info."""

    __always_sent__ = (
        "terminal_group_id",
        "organization_id",
    )

    terminal_group_id: str | None = None
    """Terminal group ID.

    Can be obtained by `/api/1/terminal_groups` operation.
    """
    organization_id: str | None = None
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    zone: str | None = None
    """Delivery zone name which this TerminalGroupId belongs to."""
    reject_code: DeliveryRestrictionRejectCode
    """Reject cause code."""
    reject_hint: str
    """Reject hint."""
    reject_item_data: RejectItemData | None = None
    """Reject additional information."""


class RejectItemData(IikoModel):
    """Reject additional information."""

    date_from: str | None = None
    """Point work time start."""
    date_to: str | None = None
    """Point work time end."""
    allowed_week_days: list[str] | None = None
    """Allowed week days."""
    min_sum: Decimal | None = None
    """Order min sum."""


class RestrictionsAddress(IikoModel):
    """Address."""

    city: str | None = None
    """City."""
    street_name: str | None = None
    """Street."""
    street_id: str | None = None
    """Street ID."""
    house: str | None = None
    """House."""
    building: str | None = None
    """Building."""
    index: str | None = None
    """Post index."""
    line1: str | None = None
    """Address line 1.
    Contains the primary address information.
    """
    entrance: str | None = None
    """Entrance."""


class RestrictionsOrderItem(IikoModel):
    """Order item."""

    id: str
    """Product ID."""
    product: str
    """Product."""
    amount: Decimal
    """Amount."""
    modifiers: list[RestrictionsOrderItemModifier] | None = None
    """Modifiers (absolute amount)."""


class RestrictionsOrderItemModifier(IikoModel):
    """Order item modifier."""

    id: str
    """Product ID."""
    product: str | None = None
    """Product."""
    amount: Decimal
    """Amount."""


class SaveDraftRequest(IikoModel):
    """Draft editing model."""

    employee_id: str
    """ID of the employee who wants to update order draft."""
    organization_id: str
    """Organization ID of the new order.

    Can be obtained by `/api/1/organizations` operation.
    """
    order: DeliveryOrderDraft
    """Order item."""
    terminal_group_id: str | None = None
    """Front group ID the order must be sent to.

    Can be obtained by `/api/1/terminal_groups` operation.
    """


class Street(IikoModel):
    """Street DTO in iikoRMS"""

    id: str
    """ID."""
    name: str
    """Name."""
    external_revision: int | None = None
    """External system revision No."""
    classifier_id: str | None = None
    """ID in classifier, e.g., address database."""
    is_deleted: bool
    """Is-Deleted attribute."""


class StreetById(IikoModel):
    """Street by id response."""

    id: str
    """Street id."""
    classifier_id: str | None = None
    """Street classifierId."""
    city_id: str
    """City id."""
    city_name: str
    """City name."""
    street_name: str
    """Street name."""


class StreetsByCityRequest(IikoModel):
    """Organization and city request DTO."""

    organization_id: str
    """Organization ID details of which have to be returned.

    Can be obtained by `/api/1/organizations` operation.
    """
    city_id: str
    """City ID."""
    include_deleted: bool | None = None
    """Include deleted streets in response."""


class StreetsByIdRequest(IikoModel):
    """Organization and city request DTO."""

    organization_id: str
    """Organization Id."""
    ids: list[str] | None = None
    """Street Ids."""
    classifier_ids: list[str] | None = None
    """Street classifierIds."""


class StreetsByIdResponse(IikoModel):
    """Streets by ids response."""

    streets: list[StreetById] | None = None
    """Found streets."""
    correlation_id: str | None = None
    """Operation ID."""


class StreetsResponse(IikoModel):
    """Service response with list of streets."""

    correlation_id: str
    """Operation ID."""
    streets: list[Street]
    """List of streets."""


class UpdateDeliveryStatusRequest(IikoModel):
    """Request for delivery status update."""

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    order_id: str
    """Order ID."""
    delivery_status: DeliveryStatusForUpdate
    """Delivery status. Can be only switched between these three statuses."""
    delivery_date: IikoDateTime | None = None
    """The date and time when the order was received by the guest (Local for delivery terminal)."""


class UpdateOrderCourierRequest(IikoModel):
    """Request for order courier update."""

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    order_id: str
    """Order ID."""
    employee_id: str
    """Courier ID.

    Can be obtained by `/api/1/employees/couriers` operation.
    """


class UpdateOrderPaymentsRequest(IikoModel):
    """Request for order payment update."""

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    order_id: str
    """Order ID."""
    payment_items: list[OrderPaymentItem] | None = None
    """Payment details."""


class UpdateOrderProblemRequest(IikoModel):
    """Request for order problem update."""

    __always_sent__ = ("problem",)

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    order_id: str
    """Order ID."""
    has_problem: bool
    """Problem flag."""
    problem: str | None = Field(default=None, min_length=0, max_length=1000)
    """Problem text."""


class UpdateTrackingLinkRequest(IikoModel):
    """Request to update tracking link of a delivery order."""

    organization_id: str
    """OrganizationId."""
    order_id: str
    """Delivery order id."""
    tracking_link: str | None = Field(default=None, min_length=0, max_length=512)
    """Tracking link of a delivery order."""


ChangeServiceTypeRequest = Annotated[
    Annotated[ChangeServiceTypeDeliveryByCourier, Tag("DeliveryByCourier")]
    | Annotated[ChangeServiceTypeDeliveryByClient, Tag("DeliveryByClient")]
    | Annotated[ChangeServiceTypeRequestBase, Tag(UNKNOWN)],
    discriminator(
        "newServiceType",
        "new_service_type",
        (
            "DeliveryByCourier",
            "DeliveryByClient",
        ),
    ),
]
"""Request for change order's delivery type.

One of `ChangeServiceTypeDeliveryByCourier`, `ChangeServiceTypeDeliveryByClient`, selected by `new_service_type`. Values unknown to this library are parsed as `ChangeServiceTypeRequestBase`.
"""


__all__ = [
    "ActionOnValidationRejection",
    "AddOrderItemsRequest",
    "AllowedItemWithDuration",
    "CancelDeliveryConfirmationRequest",
    "CancelOrderRequest",
    "ChangeCompleteBeforeRequest",
    "ChangeDeliveryCommentRequest",
    "ChangeDeliveryOperatorRequest",
    "ChangeDeliveryPointRequest",
    "ChangeDriverInfoRequest",
    "ChangeServiceTypeDeliveryByClient",
    "ChangeServiceTypeDeliveryByCourier",
    "ChangeServiceTypeRequest",
    "ChangeServiceTypeRequestBase",
    "CitiesRequest",
    "CitiesResponse",
    "City",
    "CloseDeliveryOrderRequest",
    "CommitDraftRequest",
    "ConfirmDeliveryRequest",
    "CreateDraftRequest",
    "CreateOrSaveDraftResponse",
    "CreateOrderRequest",
    "CreateOrderSettings",
    "DeleteDraftRequest",
    "DeliveryGeocodeServiceType",
    "DeliveryOrder",
    "DeliveryOrderDraft",
    "DeliveryRestrictionItem",
    "DeliveryRestrictionRejectCode",
    "DeliveryRestrictions",
    "DeliveryRestrictionsCoordinates",
    "DeliveryRestrictionsMode",
    "DeliveryStatusForUpdate",
    "DeliveryZone",
    "DeliveryZoneAddressBinding",
    "FilterDraftsRequest",
    "FilterDraftsResponse",
    "GetAllowedRestrictionsRequest",
    "GetAllowedRestrictionsResponse",
    "GetDeliveryRestrictionsRequest",
    "GetDeliveryRestrictionsResponse",
    "GetDraftRequest",
    "GetDraftResponse",
    "HousesRange",
    "HousesRangeType",
    "LockOrUnlockDraftRequest",
    "MarketingSource",
    "MarketingSourcesRequest",
    "MarketingSourcesResponse",
    "OrderDraft",
    "OrderDraftSortProperty",
    "OrderLocation",
    "OrderPaymentItem",
    "OrderResponse",
    "OrderSortProperty",
    "OrdersByDeliveryDateAndFilterRequest",
    "OrdersByDeliveryDateAndPhoneRequest",
    "OrdersByDeliveryDateAndStatusRequest",
    "OrdersByIdRequest",
    "OrdersByOrganization",
    "OrdersByRevisionRequest",
    "OrdersHistoryByDeliveryDateAndPhoneRequest",
    "OrdersResponse",
    "OrdersWithRevisionResponse",
    "PrintBillRequest",
    "PrintDeliveryBillRequest",
    "Region",
    "RegionsRequest",
    "RegionsResponse",
    "RejectItem",
    "RejectItemData",
    "RestrictionsAddress",
    "RestrictionsOrderItem",
    "RestrictionsOrderItemModifier",
    "SaveDraftRequest",
    "SortDirection",
    "Street",
    "StreetById",
    "StreetsByCityRequest",
    "StreetsByIdRequest",
    "StreetsByIdResponse",
    "StreetsResponse",
    "UpdateDeliveryStatusRequest",
    "UpdateOrderCourierRequest",
    "UpdateOrderPaymentsRequest",
    "UpdateOrderProblemRequest",
    "UpdateTrackingLinkRequest",
]
