"""Models of the employee endpoints.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

from decimal import Decimal
from typing import Any

from pydantic import Field

from iikocloudapi._base import IikoModel


class AttendanceCreateRequest(IikoModel):
    """AttendanceCreateRequest."""

    attendance_type_id: str | None = None
    """Attendance type UUID"""
    comment: str | None = None
    """Comment"""
    employee_id: str
    """Employee UUID"""
    end_at: str
    """Date and time of the confirmed attendance end. If the value is `null`, the attendance is considered open. Existing attendances may be open."""
    is_confirmed_manually: bool | None = None
    """Manually confirmed flag; may be absent for legacy data."""
    organization_id: str
    """Organization UUID"""
    personal_end_at: str | None = None
    """Date and time of the registered attendance end from POS"""
    personal_start_at: str | None = None
    """Date and time of the registered attendance start from POS"""
    role_id: str
    """Role UUID; may be absent for legacy attendances"""
    start_at: str
    """Date and time of the confirmed attendance start"""


class AttendanceCreateResponse(IikoModel):
    """AttendanceCreateResponse."""

    attendance: AttendanceResponse | None = None
    """Attendance"""


class AttendanceDeleteRequest(IikoModel):
    """AttendanceDeleteRequest."""

    id: str
    """Attendance UUID"""
    organization_id: str
    """Organization UUID"""


class AttendanceDeleteResponse(IikoModel):
    """AttendanceDeleteResponse."""

    id: str | None = None
    """Attendance UUID"""


class AttendanceListRequest(IikoModel):
    """AttendanceListRequest."""

    attendance_type_ids: list[str] | None = None
    """Non-empty unique array of attendance type UUIDs to filter by"""
    employee_ids: list[str] | None = None
    """Non-empty unique array of employee UUIDs to filter by"""
    end_at: str
    """Date and time of the confirmed attendance end. If the value is `null`, the attendance is considered open. Existing attendances may be open."""
    is_closed: bool | None = None
    """Attendance closed flag. If absent in the request body - both closed and open attendances will be returned. If the value is `true` - only closed attendances will be returned (`endAt != null`). If the value is `false` - only open attendances will be returned (`endAt = null`)"""
    limit: int | None = None
    """Maximum number of records in the response (1..1000)"""
    offset: int | None = None
    """Number of records to skip from the beginning"""
    organization_id: str
    """Organization UUID"""
    should_include_payment_details: bool | None = None
    """Flag to display payment details"""
    start_at: str
    """Date and time of the confirmed attendance start"""


class AttendanceListResponse(IikoModel):
    """AttendanceListResponse."""

    items: list[AttendanceResponse] | None = None
    """Attendances"""
    limit: int | None = None
    """Maximum number of records in the response (1..1000)"""
    offset: int | None = None
    """Number of records to skip from the beginning"""
    total_count: int | None = None
    """Total number of records matching the selected filter rules"""


class AttendanceResponse(IikoModel):
    """AttendanceResponse."""

    attendance_type_code: str | None = None
    """Attendance type code"""
    attendance_type_id: str | None = None
    """Attendance type UUID"""
    comment: str | None = None
    """Comment"""
    created_at: str | None = None
    """Date and time of creation"""
    employee_id: str | None = None
    """Employee UUID"""
    end_at: str | None = None
    """Date and time of the confirmed attendance end. If the value is `null`, the attendance is considered open. Existing attendances may be open."""
    id: str | None = None
    """Attendance UUID"""
    is_closed: bool | None = None
    """Attendance closed flag. Computed as endAt != null"""
    is_confirmed_manually: bool | None = None
    """Manually confirmed flag; may be absent for legacy data"""
    modified_by_user_id: str | None = None
    """UUID of the user who made the last changes"""
    organization_id: str | None = None
    """Organization UUID"""
    organization_name: str | None = None
    """Organization name"""
    payment_details: PaymentDetails | None = None
    """Payment calculation; null if not requested or not applicable"""
    personal_end_at: str | None = None
    """Date and time of the registered attendance end from POS"""
    personal_start_at: str | None = None
    """Date and time of the registered attendance start from POS"""
    role_id: str | None = None
    """Role UUID; may be absent for legacy attendances"""
    start_at: str | None = None
    """Date and time of the confirmed attendance start"""
    updated_at: str | None = None
    """Date and time of the last modification"""


class AttendanceTypeItem(IikoModel):
    """AttendanceTypeItem."""

    code: str | None = None
    """Attendance type code"""
    comment: str | None = None
    """Description"""
    id: str | None = None
    """Attendance type UUID"""
    is_deleted: bool | None = None
    """Attendance type deleted flag"""
    is_presence: bool | None = None
    """Presence flag: the value `true` means the employee is present, the value `false` means the employee is absent"""
    name: str | None = None
    """Localized name"""
    pay_rate: Decimal | None = None
    """Payment coefficient"""


class AttendanceTypeListRequest(IikoModel):
    """AttendanceTypeListRequest."""

    is_deleted: bool | None = None
    """false — active, true — deleted, null — all"""
    limit: int | None = None
    """Maximum number of records in the response (1..1000)"""
    offset: int | None = None
    """Number of records to skip from the beginning"""


class AttendanceTypeListResponse(IikoModel):
    """AttendanceTypeListResponse."""

    items: list[AttendanceTypeItem] | None = None
    """Attendance types"""
    limit: int | None = None
    """Maximum number of records in the response (1..1000)"""
    offset: int | None = None
    """Number of records to skip from the beginning"""
    total_count: int | None = None
    """Total number of records matching the selected filter rules"""


class AttendanceUpdateRequest(IikoModel):
    """AttendanceUpdateRequest."""

    attendance_type_id: str
    """Attendance type UUID"""
    comment: str | None = None
    """Comment"""
    employee_id: str
    """Employee UUID"""
    end_at: str
    """Date and time of the confirmed attendance end. If the value is `null`, the attendance is considered open. Existing attendances may be open."""
    id: str
    """Attendance UUID"""
    is_confirmed_manually: bool
    """Manually confirmed flag; may be absent for legacy data"""
    organization_id: str
    """Organization UUID"""
    personal_end_at: str | None = None
    """Date and time of the registered attendance end from POS. An already set value cannot be reset (set to `null`)."""
    personal_start_at: str | None = None
    """Date and time of the registered attendance start from POS. An already set value cannot be reset (set to `null`)."""
    role_id: str
    """Role UUID; may be absent for legacy attendances"""
    start_at: str
    """Date and time of the confirmed attendance start"""


class AttendanceUpdateResponse(IikoModel):
    """AttendanceUpdateResponse."""

    attendance: AttendanceResponse | None = None
    """Attendance"""


class EmployeeCreateRequest(IikoModel):
    """EmployeeCreateRequest."""

    card_number: str | None = None
    """Card number"""
    code: str
    """Code"""
    email: str | None = None
    """E-mail"""
    first_name: str | None = None
    """First name"""
    hire_date: str | None = None
    """Employee hire date. Can be `null`"""
    last_name: str | None = None
    """Last name"""
    main_organization_id: str
    """Identifier (organizationId) of the employee's main organization"""
    main_role_id: str | None = None
    """Position identifier"""
    middle_name: str | None = None
    """Middle name"""
    name: str | None = None
    """Employee name in the system"""
    note: str | None = None
    """Notes"""
    organization_ids: list[str] | None = None
    """Identifiers (organizationId) of the employee's organizations"""
    phone: str | None = None
    """Phone"""
    responsible_for_organization_ids: list[str] | None = None
    """Identifiers (organizationId) of the organizations the employee is responsible for"""


class EmployeeFilter(IikoModel):
    """EmployeeFilter."""

    field: str | None = None
    """Field name to filter by. Possible values: `id`, `code`, `firstName`, `lastName`, `middleName`, `phone`, `email`, `mainRoleId`, `organizationId`, `isFired`"""
    value: str | None = None
    """Filter value"""


class EmployeeFireRequest(IikoModel):
    """EmployeeFireRequest."""

    ids: list[str]
    """List of employee identifiers to fire"""


class EmployeeFireResponse(IikoModel):
    """EmployeeFireResponse."""

    fired_ids: list[str] | None = None
    """List of fired employee identifiers"""


class EmployeeGetRequest(IikoModel):
    """EmployeeGetRequest."""

    id: str
    """Employee identifier"""


class EmployeeListRequest(IikoModel):
    """EmployeeListRequest."""

    fields_: list[str] | None = Field(default=None, alias="fields")
    """Requested response fields: `id`, `code`, `firstName`, `lastName`, `middleName`, `name`, `phone`, `email`, `cardNumber`, `mainRoleId`, `roleIds`, `isSystem`, `isFired`, `hireDate`, `fireDate`, `note`, `mainOrganizationId`, `organizationIds`, `responsibleForOrganizationIds`.

    If empty - returns 4 fields only: `id`, `name`, `code`, `isFired`.
    """
    filters: list[EmployeeFilter]
    """Filter fields."""
    limit: int | None = None
    """Maximum number of records in the response."""
    offset: int | None = None
    """Number of records to skip from the beginning."""


class EmployeePositionDTO(IikoModel):
    """EmployeePositionDTO."""

    can_work_by_substituted_card: bool | None = None
    """Allowed to work with a substituted card"""
    code: str | None = None
    """Employee position code"""
    id: str | None = None
    """Employee position identifier (GUID)"""
    is_deleted: bool | None = None
    """Flag indicating a deleted position"""
    name: str | None = None
    """Employee position name"""
    payment_per_hour: Decimal | None = None
    """Hourly payment rate"""
    schedule_type: str | None = None
    """Schedule type (HOURS, FIXED, SESSION, BYTIME)"""
    steady_salary: Decimal | None = None
    """Monthly salary amount"""


class EmployeePositionFilterItem(IikoModel):
    """EmployeePositionFilterItem."""

    field: str | None = None
    """Field name for filtering"""
    op: str | None = None
    """Operation ("eq", "ne", "gt", "gte", "lt", "lte", "in", "nin", "like", "blank", "notblank")"""
    value: Any | None = None
    """Value for filtering by the field"""
    values: list[Any] | None = None
    """Values for multi-value filtering ("in", "nin")"""


class EmployeePositionResponse(IikoModel):
    """EmployeePositionResponse."""

    can_work_by_substituted_card: bool | None = None
    """Allowed to work with a substituted card"""
    code: str | None = None
    """Employee position code"""
    id: str | None = None
    """Employee position identifier (GUID)"""
    is_deleted: bool | None = None
    """Flag indicating a deleted position"""
    name: str | None = None
    """Employee position name"""
    payment_per_hour: Decimal | None = None
    """Hourly payment rate"""
    schedule_type: str | None = None
    """Schedule type (HOURS, FIXED, SESSION, BYTIME)"""
    steady_salary: Decimal | None = None
    """Monthly salary amount"""


class EmployeeResponse(IikoModel):
    """EmployeeResponse."""

    card_number: str | None = None
    """Card number"""
    code: str | None = None
    """Code"""
    email: str | None = None
    """E-mail"""
    fire_date: str | None = None
    """Employee fire date. If `null`, the employee is not fired"""
    first_name: str | None = None
    """First name"""
    hire_date: str | None = None
    """Employee hire date. Can be `null`"""
    id: str | None = None
    """Employee identifier"""
    is_fired: bool | None = None
    """Flag indicating that the employee is fired. If `true` — the employee is fired"""
    is_system: bool | None = None
    """Flag indicating that the employee is a system employee. If `true` — the employee is a system employee"""
    last_name: str | None = None
    """Last name"""
    main_organization_id: str | None = None
    """Identifier (organizationId) of the employee's main organization"""
    main_role_id: str | None = None
    """Position identifier"""
    middle_name: str | None = None
    """Middle name"""
    name: str | None = None
    """Employee name in the system"""
    note: str | None = None
    """Notes"""
    organization_ids: list[str] | None = None
    """Identifiers (organizationId) of the employee's organizations"""
    phone: str | None = None
    """Phone"""
    responsible_for_organization_ids: list[str] | None = None
    """Identifiers (organizationId) of the organizations the employee is responsible for"""
    role_ids: list[str] | None = None
    """Employee position identifiers"""


class EmployeeRestoreRequest(IikoModel):
    """EmployeeRestoreRequest."""

    id: str
    """Employee identifier"""


class EmployeeRestoreResponse(IikoModel):
    """EmployeeRestoreResponse."""

    restored_ids: list[str] | None = None
    """List of restored employee identifiers"""


class EmployeeUpdateRequest(IikoModel):
    """EmployeeUpdateRequest."""

    card_number: str | None = None
    """Card number"""
    code: str | None = None
    """Code"""
    email: str | None = None
    """E-mail"""
    first_name: str | None = None
    """First name"""
    hire_date: str | None = None
    """Employee hire date. Can be `null`"""
    id: str
    """Employee identifier"""
    last_name: str | None = None
    """Last name"""
    main_organization_id: str | None = None
    """Identifier (organizationId) of the employee's main organization"""
    main_role_id: str | None = None
    """Position identifier"""
    middle_name: str | None = None
    """Middle name"""
    name: str | None = None
    """Employee name in the system"""
    note: str | None = None
    """Notes"""
    organization_ids: list[str] | None = None
    """Identifiers (organizationId) of the employee's organizations"""
    phone: str | None = None
    """Phone"""
    responsible_for_organization_ids: list[str] | None = None
    """Identifiers (organizationId) of the organizations the employee is responsible for"""


class GetPositionRequest(IikoModel):
    """GetPositionRequest."""

    id: str | None = None
    """Employee position identifier (GUID)"""
    revision_from: int | None = None
    """Revision from which to return changed records (optional)"""


class ListPositionsRequest(IikoModel):
    """ListPositionsRequest."""

    filters: list[EmployeePositionFilterItem] | None = None
    """List of filters (fields: isDeleted, scheduleTypes)"""
    limit: int | None = None
    """Maximum number of records in the response (default: 50, max: 1000)"""
    offset: int | None = None
    """Number of records to skip from the beginning (0-based)"""
    revision_from: int | None = None
    """Revision from which to return changed records (optional)"""


class ListPositionsResponse(IikoModel):
    """ListPositionsResponse."""

    items: list[EmployeePositionDTO] | None = None
    """List of employee positions"""
    limit: int | None = None
    """Maximum number of records in the response"""
    offset: int | None = None
    """Number of records to skip from the beginning (0-based)"""
    total_count: int | None = None
    """Total number of records matching the filter"""


class PaymentDetails(IikoModel):
    """PaymentDetails."""

    other_payments_sum: Decimal | None = None
    """Other payments/penalties"""
    overtime_paid_minutes: int | None = None
    """Overtime paid minutes"""
    overtime_payment_sum: Decimal | None = None
    """Overtime payment sum"""
    regular_paid_minutes: int | None = None
    """Regular paid minutes"""
    regular_payment_sum: Decimal | None = None
    """Regular payment sum"""


class SwaggerEmployeeListResponse(IikoModel):
    """SwaggerEmployeeListResponse."""

    items: list[EmployeeResponse] | None = None
    """Employees"""
    limit: int | None = None
    """Maximum number of records in the response."""
    offset: int | None = None
    """Number of records to skip from the beginning."""
    total_count: int | None = None
    """Total number of employees"""


__all__ = [
    "AttendanceCreateRequest",
    "AttendanceCreateResponse",
    "AttendanceDeleteRequest",
    "AttendanceDeleteResponse",
    "AttendanceListRequest",
    "AttendanceListResponse",
    "AttendanceResponse",
    "AttendanceTypeItem",
    "AttendanceTypeListRequest",
    "AttendanceTypeListResponse",
    "AttendanceUpdateRequest",
    "AttendanceUpdateResponse",
    "EmployeeCreateRequest",
    "EmployeeFilter",
    "EmployeeFireRequest",
    "EmployeeFireResponse",
    "EmployeeGetRequest",
    "EmployeeListRequest",
    "EmployeePositionDTO",
    "EmployeePositionFilterItem",
    "EmployeePositionResponse",
    "EmployeeResponse",
    "EmployeeRestoreRequest",
    "EmployeeRestoreResponse",
    "EmployeeUpdateRequest",
    "GetPositionRequest",
    "ListPositionsRequest",
    "ListPositionsResponse",
    "PaymentDetails",
    "SwaggerEmployeeListResponse",
]
