"""Models of the finance endpoints.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

from decimal import Decimal
from typing import Any

from pydantic import Field

from iikocloudapi._base import IikoModel
from iikocloudapi.models.common import FilterCondition


class Account(IikoModel):
    """Account."""

    code: str | None = None
    """Account code"""
    created_at: str | None = None
    """Creation date and time"""
    deleted_at: str | None = None
    """Deletion date and time"""
    description: str | None = None
    """Account description"""
    id: str | None = None
    """Account UUID. string (UUID)"""
    is_custom_transactions_allowed: bool | None = None
    """Whether custom transactions are allowed for the account"""
    is_deleted: bool | None = None
    """Deleted flag"""
    is_system_account: bool | None = None
    """Whether the account is a system account"""
    modified_at: str | None = None
    """Last modification date and time"""
    name: str | None = None
    """Display name"""
    parent_id: str | None = None
    """Parent account UUID"""
    revision: int | None = None
    """Revision"""
    start_balance_date: str | None = None
    """Start balance date (YYYY-MM-DD format)"""
    start_balance_sum: Decimal | None = None
    """Start balance amount"""
    type: str | None = None
    """Account type code"""


class AccountCreateRequest(IikoModel):
    """AccountCreateRequest."""

    code: str | None = None
    """Account code"""
    description: str
    """Account description"""
    is_custom_transactions_allowed: bool | None = None
    """Whether custom transactions are allowed for the account"""
    name: str
    """Display name"""
    parent_id: str | None = None
    """Parent account UUID"""
    start_balance_date: str
    """Start balance date (YYYY-MM-DD format)"""
    start_balance_sum: Decimal
    """Start balance amount"""
    type: str
    """Account type code"""


class AccountDeleteRequest(IikoModel):
    """AccountDeleteRequest."""

    id: str
    """Account UUID. string (UUID)"""


class AccountDeleteResponse(IikoModel):
    """AccountDeleteResponse."""

    id: str | None = None
    """Account UUID. string (UUID)"""
    is_deleted: bool | None = None
    """Deleted flag"""


class AccountFilter(IikoModel):
    """AccountFilter."""

    field: str | None = None
    """Field name to filter by"""
    op: str | None = None
    """Comparison operator: "eq" (equal), "ne" (not equal), "gt" (greater than), "gte" (greater than or equal), "lt" (less than), "lte" (less than or equal), "in" (value is in the list - uses values[]), "nin" (value is not in the list - uses values[]), "like" (substring search, case-insensitive), "blank" (null or empty string), "notblank" (neither null nor empty string)"""
    value: Any | None = None
    """Scalar value for filtering (used with eq, ne, gt, gte, lt, lte, like)"""
    values: list[str] | None = None
    """Array of values for multiple filtering (used with "in", "nin")"""


class AccountGetRequest(IikoModel):
    """AccountGetRequest."""

    id: str
    """Account UUID. string (UUID)"""


class AccountListRequest(IikoModel):
    """AccountListRequest."""

    filters: list[AccountFilter]
    """Request filters. All filters are applied simultaneously (AND)"""
    limit: int
    """Maximum number of records in the response."""
    offset: int
    """Number of records to skip from the beginning."""


class AccountListResponse(IikoModel):
    """AccountListResponse."""

    accounts: list[Account] | None = None
    """List of accounts"""
    count: int | None = None
    """Number of items returned in the response"""
    limit: int | None = None
    """Maximum number of records in the response."""
    offset: int | None = None
    """Number of records to skip from the beginning."""


class AccountPostingListRequest(IikoModel):
    """AccountPostingListRequest."""

    account_id: str | None = None
    """Financial account UUID. string (UUID)"""
    counteragent_id: str | None = None
    """Filter by counteragent UUID. string (UUID), nullable"""
    from_: str | None = Field(default=None, alias="from")
    """Period start date (YYYY-MM-DD)"""
    organization_ids: list[str] | None = None
    """List of organization UUIDs to filter by. string[] (UUID)"""
    to: str | None = None
    """Period end date (YYYY-MM-DD)"""


class AccountPostingListResponse(IikoModel):
    """AccountPostingListResponse."""

    account_id: str | None = None
    """Financial account UUID. string (UUID)"""
    can_edit: bool | None = None
    """Whether postings can be edited"""
    opening_balance_amount: Decimal | None = None
    """Opening balance at the start of the period. decimal"""
    period_change_amount: Decimal | None = None
    """Net change in balance over the period. decimal"""
    postings: list[Posting] | None = None
    """List of postings"""


class AccountResponse(IikoModel):
    """AccountResponse."""

    code: str | None = None
    """Account code"""
    created_at: str | None = None
    """Creation date and time"""
    deleted_at: str | None = None
    """Deletion date and time"""
    description: str | None = None
    """Account description"""
    id: str | None = None
    """Account UUID. string (UUID)"""
    is_custom_transactions_allowed: bool | None = None
    """Whether custom transactions are allowed for the account"""
    is_deleted: bool | None = None
    """Deleted flag"""
    is_system_account: bool | None = None
    """Whether the account is a system account"""
    modified_at: str | None = None
    """Last modification date and time"""
    name: str | None = None
    """Display name"""
    parent_id: str | None = None
    """Parent account UUID"""
    revision: int | None = None
    """Revision"""
    start_balance_date: str | None = None
    """Start balance date (YYYY-MM-DD format)"""
    start_balance_sum: Decimal | None = None
    """Start balance amount"""
    type: str | None = None
    """Account type code"""


class AccountRestoreRequest(IikoModel):
    """AccountRestoreRequest."""

    id: str
    """Account UUID. string (UUID)"""
    restore_descendants: bool
    """Flag to restore child accounts"""


class AccountRestoreResponse(IikoModel):
    """AccountRestoreResponse."""

    id: str | None = None
    """Account UUID. string (UUID)"""
    is_deleted: bool | None = None
    """Deleted flag"""
    restore_descendants: bool | None = None
    """Flag to restore child accounts"""


class AccountTransactionsListRequest(IikoModel):
    """AccountTransactionsListRequest."""

    account_id: str
    """Account ID. string (UUID). Required"""
    from_: str = Field(alias="from")
    """Period start date (YYYY-MM-DD format)"""
    organization_id: str
    """Organization identifier (GUID)"""
    to: str
    """Period end date (YYYY-MM-DD format)"""


class AccountTransactionsResponse(IikoModel):
    """AccountTransactionsResponse."""

    items: list[TransactionItem] | None = None
    """Array of transactions"""
    start_balance: Decimal | None = None
    """Opening (incoming) account balance at the start of the period. decimal"""
    sum_total: Decimal | None = None
    """Total amount of all transactions in the selection. decimal"""


class AccountType(IikoModel):
    """AccountType."""

    code: str | None = None
    """Account type code"""
    title: str | None = None
    """Account type title"""


class AccountTypeListRequest(IikoModel):
    """AccountTypeListRequest."""


class AccountUpdateRequest(IikoModel):
    """AccountUpdateRequest."""

    code: str | None = None
    """Account code"""
    description: str
    """Account description"""
    id: str
    """Account UUID. string (UUID)"""
    name: str
    """Display name"""
    parent_id: str | None = None
    """Parent account UUID"""
    start_balance_date: str
    """Start balance date (YYYY-MM-DD format)"""
    start_balance_sum: Decimal
    """Start balance amount"""
    type: str
    """Account type code"""


class BalanceItem(IikoModel):
    """BalanceItem."""

    account_id: str | None = None
    """Financial account UUID. string (UUID)"""
    balance_amount: Decimal | None = None
    """Account balance. decimal"""


class BalanceSheetListRequest(IikoModel):
    """BalanceSheetListRequest."""

    balance_at: str | None = None
    """Date to retrieve balances for (YYYY-MM-DD)"""
    organization_ids: list[str] | None = None
    """List of organization UUIDs to filter by. string[] (UUID)"""


class BalanceSheetListResponse(IikoModel):
    """BalanceSheetListResponse."""

    balance_at: str | None = None
    """Date to retrieve balances for (YYYY-MM-DD)"""
    balances: list[BalanceItem] | None = None
    """List of account balances"""


class CashFlowCategory(IikoModel):
    """CashFlowCategory."""

    code: str | None = None
    """Cash flow category code"""
    created_at: str | None = None
    """Creation date and time"""
    deleted_at: str | None = None
    """Deletion date and time"""
    id: str | None = None
    """Cash flow category UUID. string (UUID)"""
    is_deleted: bool | None = None
    """Deleted flag"""
    modified_at: str | None = None
    """Last modification date and time"""
    name: str | None = None
    """Display name"""
    parent_id: str | None = None
    """Parent cash flow category UUID"""
    revision: int | None = None
    """Revision"""
    type: str | None = None
    """Cash flow category type. Allowed values: `FINANCE`, `INVESTMENT`, `OPERATIONAL`"""


class CashFlowCategoryCascadeResponse(IikoModel):
    """CashFlowCategoryCascadeResponse."""

    affected_ids: list[str] | None = None
    """List of affected cash flow category identifiers"""
    id: str | None = None
    """Cash flow category UUID. string (UUID)"""
    is_deleted: bool | None = None
    """Deleted flag"""


class CashFlowCategoryCreateRequest(IikoModel):
    """CashFlowCategoryCreateRequest."""

    code: str
    """Cash flow category code"""
    name: str
    """Display name"""
    parent_id: str | None = None
    """Parent cash flow category UUID"""
    type: str
    """Cash flow category type. Allowed values: `FINANCE`, `INVESTMENT`, `OPERATIONAL`"""


class CashFlowCategoryDeleteRequest(IikoModel):
    """CashFlowCategoryDeleteRequest."""

    id: str
    """Cash flow category UUID. string (UUID)"""


class CashFlowCategoryFilter(IikoModel):
    """CashFlowCategoryFilter."""

    field: str | None = None
    """Field name to filter by"""
    op: str | None = None
    """Comparison operator: "eq" (equal), "ne" (not equal), "gt" (greater than), "gte" (greater than or equal), "lt" (less than), "lte" (less than or equal), "in" (value is in the list - uses values[]), "nin" (value is not in the list - uses values[]), "like" (substring search, case-insensitive), "blank" (null or empty string), "notblank" (neither null nor empty string)"""
    value: Any | None = None
    """Scalar value for filtering (used with eq, ne, gt, gte, lt, lte, like)"""
    values: list[str] | None = None
    """Array of values for multiple filtering (used with "in", "nin")"""


class CashFlowCategoryGetRequest(IikoModel):
    """CashFlowCategoryGetRequest."""

    id: str
    """Cash flow category UUID. string (UUID)"""


class CashFlowCategoryListRequest(IikoModel):
    """CashFlowCategoryListRequest."""

    filters: list[CashFlowCategoryFilter]
    """Request filters. All filters are applied simultaneously (AND)"""
    limit: int
    """Maximum number of records in the response."""
    offset: int
    """Number of records to skip from the beginning."""


class CashFlowCategoryListResponse(IikoModel):
    """CashFlowCategoryListResponse."""

    cash_flow_categories: list[CashFlowCategory] | None = None
    """List of cash flow categories"""
    count: int | None = None
    """Number of items returned in the response"""
    limit: int | None = None
    """Maximum number of records in the response."""
    offset: int | None = None
    """Number of records to skip from the beginning."""


class CashFlowCategoryResponse(IikoModel):
    """CashFlowCategoryResponse."""

    code: str | None = None
    """Cash flow category code"""
    created_at: str | None = None
    """Creation date and time"""
    deleted_at: str | None = None
    """Deletion date and time"""
    id: str | None = None
    """Cash flow category UUID. string (UUID)"""
    is_deleted: bool | None = None
    """Deleted flag"""
    modified_at: str | None = None
    """Last modification date and time"""
    name: str | None = None
    """Display name"""
    parent_id: str | None = None
    """Parent cash flow category UUID"""
    revision: int | None = None
    """Revision"""
    type: str | None = None
    """Cash flow category type. Allowed values: `FINANCE`, `INVESTMENT`, `OPERATIONAL`"""


class CashFlowCategoryRestoreRequest(IikoModel):
    """CashFlowCategoryRestoreRequest."""

    id: str
    """Cash flow category UUID. string (UUID)"""
    restore_descendants: bool
    """Flag to restore child accounts"""


class CashFlowCategoryUpdateRequest(IikoModel):
    """CashFlowCategoryUpdateRequest."""

    code: str
    """Cash flow category code"""
    id: str
    """Cash flow category UUID. string (UUID)"""
    name: str
    """Display name"""
    parent_id: str | None = None
    """Parent cash flow category UUID"""
    type: str
    """Cash flow category type. Allowed values: `FINANCE`, `INVESTMENT`, `OPERATIONAL`"""


class ChartOfAccount(IikoModel):
    """ChartOfAccount."""

    account_group: str | None = None
    """Account group: ASSETS, LIABILITIES, EQUITY, INCOME_EXPENSES"""
    account_type: str | None = None
    """Account type (ENUM)"""
    code: str | None = None
    """Account code"""
    description: str | None = None
    """Account description"""
    id: str | None = None
    """Account UUID. string (UUID)"""
    is_custom_transactions_allowed: bool | None = None
    """Whether custom transactions are allowed for the account"""
    is_deleted: bool | None = None
    """Deletion flag"""
    is_system_account: bool | None = None
    """Whether the account is a system account"""
    name: str | None = None
    """Display name"""
    parent_account_id: str | None = None
    """Parent account UUID. string (UUID), nullable"""


class ChartOfAccountsListRequest(IikoModel):
    """ChartOfAccountsListRequest."""

    account_type: str | None = None
    """Account type (ENUM)"""
    is_deleted: bool | None = None
    """Deletion flag"""


class ChartOfAccountsListResponse(IikoModel):
    """ChartOfAccountsListResponse."""

    accounts: list[ChartOfAccount] | None = None
    """List of accounts"""


class DocumentTransactionItem(IikoModel):
    """DocumentTransactionItem."""

    cash_flow_category: str | None = None
    """Cash flow category. string (UUID), or null"""
    cash_order_number: str | None = None
    """Cash order number. string, or null"""
    comment: str | None = None
    """Transaction comment. string, or null"""
    conception: str | None = None
    """Concept the transaction belongs to. string (UUID), or null"""
    date: str | None = None
    """Transaction accounting date and time. string (ISO 8601 YYYY-MM-DDThh:mm:ss±hh:mm)"""
    date_created: str | None = None
    """Transaction creation date. string (ISO 8601 YYYY-MM-DDThh:mm:ss±hh:mm)"""
    date_modified: str | None = None
    """Transaction last modified date. string (ISO 8601 YYYY-MM-DDThh:mm:ss±hh:mm), or null"""
    date_secondary: str | None = None
    """Secondary transaction date. string (ISO 8601 YYYY-MM-DDThh:mm:ss±hh:mm), or null"""
    document_id: str | None = None
    """Related document ID. string (UUID), or null"""
    document_item_id: str | None = None
    """Document item ID. string (UUID), or null"""
    from_: TransactionSide | None = Field(default=None, alias="from")
    """Transaction FROM (debit) side"""
    id: str | None = None
    """Transaction UUID. string (UUID)"""
    number: str | None = None
    """Related document or cash session number. string, or null"""
    session: str | None = None
    """Cash session in which the transaction was created. string (UUID), or null"""
    sum: Decimal | None = None
    """Transaction amount. decimal"""
    to: TransactionSide | None = None
    """Transaction TO (credit) side"""
    type: str | None = None
    """Transaction type, ENUM"""
    user_modified: str | None = None
    """User who last modified the transaction. string (UUID), or null"""


class DocumentTransactionsListRequest(IikoModel):
    """DocumentTransactionsListRequest."""

    document_id: str
    """Document identifier (GUID)"""
    organization_id: str
    """Organization identifier (GUID)"""


class IncomingServiceCreateItem(IikoModel):
    """IncomingServiceCreateItem."""

    amount: Decimal
    """Product quantity"""
    num: int
    """Item sequence number"""
    price: Decimal | None = None
    """Price including VAT. Required if sum is not specified"""
    product: str
    """Product identifier (GUID)"""
    revenue_account: str
    """Revenue account identifier (GUID)"""
    split_vat: bool | None = None
    """Split VAT accounting flag"""
    sum: Decimal | None = None
    """Amount including VAT. Required if price is not specified"""
    vat_percent: Decimal
    """VAT percentage"""


class IncomingServiceCreateRequest(IikoModel):
    """IncomingServiceCreateRequest."""

    comment: str | None = None
    """Comment"""
    conception: str | None = None
    """Concept identifier (GUID)"""
    contract_date: str | None = None
    """Contract date (ISO 8601 YYYY-MM-DDThh:mm:ss±hh:mm)"""
    contract_number: str | None = None
    """Contract number"""
    counteragent: str
    """Counteragent identifier (GUID)"""
    date: str
    """Document date and time (ISO 8601 YYYY-MM-DDThh:mm:ss.sss±hh:mm)"""
    document_id: str | None = None
    due_date: str | None = None
    """Payment due date"""
    employee_pass_to_account: str | None = None
    """Charge to employee"""
    incoming_date: str | None = None
    """Incoming document date (YYYY-MM-DD)"""
    incoming_document_number: str | None = None
    """Incoming external document number"""
    invoice: str | None = None
    """Invoice number"""
    is_automatic: bool | None = None
    """Automatic document creation flag"""
    is_editable: bool | None = None
    """Editable flag. true — available for editing"""
    items: list[IncomingServiceCreateItem]
    """List of document items"""
    number: str | None = None
    """Document number"""
    organization_id: str
    """Organization identifier (GUID)"""
    revenue_account: str | None = None
    """Revenue account identifier (GUID)"""


class IncomingServiceGetItem(IikoModel):
    """IncomingServiceGetItem."""

    amount: Decimal | None = None
    """Product quantity"""
    num: int | None = None
    """Item sequence number"""
    price: Decimal | None = None
    """Price including VAT. Required if sum is not specified"""
    price_without_vat: Decimal | None = None
    """Price excluding VAT"""
    product: str | None = None
    """Product identifier (GUID)"""
    product_article: str | None = None
    """Nomenclature article"""
    revenue_account: str | None = None
    """Revenue account identifier (GUID)"""
    split_vat: bool | None = None
    """Split VAT accounting flag"""
    sum: Decimal | None = None
    """Amount including VAT. Required if price is not specified"""
    sum_without_vat: Decimal | None = None
    """Amount excluding VAT"""
    vat_percent: Decimal | None = None
    """VAT percentage"""


class IncomingServiceGetResponse(IikoModel):
    """IncomingServiceGetResponse."""

    comment: str | None = None
    """Comment"""
    conception: str | None = None
    """Concept identifier (GUID)"""
    contract_date: str | None = None
    """Contract date (ISO 8601 YYYY-MM-DDThh:mm:ss±hh:mm)"""
    contract_number: str | None = None
    """Contract number"""
    counteragent: str | None = None
    """Counteragent identifier (GUID)"""
    date: str | None = None
    """Document date and time (ISO 8601 YYYY-MM-DDThh:mm:ss.sss±hh:mm)"""
    date_created: str | None = None
    """Document creation date (ISO 8601 YYYY-MM-DDThh:mm:ss.sss±hh:mm)"""
    date_modified: str | None = None
    """Document last modification date (ISO 8601 YYYY-MM-DDThh:mm:ss.sss±hh:mm)"""
    document_id: str | None = None
    """Document identifier (GUID)"""
    due_date: str | None = None
    """Payment due date"""
    employee_pass_to_account: str | None = None
    """Charge to employee"""
    incoming_date: str | None = None
    """Incoming document date (YYYY-MM-DD)"""
    incoming_document_number: str | None = None
    """Incoming external document number"""
    invoice: str | None = None
    """Invoice number"""
    is_automatic: bool | None = None
    """Automatic document creation flag"""
    is_editable: bool | None = None
    """Editable flag. true — available for editing"""
    items: list[IncomingServiceGetItem] | None = None
    """List of document items"""
    number: str | None = None
    """Document number"""
    revenue_account: str | None = None
    """Revenue account identifier (GUID)"""
    status: str | None = None
    """Document status (NEW — not processed, PROCESSED — processed, DELETED — deleted)"""
    sum: Decimal | None = None
    """Amount including VAT"""
    sum_without_vat: Decimal | None = None
    """Amount excluding VAT"""
    user_created: str | None = None
    """User who created the document (GUID)"""
    user_modified: str | None = None
    """User who last modified the document (GUID)"""


class IncomingServiceListItem(IikoModel):
    """IncomingServiceListItem."""

    comment: str | None = None
    """Comment"""
    conception: str | None = None
    """Concept identifier (GUID)"""
    counteragent: str | None = None
    """Counteragent identifier (GUID)"""
    date: str | None = None
    """Document date and time (ISO 8601 YYYY-MM-DDThh:mm:ss.sss±hh:mm)"""
    date_created: str | None = None
    """Document creation date (ISO 8601 YYYY-MM-DDThh:mm:ss.sss±hh:mm)"""
    date_modified: str | None = None
    """Document last modification date (ISO 8601 YYYY-MM-DDThh:mm:ss.sss±hh:mm)"""
    deleted: bool | None = None
    """Flag indicating that the document is deleted"""
    document_id: str | None = None
    """Document identifier (GUID)"""
    due_date: str | None = None
    """Payment due date"""
    is_editable: bool | None = None
    """Editable flag. true — available for editing"""
    number: str | None = None
    """Document number"""
    processed: bool | None = None
    """Flag indicating that the document is processed"""
    revenue_account: str | None = None
    """Revenue account identifier (GUID)"""
    sum: Decimal | None = None
    """Amount including VAT. Required if price is not specified"""
    sum_without_vat: Decimal | None = None
    """Amount excluding VAT"""
    user_created: str | None = None
    """User who created the document (GUID)"""
    user_modified: str | None = None
    """User who last modified the document (GUID)"""


class IncomingServiceSaveResponse(IikoModel):
    """IncomingServiceSaveResponse."""

    document_id: str | None = None
    """Document identifier (GUID)"""
    document_number: str | None = None
    """Document number"""
    message: str | None = None
    """Operation result message"""


class IncomingServiceUpdateRequest(IikoModel):
    """IncomingServiceUpdateRequest."""

    comment: str | None = None
    """Comment"""
    conception: str | None = None
    """Concept identifier (GUID)"""
    contract_date: str | None = None
    """Contract date (ISO 8601 YYYY-MM-DDThh:mm:ss±hh:mm)"""
    contract_number: str | None = None
    """Contract number"""
    counteragent: str
    """Counteragent identifier (GUID)"""
    date: str
    """Document date and time (ISO 8601 YYYY-MM-DDThh:mm:ss.sss±hh:mm)"""
    document_id: str
    """Document identifier (GUID)"""
    due_date: str | None = None
    """Payment due date"""
    employee_pass_to_account: str | None = None
    """Charge to employee"""
    incoming_date: str | None = None
    """Incoming document date (YYYY-MM-DD)"""
    incoming_document_number: str | None = None
    """Incoming external document number"""
    invoice: str | None = None
    """Invoice number"""
    is_automatic: bool | None = None
    """Automatic document creation flag"""
    is_editable: bool | None = None
    """Editable flag. true — available for editing"""
    items: list[IncomingServiceCreateItem]
    """List of document items"""
    number: str
    """Document number"""
    organization_id: str
    """Organization identifier (GUID)"""
    revenue_account: str | None = None
    """Revenue account identifier (GUID)"""


class ItemCategory(IikoModel):
    """ItemCategory."""

    code: str | None = None
    """Fiscal category code"""
    id: str | None = None
    """Fiscal category UUID. string (UUID)"""
    is_deleted: bool | None = None
    """Deleted flag"""
    name: str | None = None
    """Display name"""


class ItemCategoryListRequest(IikoModel):
    """ItemCategoryListRequest."""

    filters: list[FilterCondition] | None = None
    """Request filters. All filters are applied simultaneously (AND)"""
    limit: int | None = None
    """Maximum number of records in the response."""
    offset: int | None = None
    """Number of records to skip from the beginning."""


class ItemCategoryListResponse(IikoModel):
    """ItemCategoryListResponse."""

    items: list[ItemCategory] | None = None
    """List of fiscal categories"""
    limit: int | None = None
    """Maximum number of records in the response."""
    offset: int | None = None
    """Number of records to skip from the beginning."""
    total_count: int | None = None
    """Total number of records matching the filters"""


class OutgoingServiceCreateItem(IikoModel):
    """OutgoingServiceCreateItem."""

    amount: Decimal
    """Product quantity"""
    discount_sum: Decimal | None = None
    """Discount amount"""
    num: int
    """Item sequence number"""
    price: Decimal | None = None
    """Price including VAT. Required if sum is not specified"""
    product: str
    """Product identifier (GUID)"""
    revenue_account: str
    """Revenue account identifier (GUID)"""
    split_vat: bool | None = None
    """Split VAT accounting flag"""
    sum: Decimal | None = None
    """Amount including VAT. Required if price is not specified"""
    vat_percent: Decimal
    """VAT percentage"""


class OutgoingServiceCreateRequest(IikoModel):
    """OutgoingServiceCreateRequest."""

    comment: str | None = None
    """Comment"""
    conception: str | None = None
    """Concept identifier (GUID)"""
    contract_date: str | None = None
    """Contract date (ISO 8601 YYYY-MM-DDThh:mm:ss±hh:mm)"""
    contract_number: str | None = None
    """Contract number"""
    counteragent: str
    """Counteragent identifier (GUID)"""
    date: str
    """Document date and time (ISO 8601 YYYY-MM-DDThh:mm:ss.sss±hh:mm)"""
    document_id: str | None = None
    due_date: str | None = None
    """Payment due date"""
    is_automatic: bool | None = None
    """Automatic document creation flag"""
    is_editable: bool | None = None
    """Editable flag. true — available for editing"""
    items: list[OutgoingServiceCreateItem]
    """List of document items"""
    number: str | None = None
    """Document number"""
    organization_id: str
    """Organization identifier (GUID)"""
    revenue_account: str | None = None
    """Revenue account identifier (GUID)"""


class OutgoingServiceGetItem(IikoModel):
    """OutgoingServiceGetItem."""

    amount: Decimal | None = None
    """Product quantity"""
    discount_sum: Decimal | None = None
    """Discount amount"""
    num: int | None = None
    """Item sequence number"""
    price: Decimal | None = None
    """Price including VAT. Required if sum is not specified"""
    price_without_vat: Decimal | None = None
    """Price excluding VAT"""
    product: str | None = None
    """Product identifier (GUID)"""
    product_article: str | None = None
    """Nomenclature article"""
    revenue_account: str | None = None
    """Revenue account identifier (GUID)"""
    split_vat: bool | None = None
    """Split VAT accounting flag"""
    sum: Decimal | None = None
    """Amount including VAT. Required if price is not specified"""
    sum_without_vat: Decimal | None = None
    """Amount excluding VAT"""
    vat_percent: Decimal | None = None
    """VAT percentage"""


class OutgoingServiceGetResponse(IikoModel):
    """OutgoingServiceGetResponse."""

    comment: str | None = None
    """Comment"""
    conception: str | None = None
    """Concept identifier (GUID)"""
    contract_date: str | None = None
    """Contract date (ISO 8601 YYYY-MM-DDThh:mm:ss±hh:mm)"""
    contract_number: str | None = None
    """Contract number"""
    counteragent: str | None = None
    """Counteragent identifier (GUID)"""
    date: str | None = None
    """Document date and time (ISO 8601 YYYY-MM-DDThh:mm:ss.sss±hh:mm)"""
    date_created: str | None = None
    """Document creation date (ISO 8601 YYYY-MM-DDThh:mm:ss.sss±hh:mm)"""
    date_modified: str | None = None
    """Document last modification date (ISO 8601 YYYY-MM-DDThh:mm:ss.sss±hh:mm)"""
    document_id: str | None = None
    """Document identifier (GUID)"""
    due_date: str | None = None
    """Payment due date"""
    is_automatic: bool | None = None
    """Automatic document creation flag"""
    is_editable: bool | None = None
    """Editable flag. true — available for editing"""
    items: list[OutgoingServiceGetItem] | None = None
    """List of document items"""
    number: str | None = None
    """Document number"""
    revenue_account: str | None = None
    """Revenue account identifier (GUID)"""
    status: str | None = None
    """Document status (NEW — not processed, PROCESSED — processed, DELETED — deleted)"""
    sum: Decimal | None = None
    """Amount including VAT"""
    sum_without_vat: Decimal | None = None
    """Amount excluding VAT"""
    user_created: str | None = None
    """User who created the document (GUID)"""
    user_modified: str | None = None
    """User who last modified the document (GUID)"""


class OutgoingServiceListItem(IikoModel):
    """OutgoingServiceListItem."""

    comment: str | None = None
    """Comment"""
    conception: str | None = None
    """Concept identifier (GUID)"""
    counteragent: str | None = None
    """Counteragent identifier (GUID)"""
    date: str | None = None
    """Document date and time (ISO 8601 YYYY-MM-DDThh:mm:ss.sss±hh:mm)"""
    date_created: str | None = None
    """Document creation date (ISO 8601 YYYY-MM-DDThh:mm:ss.sss±hh:mm)"""
    date_modified: str | None = None
    """Document last modification date (ISO 8601 YYYY-MM-DDThh:mm:ss.sss±hh:mm)"""
    deleted: bool | None = None
    """Flag indicating that the document is deleted"""
    document_id: str | None = None
    """Document identifier (GUID)"""
    due_date: str | None = None
    """Payment due date"""
    is_editable: bool | None = None
    """Editable flag. true — available for editing"""
    number: str | None = None
    """Document number"""
    processed: bool | None = None
    """Flag indicating that the document is processed"""
    revenue_account: str | None = None
    """Revenue account identifier (GUID)"""
    sum: Decimal | None = None
    """Amount including VAT. Required if price is not specified"""
    sum_without_vat: Decimal | None = None
    """Amount excluding VAT"""
    user_created: str | None = None
    """User who created the document (GUID)"""
    user_modified: str | None = None
    """User who last modified the document (GUID)"""


class OutgoingServiceSaveResponse(IikoModel):
    """OutgoingServiceSaveResponse."""

    document_id: str | None = None
    """Document identifier (GUID)"""
    document_number: str | None = None
    """Document number"""
    message: str | None = None
    """Operation result message"""


class OutgoingServiceUpdateRequest(IikoModel):
    """OutgoingServiceUpdateRequest."""

    comment: str | None = None
    """Comment"""
    conception: str | None = None
    """Concept identifier (GUID)"""
    contract_date: str | None = None
    """Contract date (ISO 8601 YYYY-MM-DDThh:mm:ss±hh:mm)"""
    contract_number: str | None = None
    """Contract number"""
    counteragent: str
    """Counteragent identifier (GUID)"""
    date: str
    """Document date and time (ISO 8601 YYYY-MM-DDThh:mm:ss.sss±hh:mm)"""
    document_id: str
    """Document identifier (GUID)"""
    due_date: str | None = None
    """Payment due date"""
    is_automatic: bool | None = None
    """Automatic document creation flag"""
    is_editable: bool | None = None
    """Editable flag. true — available for editing"""
    items: list[OutgoingServiceCreateItem]
    """List of document items"""
    number: str
    """Document number"""
    organization_id: str
    """Organization identifier (GUID)"""
    revenue_account: str | None = None
    """Revenue account identifier (GUID)"""


class Posting(IikoModel):
    """Posting."""

    balance_amount: Decimal | None = None
    """Cumulative account balance after posting. decimal"""
    can_edit: bool | None = None
    """Whether the posting can be edited"""
    cash_flow_category_id: str | None = None
    """Cash flow category UUID. string (UUID), nullable"""
    cash_order_number: str | None = None
    """Cash order number. string, nullable"""
    comment: str | None = None
    """Posting comment. string, nullable"""
    conception_id: str | None = None
    """Conception UUID. string (UUID), nullable"""
    corresponding_account_id: str | None = None
    """Corresponding account UUID. string (UUID)"""
    counteragent_id: str | None = None
    """Counteragent UUID. string (UUID), nullable"""
    created_at: str | None = None
    """Creation date and time. string, nullable"""
    department_id: str | None = None
    """Department UUID. string (UUID), nullable"""
    document_at: str | None = None
    """Document date (YYYY-MM-DD)"""
    document_id: str | None = None
    """Document UUID. string (UUID), nullable"""
    document_number: str | None = None
    """Document number. string, nullable"""
    is_credit_side: bool | None = None
    """Credit side flag (true = credit, false = debit)"""
    modified_at: str | None = None
    """Last modification date and time. string, nullable"""
    modified_by_user_id: str | None = None
    """UUID of the user who last modified the posting. string (UUID), nullable"""
    posted_at: str | None = None
    """Actual posting date. string (YYYY-MM-DD), nullable"""
    posting_amount: Decimal | None = None
    """Posting amount. decimal"""
    posting_id: str | None = None
    """Posting UUID. string (UUID)"""
    posting_type: str | None = None
    """Posting type (ENUM)"""
    secondary_counteragent_id: str | None = None
    """Secondary counteragent UUID. string (UUID), nullable"""


class TaxCategory(IikoModel):
    """TaxCategory."""

    id: str | None = None
    """Tax category UUID. string (UUID)"""
    is_deleted: bool | None = None
    """Deleted flag"""
    name: str | None = None
    """Display name"""


class TaxCategoryListRequest(IikoModel):
    """TaxCategoryListRequest."""

    filters: list[FilterCondition] | None = None
    """Request filters. All filters are applied simultaneously (AND)"""
    limit: int | None = None
    """Maximum number of records in the response."""
    offset: int | None = None
    """Number of records to skip from the beginning."""


class TaxCategoryListResponse(IikoModel):
    """TaxCategoryListResponse."""

    items: list[TaxCategory] | None = None
    """List of tax categories"""
    limit: int | None = None
    """Maximum number of records in the response."""
    offset: int | None = None
    """Number of records to skip from the beginning."""
    total_count: int | None = None
    """Total number of records matching the filters"""


class TransactionItem(IikoModel):
    """TransactionItem."""

    account: str | None = None
    """Account or store. string (UUID)"""
    balance: Decimal | None = None
    """Accumulated account balance after this transaction. decimal"""
    cash_flow_category: str | None = None
    """Cash flow category. string (UUID), or null"""
    cash_order_number: str | None = None
    """Cash order number. string, or null"""
    cause_event_id: str | None = None
    """ID of the event that caused the transaction creation. string (UUID), or `null`"""
    comment: str | None = None
    """Transaction comment. string, or null"""
    conception: str | None = None
    """Concept the transaction belongs to. string (UUID), or null"""
    counteragent: str | None = None
    """Counteragent. string (UUID), or null"""
    date: str | None = None
    """Transaction accounting date and time. string (ISO 8601 YYYY-MM-DDThh:mm:ss±hh:mm)"""
    date_created: str | None = None
    """Transaction creation date. string (ISO 8601 YYYY-MM-DDThh:mm:ss±hh:mm)"""
    date_modified: str | None = None
    """Transaction last modified date. string (ISO 8601 YYYY-MM-DDThh:mm:ss±hh:mm), or null"""
    date_secondary: str | None = None
    """Secondary transaction date. string (ISO 8601 YYYY-MM-DDThh:mm:ss±hh:mm), or null"""
    document_id: str | None = None
    """Related document ID. string (UUID), or null"""
    document_type: str | None = None
    """Document type, ENUM"""
    number: str | None = None
    """Related document or cash session number. string, or null"""
    penalty_or_bonus_type: str | None = None
    """Penalty/bonus type — filled only for `PENALTY` / `BONUS` transactions. UUID, or `null`"""
    second_counteragent: str | None = None
    """Corresponding counteragent (employee/user) for the transaction. string (UUID), or `null`"""
    session: str | None = None
    """Cash session in which the transaction was created. string (UUID), or null"""
    sum: Decimal | None = None
    """Transaction amount. decimal"""
    terminal: str | None = None
    """Terminal on which the transaction was created. string (UUID), or `null`"""
    type: str | None = None
    """Transaction type, ENUM"""
    user_modified: str | None = None
    """User who last modified the transaction. string (UUID), or null"""


class TransactionSide(IikoModel):
    """TransactionSide."""

    account: str | None = None
    """Account or store. string (UUID)"""
    amount: Decimal | None = None
    """Product quantity. decimal, or null"""
    counteragent: str | None = None
    """Counteragent. string (UUID), or null"""
    product: str | None = None
    """Product. string (UUID), or null"""


__all__ = [
    "Account",
    "AccountCreateRequest",
    "AccountDeleteRequest",
    "AccountDeleteResponse",
    "AccountFilter",
    "AccountGetRequest",
    "AccountListRequest",
    "AccountListResponse",
    "AccountPostingListRequest",
    "AccountPostingListResponse",
    "AccountResponse",
    "AccountRestoreRequest",
    "AccountRestoreResponse",
    "AccountTransactionsListRequest",
    "AccountTransactionsResponse",
    "AccountType",
    "AccountTypeListRequest",
    "AccountUpdateRequest",
    "BalanceItem",
    "BalanceSheetListRequest",
    "BalanceSheetListResponse",
    "CashFlowCategory",
    "CashFlowCategoryCascadeResponse",
    "CashFlowCategoryCreateRequest",
    "CashFlowCategoryDeleteRequest",
    "CashFlowCategoryFilter",
    "CashFlowCategoryGetRequest",
    "CashFlowCategoryListRequest",
    "CashFlowCategoryListResponse",
    "CashFlowCategoryResponse",
    "CashFlowCategoryRestoreRequest",
    "CashFlowCategoryUpdateRequest",
    "ChartOfAccount",
    "ChartOfAccountsListRequest",
    "ChartOfAccountsListResponse",
    "DocumentTransactionItem",
    "DocumentTransactionsListRequest",
    "IncomingServiceCreateItem",
    "IncomingServiceCreateRequest",
    "IncomingServiceGetItem",
    "IncomingServiceGetResponse",
    "IncomingServiceListItem",
    "IncomingServiceSaveResponse",
    "IncomingServiceUpdateRequest",
    "ItemCategory",
    "ItemCategoryListRequest",
    "ItemCategoryListResponse",
    "OutgoingServiceCreateItem",
    "OutgoingServiceCreateRequest",
    "OutgoingServiceGetItem",
    "OutgoingServiceGetResponse",
    "OutgoingServiceListItem",
    "OutgoingServiceSaveResponse",
    "OutgoingServiceUpdateRequest",
    "Posting",
    "TaxCategory",
    "TaxCategoryListRequest",
    "TaxCategoryListResponse",
    "TransactionItem",
    "TransactionSide",
]
