"""Models of the license endpoints.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

from decimal import Decimal

from iikocloudapi._base import IikoDateTime, IikoModel


class GetLicenseListRequest(IikoModel):
    """Request to obtain the information on license list."""

    organization_ids: list[str] | None = None
    """Organization IDs for which license list information will be returned. By default - all organizations from API login."""


class GetLicenseListResponse(IikoModel):
    """Request to obtain the information on license list."""

    organization_licenses: list[OrganizationLicenseInfo]
    """List of organization license information."""
    correlation_id: str
    """Operation ID."""


class LicenseItem(IikoModel):
    """License Information of organization."""

    organization_id: str
    """UoC organization ID."""
    module_id: str
    """Id license module."""
    license_start: IikoDateTime | None = None
    """License start date."""
    expires: IikoDateTime | None = None
    """License end date."""
    quantity: Decimal
    """Number of license "slots"."""


class OrganizationLicenseInfo(IikoModel):
    """OrganizationLicenseInfo."""

    organization_id: str
    """Organization Id."""
    licenses: list[LicenseItem]
    """List of licenses."""


__all__ = [
    "GetLicenseListRequest",
    "GetLicenseListResponse",
    "LicenseItem",
    "OrganizationLicenseInfo",
]
