"""Models of the table order endpoints.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

from pydantic import Field

from iikocloudapi._base import IikoDateTime, IikoModel
from iikocloudapi.models.common import (
    ChequeAdditionalInfo,
    Combo,
    DiscountsInfo,
    ExternalData,
    Gender,
    LoyaltyInfo,
    OrderItem,
    OrderStatus,
    Payment,
    RegularCustomer,
    TableOrderInfo,
    TipsPayment,
)


class AddCustomerToTableOrderRequest(IikoModel):
    """Request for adding customer to order."""

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    order_id: str
    """Order ID."""
    customer: TableOrderCustomer
    """Guest info."""


class AddItemsToTableOrderRequest(IikoModel):
    """Request for add order items to table order."""

    add_order_items_settings: AddTableOrderItemsSettings | None = None
    """Add order items parameters."""
    order_id: str
    """Order ID."""
    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    items: list[OrderItem]
    """Order items (may include ProductOrderItem or CompoundOrderItem)."""
    combos: list[Combo] | None = None
    """Combos.

    Allowed from version `7.6.1`.
    """


class AddTableOrderItemsSettings(IikoModel):
    """Add table order items options."""

    service_print: bool | None = None
    """Auto service print is needed."""


class CancelTableOrderRequest(IikoModel):
    """Request to cancel a table order."""

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    order_id: str
    """Order ID."""
    removal_type_id: str | None = None
    """Removal type (used during deletion of printed order items)."""
    removal_comment: str | None = Field(default=None, min_length=0, max_length=255)
    """Comment to the charge-off."""
    user_id_for_writeoff: str | None = None
    """User for writeoff (used during deletion of printed order items)."""


class CloseTableOrderRequest(IikoModel):
    """Request for close table order."""

    cheque_additional_info: ChequeAdditionalInfo | None = None
    """Cheque additional information according to russian federal law #54."""
    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    order_id: str
    """Order ID."""


class CreateTableOrderRequest(IikoModel):
    """Order creation model."""

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    terminal_group_id: str
    """Front group ID an order must be sent to.

    Can be obtained by `/api/1/terminal_groups` operation.
    """
    order: TableOrder | None = None
    """Order."""
    create_order_settings: CreateTableOrderSettings | None = None
    """Order creation parameters."""


class CreateTableOrderSettings(IikoModel):
    """Table order creation options"""

    service_print: bool | None = None
    """Auto service print is needed."""
    transport_to_front_timeout: int | None = None
    """Timeout in seconds that specifies how much time is given for order to reach iikoFront.
    After this time, order is nullified if iikoFront doesn't take it. By default - 8 seconds.
    """
    check_stop_list: bool | None = None
    """Flag indicating whether there's need to check order items in out-of-stock list.

    Unable if `terminalGroupId` is null.
    """


class GetTableOrdersByIdRequest(IikoModel):
    """Request for information about orders using IDs."""

    source_keys: list[str] | None = None
    """Source keys."""
    organization_ids: list[str]
    """Organization IDs.

    Can be obtained by `/api/1/organizations` operation.
    """
    order_ids: list[str] | None = None
    """Order IDs.

    Required if "posOrderIds" is null. Must be null if "posOrderIds" is not null.
    """
    pos_order_ids: list[str] | None = None
    """POS order IDs.

    Required if "orderIds" is null. Must be null if "orderIds" is not null.
    """
    return_external_data_keys: list[str] | None = None
    """Keys for retrun external data information."""


class GetTableOrdersByTableRequest(IikoModel):
    """Request for information about orders using table IDs."""

    source_keys: list[str] | None = None
    """Source keys."""
    organization_ids: list[str]
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    table_ids: list[str]
    """Table IDs.

    Can be obtained by `/api/1/reserve/available_restaurant_sections` operation.
    """
    statuses: list[OrderStatus] | None = None
    """Order statuses."""
    date_from: IikoDateTime | None = None
    """Order creation date (terminal time zone). Lower limit.

    Order details are stored for 90 days.
    """
    date_to: IikoDateTime | None = None
    """Order creation date (terminal time zone). Upper limit."""


class GuestsInfo(IikoModel):
    """Table order guests information."""

    count: int
    """Guests count."""


class InitTableOrderByPosOrderRequest(IikoModel):
    """Request for init orders on table by POS orders."""

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    terminal_group_id: str
    """Terminal group ID.

    Can be obtained by `/api/1/terminal_groups` operation.
    """
    pos_order_ids: list[str]
    """POS order IDs."""


class InitTableOrderRequest(IikoModel):
    """Request for init orders on table."""

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    terminal_group_id: str
    """Terminal group ID.

    Can be obtained by `/api/1/terminal_groups` operation.
    """
    table_ids: list[str]
    """Table IDs.

    Can be obtained by `/api/1/reserve/available_restaurant_sections` operation.
    """


class TableOrder(IikoModel):
    """TableOrder."""

    id: str | None = None
    """Order ID."""
    external_number: str | None = Field(default=None, min_length=0, max_length=50)
    """Order external number.

    Allowed from version `8.0.6`.
    """
    table_ids: list[str] | None = None
    """Table IDs.

    Can be obtained by `/api/1/reserve/available_restaurant_sections` operation.
    """
    customer: RegularCustomer | None = None
    """Guest.

    Allowed from version `7.5.2`.
    """
    phone: str | None = None
    """Guest phone.

    Allowed from version `7.5.2`.
    """
    guest_count: int | None = None
    """**Deprecated.** Amount of guests in the order.

    Allowed from version `7.6.1`.
    """
    guests: GuestsInfo | None = None
    """Guests information.

    Allowed from version `7.6.1`.
    """
    tab_name: str | None = None
    """Tab name (only for fastfood terminals group in tab mode).

    Allowed from version `7.6.1`.
    """
    menu_id: str | None = None
    """External menu ID."""
    price_category_id: str | None = None
    """Price category id of the order.

    Can be obtained by `/api/2/menu` operation.

    Allowed from version `9.0.5`.
    """
    items: list[OrderItem]
    """Order items."""
    combos: list[Combo] | None = None
    """Combos included in order."""
    payments: list[Payment] | None = None
    """Order payment components.

    Type **LoyaltyCard** allowed from version `7.1.5`.
    """
    tips: list[TipsPayment] | None = None
    """Order tips components."""
    source_key: str | None = None
    """The string key (marker) of the source (partner - api user) that created the order. Needed to limit the visibility of orders for external integration."""
    discounts_info: DiscountsInfo | None = None
    """Discounts/surcharges."""
    loyalty_info: LoyaltyInfo | None = None
    """Information about Loyalty app."""
    order_type_id: str | None = None
    """Order type ID.

    Can be obtained by `/api/1/deliveries/order_types` operation
    """
    cheque_additional_info: ChequeAdditionalInfo | None = None
    """Cheque additional information."""
    external_data: list[ExternalData] | None = None
    """Order external data.

    Allowed from version `8.0.6`.
    """


class TableOrderCustomer(IikoModel):
    """TableOrderCustomer."""

    id: str | None = None
    """Existing customer ID in RMS.
    If null - the phone number and name is searched in database, otherwise the new customer is created in RMS.
    """
    name: str | None = Field(default=None, min_length=0, max_length=60)
    """Name of customer.
    Required if "id" == null.
    Not required if "id" specified.
    """
    surname: str | None = Field(default=None, min_length=0, max_length=60)
    """Last name."""
    comment: str | None = Field(default=None, min_length=0, max_length=60)
    """Comment."""
    birthdate: IikoDateTime | None = None
    """Date of birth."""
    email: str | None = None
    """Email."""
    should_receive_order_status_notifications: bool | None = None
    """Whether customer receives order status notification messages."""
    gender: Gender | None = None
    """Gender."""
    phone: str | None = None
    """Customer phone.
    Required if "id" == null.
    Not required if "id" specified.
    """


class TableOrderResponse(IikoModel):
    """Wrapping object (external) for a delivery order return."""

    correlation_id: str
    """Operation ID."""
    order_info: TableOrderInfo
    """Order."""


class TableOrdersResponse(IikoModel):
    """Wrapping object (external) for return of orders."""

    correlation_id: str
    """Operation ID."""
    orders: list[TableOrderInfo]
    """Orders."""


__all__ = [
    "AddCustomerToTableOrderRequest",
    "AddItemsToTableOrderRequest",
    "AddTableOrderItemsSettings",
    "CancelTableOrderRequest",
    "CloseTableOrderRequest",
    "CreateTableOrderRequest",
    "CreateTableOrderSettings",
    "GetTableOrdersByIdRequest",
    "GetTableOrdersByTableRequest",
    "GuestsInfo",
    "InitTableOrderByPosOrderRequest",
    "InitTableOrderRequest",
    "TableOrder",
    "TableOrderCustomer",
    "TableOrderResponse",
    "TableOrdersResponse",
]
