"""Models of the platform endpoints.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any

from iikocloudapi._base import IikoModel, IsoDateTime


class EventAttributeDoc(IikoModel):
    """EventAttributeDoc."""

    code: str | None = None
    """Attribute code"""
    value: Any | None = None
    """Attribute value. The type depends on valueType: `bool` | `string` | `int` | `float` | `date` | `guid`"""


class EventGroup(IikoModel):
    """EventGroup."""

    code: str | None = None
    """Event group code"""
    event_types: list[EventType] | None = None
    """Event types of the group"""
    name: str | None = None
    """Event group name"""


class EventListItem(IikoModel):
    """EventListItem."""

    attributes: list[EventAttributeDoc] | None = None
    """Event attributes"""
    event_type: str | None = None
    """Event type code"""
    id: str | None = None
    """Event identifier (UUID), unique"""
    occurred_at: str | None = None
    """Event date and time"""
    source: str | None = None
    """Data source: `RMS` if organizationId is provided in the request, otherwise `Chain`"""


class EventListRequest(IikoModel):
    """EventListRequest."""

    event_types: list[str] | None = None
    """Event codes to filter by. If omitted or empty, all events are returned"""
    from_revision: int | None = None
    """Revision to request events from (incremental mode), must be zero or greater. Required unless both fromTime and toTime are provided. Cannot be combined with fromTime/toTime"""
    from_time: IsoDateTime | None = None
    """Period start, inclusive, date-time format. Required together with toTime when fromRevision is not provided"""
    organization_id: str | None = None
    """Organization identifier (GUID). If provided, the request goes to the RMS API; otherwise to the Chain API by userContext.uocId"""
    to_time: IsoDateTime | None = None
    """Period end, exclusive, date-time format. Required together with fromTime when fromRevision is not provided"""


class EventListResponse(IikoModel):
    """EventListResponse."""

    items: list[EventListItem] | None = None
    revision: int | None = None
    """Revision up to which events are returned inclusively. Use revision + 1 for the next request"""
    total_count: int | None = None
    """Total number of events in the response"""


class EventMetadataListRequest(IikoModel):
    """EventMetadataListRequest."""


class EventMetadataListResponse(IikoModel):
    """EventMetadataListResponse."""

    event_groups: list[EventGroup] | None = None
    """Event groups"""
    total_count: int | None = None
    """Total number of event groups"""


class EventType(IikoModel):
    """EventType."""

    code: str | None = None
    """Event type code"""
    name: str | None = None
    """Event type name"""
    severity: int | None = None
    """Event severity level"""


__all__ = [
    "EventAttributeDoc",
    "EventGroup",
    "EventListItem",
    "EventListRequest",
    "EventListResponse",
    "EventMetadataListRequest",
    "EventMetadataListResponse",
    "EventType",
]
