"""Models of the reporting endpoints.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

import datetime
from decimal import Decimal
from typing import Any

from pydantic import Field

from iikocloudapi._base import IikoModel


class GetIncomePlanRequest(IikoModel):
    """GetIncomePlanRequest."""

    date_from: datetime.date
    """Period start date (inclusive)"""
    date_to: datetime.date
    """Period end date (inclusive)"""
    organization_id: str
    """Organization (department) identifier; used to resolve the plan"""


class GetIncomePlanResponse(IikoModel):
    """GetIncomePlanResponse."""

    items: list[IncomePlanItem] | None = None
    """Daily planned values"""


class GetOlapColumnsRequest(IikoModel):
    """GetOlapColumnsRequest."""

    report_type: str
    """Report type: `SALES` — sales, `TRANSACTIONS` — transactions, `DELIVERIES` — deliveries"""


class GetOlapReportRequest(IikoModel):
    """GetOlapReportRequest."""

    aggregate_fields: list[str]
    """Non-empty list of fields to aggregate by (`FieldName` names from `columns/get`)"""
    build_summary: bool | None = None
    """Whether to build totals"""
    filters: list[OlapFilterDoc]
    """Report filters: an array of filter structures; each contains name (`FieldName` from `columns/get`) and `filterType`, remaining fields depend on filterType (see filter models); at least one `DateRange` filter by the `OpenDate.Typed` field is required. For periodType = CUSTOM the period is limited to 31 days inclusive."""
    group_by_col_fields: list[str] | None = None
    """Fields to group columns by (`FieldName` names from `columns/get`)"""
    group_by_row_fields: list[str] | None = None
    """Fields to group rows by (`FieldName` names from `columns/get`)"""
    report_type: str
    """Report type: `SALES` — sales, `TRANSACTIONS` — transactions, `DELIVERIES` — deliveries"""


class GetOlapReportResponse(IikoModel):
    """GetOlapReportResponse."""

    data: list[dict[str, Any]] | None = None
    """Linear report data (row by row)"""
    summary: list[Any] | None = None
    """Intermediate and grand totals of the report"""


class IncomePlanItem(IikoModel):
    """IncomePlanItem."""

    date: datetime.date | None = None
    """Date for which the plan is set"""
    plan_value: Decimal | None = None
    """Planned value: amount for ABSOLUTE, percentage for PERCENT, or automatically calculated value for AUTOMATIC"""
    value_type: str | None = None
    """Value type: ABSOLUTE — amount, PERCENT — percentage, AUTOMATIC — automatic calculation"""


class OlapColumn(IikoModel):
    """OlapColumn."""

    can_aggregate: bool | None = None
    """Whether aggregation is allowed for the column"""
    can_filter: bool | None = None
    """Whether filtering is allowed for the column"""
    can_group: bool | None = None
    """Whether grouping is allowed for the column"""
    display_name: str | None = None
    """Report column name"""
    name: str | None = None
    """Field name (`FieldName`): used in `groupByRowFields`/`groupByColFields`/`aggregateFields`, grouping and filters"""
    tags: list[str] | None = None
    """Report categories the field belongs to"""
    type: str | None = None
    """Field type (`ENUM`, `STRING`, `ID`, `DATETIME`, `INTEGER`, `PERCENT`, `DURATION_IN_SECONDS`, etc.)"""


class OlapFilterDoc(IikoModel):
    """One item of the filters array. Which fields are actually present depends on `filterType`: name and `filterType` are always present; `values` — for IncludeValues/ExcludeValues; `from`/`to` — a number for `Range` or a date string in `yyyy-MM-dd` format for `DateRange`; `periodType` — for `DateRange`; `includeLow`/`includeHigh` — for `Range` and `DateRange`"""

    filter_type: str
    """Filter type: `IncludeValues`/`ExcludeValues` — by values, `Range` — by numeric range, `DateRange` — by date range"""
    from_: Any | None = Field(default=None, alias="from")
    """Lower range bound: a number (`Range`) or a date (`DateRange`) in `yyyy-MM-dd` format. For periodType = CUSTOM the period is limited to 31 days inclusive."""
    include_high: bool | None = None
    """Whether to include the upper range bound; defaults to `false`"""
    include_low: bool | None = None
    """Whether to include the lower range bound; defaults to `true`"""
    name: str
    """Field name to filter by (`FieldName` from `columns/get`)"""
    period_type: str | None = None
    """Period type (for `DateRange`): `CUSTOM`, `OPEN_PERIOD`, `TODAY`, `YESTERDAY`, `CURRENT_WEEK`, `CURRENT_MONTH`, `CURRENT_YEAR`, `LAST_WEEK`, `LAST_MONTH`, `LAST_YEAR`"""
    to: Any | None = None
    """Upper range bound: a number (`Range`) or a date (`DateRange`) in `yyyy-MM-dd` format; required for `Range` and for `DateRange` with `periodType=CUSTOM`. For periodType = CUSTOM the period is limited to 31 days inclusive."""
    values: list[str] | None = None
    """Field values to filter by; required for `IncludeValues`/`ExcludeValues` `filterType`"""


class OlapPreset(IikoModel):
    """OlapPreset."""

    name: str | None = None
    """Name of the saved OLAP preset set by the restaurant owner"""
    preset_id: str | None = None
    """Identifier of the saved OLAP preset; used in the `olap/presets/get` method to retrieve its data"""


class OlapPresetReportRequest(IikoModel):
    """OlapPresetReportRequest."""

    date_from: str
    """Start of the report period (inclusive) in `yyyy-MM-dd` format"""
    date_to: str
    """End of the report period (exclusive) in `yyyy-MM-dd` format"""
    preset_id: str
    """Identifier of the saved OLAP preset (from `olap/presets/list`)"""


class OlapPresetsListRequest(IikoModel):
    """OlapPresetsListRequest."""


__all__ = [
    "GetIncomePlanRequest",
    "GetIncomePlanResponse",
    "GetOlapColumnsRequest",
    "GetOlapReportRequest",
    "GetOlapReportResponse",
    "IncomePlanItem",
    "OlapColumn",
    "OlapFilterDoc",
    "OlapPreset",
    "OlapPresetReportRequest",
    "OlapPresetsListRequest",
]
