"""Models of the banquet/reserve endpoints.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

from decimal import Decimal

from pydantic import Field

from iikocloudapi._base import IikoDateTime, IikoModel, OpenStrEnum
from iikocloudapi.models.common import (
    ChequeAdditionalInfo,
    Combo,
    DiscountsInfo,
    ExternalData,
    LoyaltyInfo,
    OrderItem,
    Payment,
    RegularCustomer,
    ReserveCancelReason,
    ReserveInfo,
    TipsPayment,
)


class FontStyle(OpenStrEnum):
    """Font style."""

    REGULAR = "Regular"
    BOLD = "Bold"
    ITALIC = "Italic"
    UNDERLINE = "Underline"
    STRIKEOUT = "Strikeout"


class AddOrderItemsToBanquetRequest(IikoModel):
    """Request for add order items to banquet."""

    reserve_id: str
    """Banquet ID."""
    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    items: list[OrderItem]
    """Order items (may include ProductOrderItem or CompoundOrderItem)."""
    combos: list[Combo] | None = None
    """Combos.

    Allowed from version `7.6.1`.
    """


class AddOrderPaymentsToBanquetRequest(IikoModel):
    """Request for add order payments to banquet."""

    reserve_id: str
    """Reserve ID."""
    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    payments: list[Payment]
    """Order payments."""


class CancelReserveRequest(IikoModel):
    """Request for canceling the reservation."""

    organization_id: str
    """Organization ID of the reserve.

    Can be obtained by `/api/1/organizations` operation.
    """
    reserve_id: str
    """Reserve ID to cancel."""
    cancel_reason: ReserveCancelReason
    """Reason to cancel planned event."""


class ChangeBanquetOrderItemsRequest(IikoModel):
    """Request to change banquet order items."""

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    reserve_id: str
    """Banquet ID."""
    items: list[OrderItem] | None = None
    """Order items (may include ProductOrderItem or CompoundOrderItem)."""
    combos: list[Combo] | None = None
    """Combos."""


class ChangeReserveEstimatedStartTimeRequest(IikoModel):
    """Request to change reserve/banquet estimated start time."""

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    reserve_id: str
    """Reserve/banquet ID."""
    new_estimated_start_time: IikoDateTime
    """New estimated start time of reserve/banquet."""


class ChangeReserveTablesRequest(IikoModel):
    """Request to change reserve/banquet tables."""

    organization_id: str
    """Organization ID.

    Can be obtained by `/api/1/organizations` operation.
    """
    reserve_id: str
    """Reserve ID."""
    table_ids: list[str]
    """Table IDs."""


class Color(IikoModel):
    """Color."""

    a: int
    """Alpha-component."""
    r: int
    """Red-component."""
    g: int
    """Green-component."""
    b: int
    """Blue-component."""


class CreateOrderSettingsBase(IikoModel):
    """CreateOrderSettingsBase."""

    transport_to_front_timeout: int | None = None
    """Timeout in seconds that specifies how much time is given for order to reach iikoFront.
    After this time, order is nullified if iikoFront doesn't take it. By default - 8 seconds.
    """
    check_stop_list: bool | None = None
    """Flag indicating whether there's need to check order items in out-of-stock list.

    Unable if `terminalGroupId` is null.
    """


class CreateReserveRequest(IikoModel):
    """Banquet/reserve creation model."""

    organization_id: str
    """Organization ID of a new banquet/reserve.

    Can be obtained by `/api/1/organizations` operation.
    """
    terminal_group_id: str | None = None
    """Front group ID an banquet/reserve must be sent to.

    Can be obtained by `/api/1/terminal_groups` operation.
    """
    id: str | None = None
    """Banquet/reserve ID. Must be unique."""
    external_number: str | None = Field(default=None, min_length=0, max_length=50)
    """Banquet/reserve external number.

    Allowed from version `8.0.6`.
    """
    order: ReserveOrder | None = None
    """Order. Used only at a banquet."""
    customer: RegularCustomer
    """Customer."""
    phone: str
    """Telephone number.
    Must begin with symbol "+" and must be at least 8 digits.
    """
    guests_count: int | None = None
    """**Deprecated.** Number of guests."""
    comment: str | None = None
    """Banquet/reserve comment."""
    duration_in_minutes: int
    """Estimated banquet duration."""
    should_remind: bool
    """Whether to remind staff to prepare table beforehand."""
    table_ids: list[str]
    """Reserved tables."""
    estimated_start_time: IikoDateTime
    """Estimated time when reserve will be closed or banquet will be started (Local for the terminal).
    Reservation can be made up to 90 days prior to the date.
    """
    transport_to_front_timeout: int | None = None
    """**Deprecated.** Timeout in seconds that specifies how much time is given for banquet/reserve to reach iikoFront.
    After this time, banquet/reserve is nullified if iikoFront doesn't take it. By default - 8 seconds.
    """
    guests: ReserveGuestsInfo | None = None
    """Guests information."""
    event_type: str | None = Field(default=None, min_length=0, max_length=160)
    """Event type.

    Allowed from version `8.5.6`.
    """
    create_reserve_settings: CreateOrderSettingsBase | None = None
    """Reserve creation parameters."""


class Font(IikoModel):
    """Font."""

    font_family: str
    """Font family."""
    size: Decimal
    """Font size."""
    font_style: FontStyle
    """Font style. May be multiple values."""


class GetRestaurantSectionsRequest(IikoModel):
    """Request for get all restaurant sections of specified terminal groups, for which banquet/reserve booking are available."""

    terminal_group_ids: list[str]
    """Collection of terminal group ID.

    Can be obtained by `/api/1/terminal_groups` operation.
    """
    return_schema: bool | None = None
    """Indicates whether table layout information should be returned..."""
    revision: int | None = None
    """Last modified time after."""


class GetRestaurantSectionsResponse(IikoModel):
    """Response which contains all restaurant sections of specified terminal groups for which banquet/reserve booking are available."""

    correlation_id: str
    """Operation ID."""
    restaurant_sections: list[RestaurantSection]
    """Restaurant sections."""
    revision: int
    """Items list revision."""


class GetRestaurantSectionsWorkloadRequest(IikoModel):
    """Request for check restaurant sections workload."""

    restaurant_section_ids: list[str]
    """Collection of restaurant section ID.

    Can be obtained by `/api/1/reserve/available_restaurant_sections` operation.
    """
    date_from: IikoDateTime
    """Estimated start time (Local for the terminal). Lower limit.

    Order details are stored for 90 days.
    """
    date_to: IikoDateTime | None = None
    """Estimated start time (Local for the terminal). Upper limit."""


class GetRestaurantSectionsWorkloadResponse(IikoModel):
    """Response for check restaurant sections workload."""

    correlation_id: str
    """Operation ID."""
    reserves: list[ReserveInWorkload]
    """Banquets/reserves."""


class GetTerminalGroupsByOrganizationsRequest(IikoModel):
    """Request for list of terminal groups."""

    organization_ids: list[str]
    """Organizations IDs for which information is requested.

    Can be obtained by `/api/1/organizations` operation.
    """


class ReserveGuestsInfo(IikoModel):
    """Reserve guests information."""

    count: int
    """Guests count."""


class ReserveInWorkload(IikoModel):
    """Banquet/reserve."""

    id: str
    """Banquet/reserve ID."""
    table_ids: list[str]
    """Reserved tables."""
    estimated_start_time: IikoDateTime
    """Estimated time when reserve will be closed or banquet will be started (Local for the terminal)."""
    duration_in_minutes: int
    """Estimated banquet duration."""
    guests_count: int
    """Number of guests."""


class ReserveOrder(IikoModel):
    """Order."""

    menu_id: str | None = None
    """External menu ID."""
    items: list[OrderItem]
    """Order items."""
    combos: list[Combo] | None = None
    """Combos included in order."""
    payments: list[Payment] | None = None
    """Order payment components.

    Type **LoyaltyCard** allowed from version `7.1.5`.
    """
    tips: list[TipsPayment] | None = None
    """Order tips components."""
    source_key: str | None = None
    """The string key (marker) of the source (partner - api user) that created the order. Needed to limit the visibility of orders for external integration."""
    discounts_info: DiscountsInfo | None = None
    """Discounts/surcharges."""
    loyalty_info: LoyaltyInfo | None = None
    """Information about Loyalty app."""
    order_type_id: str | None = None
    """Order type ID.

    Can be obtained by `/api/1/deliveries/order_types` operation
    """
    cheque_additional_info: ChequeAdditionalInfo | None = None
    """Cheque additional information."""
    external_data: list[ExternalData] | None = None
    """Order external data.

    Allowed from version `8.0.6`.
    """


class ReserveResponse(IikoModel):
    """Wrapping object (external) for return of banquets/reserves."""

    correlation_id: str
    reserve_info: ReserveInfo
    """Banquet/reserve."""


class ReservesByIdRequest(IikoModel):
    """Request for information about banquets/reserves using IDs."""

    organization_id: str
    """Organization ID for which an order search will be performed.

    Can be obtained by `/api/1/organizations` operation.
    """
    reserve_ids: list[str]
    """IDs of banquets/reserves information on which is required."""
    source_keys: list[str] | None = None
    """Source keys."""


class ReservesResponse(IikoModel):
    """Wrapping object (external) for return of banquets/reserves."""

    correlation_id: str
    reserves: list[ReserveInfo]
    """Banquets/reserves."""


class RestaurantSection(IikoModel):
    """Restaurant section."""

    id: str
    """Restaurant section ID."""
    terminal_group_id: str
    """Terminal group ID.

    Can be obtained by `/api/1/terminal_groups` operation.
    """
    name: str
    """Name."""
    tables: list[Table]
    """Tables."""
    schema_: SectionSchema | None = Field(default=None, alias="schema")
    """Table layout."""


class RestaurantSectionEllipse(IikoModel):
    """Restaurant section ellipse."""

    color: Color
    """Color."""
    x: int
    """X coordinate of left point of item."""
    y: int
    """Y coordinate of top point of item."""
    z: int
    """Z-index of item."""
    angle: Decimal
    """Item's angle of slope."""
    width: int
    """Item's width in px."""
    height: int
    """Item's height in px."""


class RestaurantSectionMark(IikoModel):
    """Restaurant section mark."""

    text: str
    """Text."""
    font: Font
    """Font."""
    color: Color
    """Color."""
    x: int
    """X coordinate of left point of item."""
    y: int
    """Y coordinate of top point of item."""
    z: int
    """Z-index of item."""
    angle: Decimal
    """Item's angle of slope."""
    width: int
    """Item's width in px."""
    height: int
    """Item's height in px."""


class RestaurantSectionRectangle(IikoModel):
    """Restaurant section rectangle."""

    color: Color
    """Color."""
    x: int
    """X coordinate of left point of item."""
    y: int
    """Y coordinate of top point of item."""
    z: int
    """Z-index of item."""
    angle: Decimal
    """Item's angle of slope."""
    width: int
    """Item's width in px."""
    height: int
    """Item's height in px."""


class RestaurantSectionTable(IikoModel):
    """Restaurant section table."""

    table_id: str
    """Table ID."""
    x: int
    """X coordinate of left point of item."""
    y: int
    """Y coordinate of top point of item."""
    z: int
    """Z-index of item."""
    angle: Decimal
    """Item's angle of slope."""
    width: int
    """Item's width in px."""
    height: int
    """Item's height in px."""


class SectionSchema(IikoModel):
    """Table layout."""

    width: int
    """Layout width in px."""
    height: int
    """Layout height in px."""
    mark_elements: list[RestaurantSectionMark]
    """Collection of restaurant section marks."""
    table_elements: list[RestaurantSectionTable]
    """Collection of restaurant section tables."""
    rectangle_elements: list[RestaurantSectionRectangle]
    """Collection of restaurant section rectangles."""
    ellipse_elements: list[RestaurantSectionEllipse]
    """Collection of restaurant section ellipses."""
    revision: int
    """Last modified time."""
    is_deleted: bool
    """Is schema deleted."""


class Table(IikoModel):
    """Table."""

    id: str
    """Table ID."""
    number: int
    """Number of table."""
    name: str
    """Table name specified in the organization settings."""
    seating_capacity: int
    """Seating capacity of the table."""
    revision: int
    """Last modified time."""
    is_deleted: bool
    """Is table deleted."""
    pos_id: str
    """POS table Id."""


__all__ = [
    "AddOrderItemsToBanquetRequest",
    "AddOrderPaymentsToBanquetRequest",
    "CancelReserveRequest",
    "ChangeBanquetOrderItemsRequest",
    "ChangeReserveEstimatedStartTimeRequest",
    "ChangeReserveTablesRequest",
    "Color",
    "CreateOrderSettingsBase",
    "CreateReserveRequest",
    "Font",
    "FontStyle",
    "GetRestaurantSectionsRequest",
    "GetRestaurantSectionsResponse",
    "GetRestaurantSectionsWorkloadRequest",
    "GetRestaurantSectionsWorkloadResponse",
    "GetTerminalGroupsByOrganizationsRequest",
    "ReserveGuestsInfo",
    "ReserveInWorkload",
    "ReserveOrder",
    "ReserveResponse",
    "ReservesByIdRequest",
    "ReservesResponse",
    "RestaurantSection",
    "RestaurantSectionEllipse",
    "RestaurantSectionMark",
    "RestaurantSectionRectangle",
    "RestaurantSectionTable",
    "SectionSchema",
    "Table",
]
