"""Models of the terminal endpoints.

Generated by ``python -m codegen`` from the iikoCloud OpenAPI specification. Do not edit by hand.
"""

from __future__ import annotations

from iikocloudapi._base import IikoModel


class CashRegisterListItem(IikoModel):
    """CashRegisterListItem."""

    id: str | None = None
    """Cash register identifier (UUID)"""
    name: str | None = None
    """Cash register name"""
    number: str | None = None
    """Cash register number"""
    status: str | None = None
    """Cash register status"""
    terminal_group_ids: list[str] | None = None
    """Identifiers of the terminal groups linked to the cash register (UUID)"""


class CashRegisterListRequest(IikoModel):
    """CashRegisterListRequest."""

    limit: int | None = None
    """Items per page. Default value: `50`, from `1` to `1000`"""
    offset: int | None = None
    """Offset. Default value: `0`, non-negative"""
    organization_id: str
    """Organization identifier (GUID)"""
    search: str | None = None
    """Case-insensitive substring search by name or number"""
    terminal_group_ids: list[str] | None = None
    """Filter by terminal group identifiers (UUID). Duplicates do not affect the result"""


class CashRegisterListResponse(IikoModel):
    """CashRegisterListResponse."""

    items: list[CashRegisterListItem] | None = None
    """Cash registers"""
    limit: int | None = None
    """Items per page. Default value: `50`, from `1` to `1000`"""
    offset: int | None = None
    """Offset. Default value: `0`, non-negative"""
    total_count: int | None = None
    """Total number of matches before pagination"""


class TerminalListItem(IikoModel):
    """TerminalListItem."""

    computer_name: str | None = None
    """Terminal host address"""
    id: str | None = None
    """Terminal identifier (UUID)"""
    is_anonymous: bool | None = None
    """Anonymous terminal flag"""
    name: str | None = None
    """Terminal name"""
    restaurant_section_ids: list[str] | None = None
    """Identifiers of the dining-hall sections available to the terminal"""


class TerminalListRequest(IikoModel):
    """TerminalListRequest."""

    include_anonymous: bool | None = None
    """Include anonymous terminals. Default value: `false`"""
    organization_id: str
    """Organization identifier (GUID)"""
    search: str | None = None
    """Filter by terminal name"""


class TerminalListResponse(IikoModel):
    """TerminalListResponse."""

    items: list[TerminalListItem] | None = None
    """Terminals"""
    total_count: int | None = None
    """Total number of terminals in the response"""


__all__ = [
    "CashRegisterListItem",
    "CashRegisterListRequest",
    "CashRegisterListResponse",
    "TerminalListItem",
    "TerminalListRequest",
    "TerminalListResponse",
]
